### ISSUE TITLE
Android Builds of the JDK?

### ISSUE THREAD

**Issue by masterjavaofficial** [adoptium/adoptium#101]
Need builds that support Android armv7a and armv8a architectures.

**Comment by karianna** [comment]
@masterjavaofficial - What's the use case for this?  My understanding is that the Android ecosystem only really allows Android SDK to run on the google provided runtime.

**Comment by masterjavaofficial** [comment]
> @masterjavaofficial - What's the use case for this? My understanding is that the Android ecosystem only really allows Android SDK to run on the google provided runtime.

No! You can run anything if it supports the architecture, and bundled within the APK.

[Termux](github.com/termux/termux-app), a **Linux Terminal Emulator** app for Android, is such kind of app which bundles the maximum Linux environment Android can support without needing any root privileges. It also offers its own package [repository](github.com/termux/termux-packages), so anyone can install Python3, Node.js, OpenJDK-17 (only ea-17 features are available), Neovim, Nano editors, Apache 2.0 server and many other programming languages and tools, and even xfce4 or LxQt graphical environments with support for Gtk2 or 3, which you can see and use with VNC Viewer or Microsoft RDP apps. Already many popular open-source softwares have listed Termux in their repositories and indexes, and directly collaborate with them for building and porting those softwares to Android using Termux.

Termux already provides openjdk-17, maven, gradle and ant builds for Android, but the problem is that I can't use JavaFX with those, because the official builds from OpenJFX.io for Linux is incompatible with Android architecture. And I know Adoptium provides JavaFX bundled within the Java SE. So I wanted Android builds of the JDK.

**Comment by karianna** [comment]
Ahhhh, thanks for the context that helps a lot.  Unfortunately, Adoptium does _not_ bundle JavaFX and I'm not aware of JavaFX being ported to that platform just yet.  Gluon is leading the OpenJDK mobile project to get native support for Android.  I'd recommend contacting them at www.gluonhq.com
