### ISSUE TITLE
January 2022 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by sxa** [adoptium/adoptium#109]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922.  Primary platforms (x64 Linux/Windows/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).

👍 results in these Tables means the activity has successfully completed.
⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.
⛔ means there is no build planned for that version/platform combination. 
📂 means activity not yet started.

## JDK 8u322b06

| Platform | jdk8 AQA | jdk8 TCK | jdk8 installers | jdk8 containers | Notes
| ----- | ----- | ----- | ----- | ----- | ----- |
| **x64 Linux** | 👍 | 👍 | 👍 | 👍 |
| **x64 Windows** | 👍 | 👍 | 👍 | 👍 |
| **x64 MacOS** | 👍 | 👍 | 👍 | ⛔ |
| aarch64 Linux | 👍 | 👍 | 👍 | 👍 |
| ppc64le Linux | 👍 | 👍 | 👍 | 👍 |
| arm32 Linux | 👍 | 👍 | 👍 | 👍 |
| ppc64 AIX | 👍 | 👍 | ⛔ | ⛔ |
| x32 Windows | 👍  | 👍 | 👍 | ⛔ |
| sparcv9 Solaris | 👍 | 👍 | ⛔ | ⛔ |
| x64 Solaris | 👍 | 👍 | ⛔ | ⛔ |

### JDK11.0.14.1
| Platform  | jdk11 AQA  | jdk11 TCK | jdk11 installers | jdk11 containers | Notes | 
| ----- | ----- | ----- | ----- | ----- | ----- | 
| [**x64 Linux**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/linux/x64/hotspot/) | 👍      |  👍    | 👍  | 👍  |   | 
| [**x64 Windows**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/windows/x64/hotspot/) |   👍   |  👍    | 👍  | 👍  |   | 
| [**x64 Mac**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/mac/x64/hotspot/) |  👍  | 👍   | 👍  | ⛔ |   | 
| [aarch64 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/linux/aarch64/hotspot/) | 👍   |  👍  | 👍  | 👍  |   | 
| [ppcle64 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/linux/ppc64le/hotspot/) |  👍   |  👍   | 👍  | 👍  |   | 
| [s390x Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/linux/s390x/hotspot/) |   👍    |  👍  | 👍  | 👍  |   | 
| [ppc64 AIX](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/aix/ppc64/hotspot) | 👍  | 👍 | ⛔ |⛔  |   | 
| [x32 Windows](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/windows/x86-32/hotspot/) | 👍   | 👍 | 👍  | ⛔ |   | 
| [arm32 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/artifact/target/linux/arm/hotspot/) |  👍  | 👍 | 👍 | 👍  |   | 
| [x64 alpine-Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/artifact/target/alpine-linux/x64/hotspot/) | 👍 |  ⏳   | ⛔  | 👍  |  This will be a headless build | 

### JDK11.0.14
| Platform  | jdk11 AQA  | jdk11 TCK | jdk11 installers | jdk11 containers | Notes | 
| ----- | ----- | ----- | ----- | ----- | ----- | 
| [**x64 Linux**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/linux/x64/hotspot/) | 👍      |  👍    | 👍  | 👍  |   | 
| [**x64 Windows**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/windows/x64/hotspot/) |   👍      |  👍    | 👍  | 👍  |   | 
| [**x64 Mac**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/mac/x64/hotspot/) |   👍    | 👍   | 👍  | ⛔ |   |
| [aarch64 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/linux/aarch64/hotspot/) | 👍      |  👍    | 👍  | 👍  |   | 
| [ppcle64 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/linux/ppc64le/hotspot/) |  👍      |  👍   | 👍  | 👍  |   | 
| [s390x Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/linux/s390x/hotspot/) |   👍    |  👍  | 👍  | 👍  |   | 
| [ppc64 AIX](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/aix/ppc64/hotspot) |   👍    | 👍 | ⛔ |⛔  |   | 
| [x32 Windows](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/windows/x86-32/hotspot/) | 👍  | 👍   | 👍  | ⛔ |   | 
| [arm32 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/artifact/target/linux/arm/hotspot/) |   👍      | 👍  | 👍  | 👍  |   | 
| [x64 alpine-Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/artifact/target/alpine-linux/x64/hotspot/) | 👍    |  👍   | ⛔  | 👍  |  This will be a headless build | 

## JDK 17.0.2+8

| Platform | jdk17 AQA | jdk17 TCK | jdk17 installers | jdk17 containers | Notes
| ----- | ----- | ----- | ----- | ----- | ----- |
| **x64 Linux** | 👍 | 👍 | 👍 | 👍 |
| **x64 Windows** | 👍 | 👍 | 👍 | 👍 |
| **x64 MacOS** | 👍 | 👍 | 👍 | ⛔ |
| aarch64 Linux | 👍 | 👍 | 👍 | 👍 |
| ppc64le Linux | 👍 | 👍 | 👍 | 👍 |
| ppc64 AIX | 👍 | ⏳ | ⛔ | ⛔ |
| x32 Windows | 👍 | 👍 | 👍 | ⛔ |
| arm32 Linux | 👍 | 👍 | 👍 | 👍 |
| s390x Linux | 👍 | 👍 | 👍 | 👍 |
| x64 Alpine [JDK](musl) | 👍 | 👍 | 👍 | 👍 |
| aarch64 macos | 👍 | 👍  | 👍 | ⛔ |

**Comment by lobax** [comment]
Is there an ETA for when Windows X86 builds will be available?

**Comment by ctipper** [comment]
So [note \#3](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922) implies that there is an astonishing amount of manual labour running these tests, work which presumably is duplicated from openjdk release. Is anyone concerned that Jan PSU was 18 Jan and yet here we are 10 days later with only half of tests complete? I note that Azul binaries have been available for several days now, maybe their release process is more streamlined, but I don't understand the need to duplicate effort?

**Comment by karianna** [comment]
> So [note #3](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922) implies that there is an astonishing amount of manual labour running these tests, work which presumably is duplicated from openjdk release. Is anyone concerned that Jan PSU was 18 Jan and yet here we are 10 days later with only half of tests complete? I note that Azul binaries have been available for several days now, maybe their release process is more streamlined, but I don't understand the need to duplicate effort?

Every vendor has to independently run the TCK tests (there are very strict rules for this). In addition to those TCK tests we also run the AQA tests (which is unique to us and executes millions of functional tests across all platforms).  Lastly, we run on more platforms than any other vendor :-).

So we do tend to release later than other vendors but we're OK with that :-).

**Comment by davidkarlsen** [comment]
You all do an awesome job!
But the status says v17 is now OK for linux, but on the webside, only mac/win is updated to 17.0.2, while linux is still at 17.0.1 for x86?

**Comment by losmurfs** [comment]
Did linux package repositories get dropped?

**Comment by sxa** [comment]
> Did linux package repositories get dropped?

No they're still there details [here](https://blog.adoptium.net/2021/12/eclipse-temurin-linux-installers-available/) but haven't been updated for these releases yet. Will probably be at the start of next week.

**Comment by Rakeshsim1** [comment]
Hello, I am using Open JRE Package (OpenJDK8U-jre_x64_windows_hotspot) and not able to find Java WebStart (IceTea Web) while installing the New package for both 32 and 64 bits Version. JavaWeb (Ice Team Web) was available untill version 8u301 which could be easily installed install Wizard inside custom settings and now it is missing New version 8u322.

Can anyone Advise what changes have been made and how this Java Web Start Feature can be accessed. We need to Deploy this for large number of users.

Thanks In Advance
Regards,
Rakesh

**Comment by j0kkeri** [comment]
> > Hello, I am using Open JRE Package (OpenJDK8U-jre_x64_windows_hotspot) and not able to find Java WebStart (IceTea Web) while installing the New package for both 32 and 64 bits Version. JavaWeb (Ice Team Web) was available untill version 8u301 which could be easily installed install Wizard inside custom settings and now it is missing New version 8u322.
> > Can anyone Advise what changes have been made and how this Java Web Start Feature can be accessed. We need to Deploy this for large number of users.
> > Thanks In Advance Regards, Rakesh
> 
> Hi Rakesh, as part of moving to Eclipse ADoptium we were no longer able to support Java Webstart / IcedTea. Please see https://blog.adoptopenjdk.net/2018/10/using-icedtea-web-browser-plug-in-with-adoptopenjdk/ for details.

I will also be missing the "integrated" ITW in the installer. May I ask if the reason is technical, licence issue or just strategical decision?

**Comment by sxa** [comment]
> website

Can't remember what happened there at the time, but it's up there now - hopefully you can see it now.

**Comment by j0kkeri** [comment]
> > > Hello, I am using Open JRE Package (OpenJDK8U-jre_x64_windows_hotspot) and not able to find Java WebStart (IceTea Web) while installing the New package for both 32 and 64 bits Version. JavaWeb (Ice Team Web) was available untill version 8u301 which could be easily installed install Wizard inside custom settings and now it is missing New version 8u322.
> > > Can anyone Advise what changes have been made and how this Java Web Start Feature can be accessed. We need to Deploy this for large number of users.
> > > Thanks In Advance Regards, Rakesh
> > 
> > 
> > Hi Rakesh, as part of moving to Eclipse ADoptium we were no longer able to support Java Webstart / IcedTea. Please see https://blog.adoptopenjdk.net/2018/10/using-icedtea-web-browser-plug-in-with-adoptopenjdk/ for details.
> 
> I will also be missing the "integrated" ITW in the installer. May I ask if the reason is technical, licence issue or just strategical decision?

Never mind, found the answer here:
[https://adoptium.net/faq.html?variant=openjdk11#IcedTeaWeb](https://adoptium.net/faq.html?variant=openjdk11#IcedTeaWeb)

**Comment by kbotond** [comment]
What happened to the x86 Windows version of 17.0.2? It has been in the works for many weeks now.

**Comment by sxa** [comment]
> What happened to the x86 Windows version of 17.0.2? It has been in the works for many weeks now.

We've seen a potential regression in the Vector tests with that version that we have not yet been able to explain. To be honest, you're the first person that has seemingly noticed its absence, although it looks like a few others have given you a :+1: on it.

**Comment by rednoah** [comment]
Thanks for the update on the `win-x86` build. I guess that means it's not coming anytime soon so best to stick with previous releases for now.

**Comment by sxa** [comment]
@kbotond @rednoah I've [just published it](https://adoptium.net/releases.html?variant=openjdk17) [github direct link](https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.2%2B8) if they haven't shown up on the main web site by the time you read this, but be aware there are some potential issues which we've decided to consider non-blocking:
- [A Vector test failure from the incubator suite](https://github.com/adoptium/aqa-tests/issues/3279)
- [A crash that can show up while using JFR](https://github.com/adoptium/aqa-tests/issues/3277)
