### ISSUE TITLE
Memo to self - RELEASING.md doc updates for:

### ISSUE THREAD

**Issue by adamfarley** [adoptium/adoptium#117]
Memo to self - RELEASING.md doc updates for:
- Ensuring mirror jobs (`git-skara-jd*`) are run and have the tags before initiating pipelines
- Add info on new `aqaReference` parameter
- Fix link to sample banner PR
- Resolving merge conflicts (On machine using the `adoptium_temurin_bot_ssh_key` from `secrets` or run the mirror script on a local machine with push permission, resolve, `git add`, `git merge --continue` `git push` Usually to the `release` branch that you're on, then re-run the mirror script.

_Originally posted by @sxa in https://github.com/adoptium/adoptium/issues/104#issuecomment-1015909279_

**Comment by sxa** [comment]
Recreated at https://github.com/adoptium/temurin-build/issues/2848
