### ISSUE TITLE
Bi-weekly Adoptium Community Call - May 18, 2021

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#13]
**Time**

Tuesday May 18, 2021 4pm-5pm GMT (11am-12pm EST/Ontario)

**Location**

https://bluejeans.com/956754991/2833?src=calendarLink

Add this [recurring bi-weekly Adoptium Community Call](https://calendar.google.com/event?action=TEMPLATE&tmeid=MjViajc5a3RxczFlMGNuaXN2OW5paTQ5cmhfMjAyMTAzMDhUMTYwMDAwWiBjX3Vhbm5vdW1zNWhvMG9saGprM3VsZWNka2JjQGc&tmsrc=c_uannoums5ho0olhjk3ulecdkbc%40group.calendar.google.com&scp=ALL) to your calendar, if you wish.

**Overall Purpose**

Mainly to make announcements regarding planned actions that affect the Adopt community
(Emphasis on non-test efforts, as those are covered in AQAvit call on Wednesdays)

Secondary purposes include debate, discussion, and community socializing.

Call to be recorded for reference, and linked in this issue afterwards.

**Proposed Meeting Agenda** - TBD / topics to be confirmed

- First Temurin release - status update 
- Update on linux installers work 
- Update on reproducible builds prototype

**Comment by adamfarley** [comment]
Proposed agenda additions:

- Review PMC Highlights.
- Make a “revoked public access to builds” announcement.
- Review this issue growth chart.

![image](https://user-images.githubusercontent.com/26874628/118674932-178cbc80-b7f2-11eb-9a8e-03e6c8dcb6a4.png)

**Comment by adamfarley** [comment]
[Next Session.](https://github.com/adoptium/adoptium/issues/19)
