### ISSUE TITLE
March 2022 Release Status per Platform for jdk-18+36

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#131]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).

👍 results in these Tables means the activity has successfully completed.
⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.
⛔ means there is no build planned for that version/platform combination.
📂 means activity not yet started.

### jdk-18+36
| Platforms  | jdk18 AQA  | jdk18 TCK | jdk18 installers | jdk18 containers | Notes |
| ----- | ----- | ----- | ----- | ----- | ----- |
| **x64 Linux**| 👍 | 👍 | 👍 | 👍 |   |
| **x64 Windows** | 👍 | 👍 | 👍  | 👍  |   |
| **x64 Mac** | 👍 | 👍 | 👍  | ⛔ |   |
| aarch64 Linux | 👍 | 👍 | 👍 | 👍 |   |
| ppcle64 Linux | 👍 | 👍 | 👍 | 👍 |   |
| s390x Linux | 👍 | 👍 | 👍 | 👍 |   |
| ppc64 AIX| 👍 | ⏳ | ⛔ |⛔  |   |
| x32 Windows | 👍 | 👍 | 👍 | ⛔ |   |
| arm32 Linux | 👍 | 👍 | 👍 | 👍 |   |
| x64 alpine-Linux | 👍 | 👍 | 👍 | 👍 | This will be a headless build |
| aarch64 Mac | 👍 | 👍  | 👍 | ⛔ |   |

**Comment by jiekang** [comment]
I noticed I'm getting 404 not found for the links to the different pipelines, such as https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk18-pipeline/xxx/artifact/target/linux/x64/hotspot/

I'm guessing the `xxx` is not intended. Is this expected? Do we want these to be visible to the public?

**Comment by smlambert** [comment]
re: https://github.com/adoptium/adoptium/issues/131#issuecomment-1089257476 those links are not public (as they refer to a GA candidate build that has not yet passed through the TCK process, therefore, we are not to share them publicly as they are without the extra decoration of an EA/nightly build ... files/statements about the build being 'beta'), so I did not bother to change the links from the template for ease of folks with access to those builds.  I think we should just remove the hyperlink.

It was one of the items I was going to flag in the retrospective tomorrow.

**Comment by jiekang** [comment]
Makes sense to remove them if they aren't meant to be accessible to the same group that can see this issue. Thanks!
