### ISSUE TITLE
General Retrospective for April 2022 Releases

### ISSUE THREAD

**Issue by adamfarley** [adoptium/adoptium#138]
**Summary**

A retrospective for all efforts surrounding the titular releases. 

All community members are welcome to contribute to the agenda via comments below.

This will be a virtual meeting after the release, with at least a week of notice in the #release Slack channel.

On the day of the meeting the agenda items will be iterated over, with a list of actions added in a comment at/near the end.

Invited: Everyone.

**Time, Date, and URL**

Time: TBD
Date: TBD

URL: TBD
Dial-in: TBD
PIN: TBD

**Details**

Retrospective Owner Tasks (in order):

- [ ] Post this issue's URL on the \#Release Slack channel around the start of the new release.
- [ ] Copy actions from the previous retrospective into this issue, while ignoring actions that are ticked or have issue links (i.e. clearly-completed actions).
- [ ] Wait until 90% of all builds have been released, with no clear signs of additional respins.
- [ ] Announce the retrospective Slack call's date + time on \#Release at least one full week in advance, and send out meeting invites.
- [ ] Host the slack call for the retrospective, including:
  - [ ] Iterating over the actions from the previous retrospective issue, ticking off completed items.
  - [ ] Iterate over the agenda, ensuring everything gets debated.
  - [ ] Create a clear list of actions at the end of the retrospective, including volunteer names.
- [ ] Create a new retrospective issue for the next release.
- [ ] Set yourself a calendar reminder so that you remember to commence step 1 (in the new issue) just before the next release.
- [ ] Close this issue.

**Comment by andrew-m-leonard** [comment]
It would be good to have some form of "immediate" Alert to "blocking" Release situations, eg:
-     Mirror job failure
-     Release pipeline build is stuck/hung, eg.nodes down, test job hung

**Comment by zdtsw** [comment]
Update https://github.com/temurin-compliance/temurin-compliance/blob/master/doc/ExecutingTests.md to make it easy to understand and follow:
- how to find the "test machine": follow steps from Jenkins to inventory to IP and port etc
- how to connect to different target OS: special setting on Mac/Win, different commands to use. 
- difficulty for certain test ( not in the gotchas issue): modal Jdialog need to close before click "Yes", press F8 may have "error dialog", type letter is auto-test, etc

**Comment by zdtsw** [comment]
maybe use label set on  a jenkins agent pool (multiple agent) to run "achieve" job if it is to upload test result from "automatic test" from Jenkins job.

Actually, I am thinking if it is better to split the job into two jobs: 
one for interactives+auto_manual , 
another one for automatic  test

some small details to make it easy to run the job:
LABEL only need to be as parameter for "interactive" but no need to be as parameter for the "auto" job.
versions and tag do as dropdown to mitigate human input error. 
server, github_token, user_and_repo etc can be hard-coded in the job (unless we do need it be to configurable)
etc

**Comment by zdtsw** [comment]
set information for each test jobs description:
current we have TARGET and LABEL. mainly each build (for the same job) get same value, not very useful.
suggestion to have:
- NODE (with node name) so we can have a better view if certain nodes always fail than others. (e.g disconnection of agent etc)
- jdk version (e.g 8u332b09)

**Comment by zdtsw** [comment]
find a better way to secure the test machine  is not being used for multiple tests (auto/interactive) at the same time.
we can take node offline from jenkins to block all auto test on that node, but if we try to do interactives as fast as we can, there is a chance two people are using the same test machine. normally it should not be a problem (if sufficient resource on the machine) but if requires "agent" to be used or some background process, might cause issue.

**Comment by zdtsw** [comment]
how to secure test machine? 
- if we cannot get more hardware, we need to have better way to escalate problems: contact person
- alerts/alarms if we have more than 50% HW( machine for these high prio. arch ) are down so someone can take action ASAP
- etc

**Comment by jiekang** [comment]
We should improve release reporting to the public to give a clear place and sign that a release artifact is available to download. (tarball, docker image, installer, etc.)

**Comment by smlambert** [comment]
Issue with linuxNew installer job hung and unable to upload certain images (machines for arm32 and ppcle64) due to no machine available (the single machine taken by docker multiarch job, https://ci.adoptopenjdk.net/job/openjdk_build_docker_multiarch/)

**Comment by sophia-guo** [comment]
LinuxNew installer Debian ones doesn't use cross building, which means the Debian installer jobs need to run on corresponding platforms. There are limited nodes for those platforms right now (https://ci.adoptopenjdk.net/label/docker&&linux&&${arch}/, some only have one node), which are heavily used by [docker multiarch job](https://ci.adoptopenjdk.net/job/openjdk_build_docker_multiarch/).

**Comment by sclassen** [comment]
While looking at #140 
I have a very hard time to distinguish `successfully completed` and `not yet started` as they have almost the same color and the icons are small so they don't stick out clearly.
Would it be possible to chose another icon for one of these states which has a different color and or a distinguishable shape
Maybe :heavy_check_mark: `:heavy_check_mark:`  or :checkered_flag:  `:checkered_flag:` for completed tasks

Also in that regards is there a semantic difference between columns which are initially empty and columns which are initially in `not yet started` :open_file_folder: ??

**Comment by andrew-m-leonard** [comment]
aqa-tests triage gets quite tricky due to large number of extended / special failures, expecially in the 2nd/3rd priority platforms, eg.armLinux. Can we fix the exclude issue (eg.for arm?)
A number of tests also only work on certain nodes...

**Comment by jamesbroadhead** [comment]
Please discuss changing the policy of holding repo-releases until all packages are available. 
https://github.com/adoptium/adoptium/issues/140#issuecomment-1114746250

We must install jdk packages through our package manager so that our security scanner picks it up correctly. 
We also have SLAs to meet for deploying fixed versions of software after a CVE has been detected. 
We would much prefer if packages were available through yum etc. as soon as the tarballs are available. 

Thank you!

**Comment by sxa** [comment]
@jamesbroadhead Absolutely we need to change the process and we are very much aware that the current situation is not good.

**Comment by sxa** [comment]
>  Would it be possible to chose another icon for one of these states which has a different color and or a distinguishable shape

@sclassen I've already got a proposal in to replace those with different ones as I don't think the current ones are ideal - it just didn't get implemented before this release.

> Also in that regards is there a semantic difference between columns which are initially empty and columns which are initially have a not yet started open_file_folder ??

No - the 'initially empty' ones are new ones that we're trialling for this release and they were added as blanks, although I agree that this convention could be confusing. The real difference is that e.g. the tarball published column is a definite "Yes/No" and there is no "in-progress" state so the other icons are not so useful there.

**Comment by sxa** [comment]
> any good way to have a central place collect all these pages, so we can easily bookmark it and click to different pages?

The main status document which we point end-users to should be the master page. Bear in mind that for temurin-compliance the pages are not (cannot) be publicly visible so adding those in would only cause confusion, but I agree that we could link to the issues for AQA triage from there.

**Comment by sxa** [comment]
Revisit process for ship approvals

**Comment by Haroon-Khel** [comment]
Retrospective items:

* Release champion needs permissions to build/rebuild sign_installer jobs
* sign_installer jobs should stay around for longer

**Comment by karianna** [comment]
For those watching, linuxNew has been renamed to linux
