### ISSUE TITLE
April 2022 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/adoptium#140]
Please follow live updates in the [release](https://adoptium.slack.com/archives/CLCFNV2JG) channel in the Adoptium Slack workspace.

Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).

👍 results in these Tables means the activity has successfully completed.
⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.
⛔ means there is no build planned for that version/platform combination.
📂 means activity not yet started.

### JDK8u332 
Tag available & pipeline launched on April 22nd, as at April 27th, 1/11 tarballs published.  At May 4, 7/11 published.
| Platform | [jdk8 AQA](https://github.com/adoptium/aqa-tests/issues/3603)  | jdk8 TCK | jdk8 installers | jdk8 containers | Tarball Published | Notes |
| -----  | ----- | ----- | ----- | ----- | ----- | ----- |
| [**x64 Linux**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/xxxx/artifact/target/linux/x64/hotspot) | 👍 | 👍 | 📂 | 👍🏻  | 👍   |  |
| [**x64 Windows**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/xxxx/artifact/target/windows/x64/hotspot) | 👍 | 👍 | 👍🏻 | 📂 | 👍🏻   |  |
| [**x64 Mac**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/xxxx/artifact/target/mac/x64/hotspot) | 👍 | 👍  | 📂 | ⛔ | 👍  |  |
| [aarch64 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/xxxx/artifact/target/linux/aarch64/hotspot) | 👍  | 👍 | 📂 | 👍🏻  |  👍  |  |
| [ppcle64 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/xxxx/artifact/target/linux/ppc64le/hotspot) | 👍 | 👍 | 📂 | 👍🏻  |  👍🏻  |  |
| [ppc64 AIX](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/xxxx/artifact/target/aix/ppc64/hotspot) | 👍  | 👍  | ⛔ | ⛔ | 👍 |  |
| [x32 Windows](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/xxxx/artifact/target/windows/x86-32/hotspot) | 👍  | 👍 | 📂 | ⛔ | 👍  |  |
| [arm32 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/yyyy/artifact/target/linux/arm/hotspot) | 👍  | 👍 | 📂 | 👍🏻  | 👍    |  |
| [sparcv9 solaris](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/xxxx/artifact/target/solaris/sparcv9/hotspot) | 👍  | ⌛ | ⛔  | ⛔ |   | machine issue (May12) |
| [x86 solaris](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/xxxx/artifact/target/solaris/x64/hotspot) |  👍  | 👍    | ⛔  | ⛔ | 👍  |  |
| [x64 alpine-Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/xxxx/artifact/target/alpine-linux/x64/hotspot/) | 👍 | 👍  | ⛔  | 📂 |  👍🏻  | headless build |

### JDK11.0.15 
Tag available & pipeline launched late April 19th, as at April 26th 8/11 tarballs published & containers available. May 4, 8/11.
| Platform  | [jdk11 AQA](https://github.com/adoptium/aqa-tests/issues/3596)  | jdk11 TCK | jdk11 installers | jdk11 containers | Tarball Published |Notes |
| ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| [**x64 Linux**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/linux/x64/hotspot/) | 👍  | 👍| 👍 | 👍  |  👍  |   |
| [**x64 Windows**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/windows/x64/hotspot/) | 👍  | 👍 | 👍🏻  | 👍 | 👍   |   |
| [**x64 Mac**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/mac/x64/hotspot/) | 👍  | 👍 | 📂 | ⛔ | 👍  |   |
| [aarch64 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/linux/aarch64/hotspot/) | 👍  | 👍  | 👍 | 👍 |  👍 |   |
| [ppcle64 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/linux/ppc64le/hotspot/) |  👍  | 👍 | 👍 | 👍 | 👍  |   |
| [s390x Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/linux/s390x/hotspot/) | 👍  | 👍 | 👍 | 👍 | 👍  |   |
| [ppc64 AIX](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/aix/ppc64/hotspot/) | 👍 | 👍  | ⛔ |⛔ |   |  machine issues |
| [x32 Windows](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/windows/x86-32/hotspot/) | 👍  | 👍 | 👍🏻   | ⛔ |  👍🏻  |   |
| [arm32 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/linux/arm/hotspot/) | 👍  | 👍  | 👍 | 👍 |  👍  |   |
| [x64 alpine-Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/xxxx/artifact/target/alpine-linux/x64/hotspot/) | 👍  | 👍 | 📂 | 👍 | 👍  | headless build  |
| [aarch64 Mac](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxxx/artifact/target/mac/aarch64/hotspot/) | 👍  | 👍 | 👍 | ⛔ | 👍  |   |

### JDK17.0.3 
Tag available & pipeline launched late April 19th, as at April 27th 8/11 tarballs published & containers available.  May 4, 9/11.
| Platforms  | [jdk17 AQA  ](https://github.com/adoptium/aqa-tests/issues/3594)| jdk17 TCK | jdk17 installers | jdk17 containers | Tarball Published | Notes |
| ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| [**x64 Linux**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/linux/x64/hotspot/)| 👍 | 👍   | 👍 | 👍  |  👍  | |
| [**x64 Windows**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/windows/x64/hotspot/) | 👍  | 👍 | 👍🏻   | 👍   | 👍   | |
| [**x64 Mac**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/mac/x64/hotspot/) | 👍 | 👍 | 📂  | ⛔ |  👍  | |
| [aarch64 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/linux/aarch64/hotspot/) | 👍  | 👍  | 👍 | 👍  | 👍   | |
| [ppcle64 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/linux/ppc64le/hotspot/) | 👍 | 👍 | 📂 | 👍  | 👍   | |
| [s390x Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/linux/s390x/hotspot/) | 👍 | 👍 | 👍 | 👍  | 👍   | |
| [ppc64 AIX](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/aix/ppc64/hotspot/)| 👍 | ⌛ | ⛔ |⛔  |   | machine issues |
| [x32 Windows](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/windows/x86-32/hotspot/) | 👍 | 👍 | 👍🏻 | ⛔ |  👍🏻  | |
| [arm32 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/linux/arm/hotspot/) | 👍  | 👍  | 📂 | 👍  | 👍   | |
| [x64 alpine-Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/alpine-linux/x64/hotspot/) | 👍  | 👍  | 📂 | 👍  | 👍  | headless build |
| [aarch64 Mac](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/mac/aarch64/hotspot/) | 👍 | 👍  | 📂 | ⛔ | 👍🏻   | |

### JDK18.0.1 
Tag available & pipeline launched April 20th, as at April 27th 2/11 tarballs published.  May 4, 9/11 published.
| Platforms  | [jdk18 AQA](https://github.com/adoptium/aqa-tests/issues/3599)  | jdk18 TCK | jdk18 installers | jdk18 containers | Tarball Published | Notes |
| ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| [**x64 Linux**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/linux/x64/hotspot/)| 👍   | 👍 | 📂 | 👍🏻  | 👍   |   |
| [**x64 Windows**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/windows/x64/hotspot/) | 👍  | 👍 | 👍🏻   | 📂  | 👍   |   |
| [**x64 Mac**](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/mac/x64/hotspot/) | 👍  | 👍  | 📂  | ⛔ |  👍   |   |
| [aarch64 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/linux/aarch64/hotspot/) | 👍  | 👍 | 📂 | 👍🏻 |  👍 |   |
| [ppcle64 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/linux/ppc64le/hotspot/) | 👍 | 👍 | 📂 | 👍🏻  | 👍  |   |
| [s390x Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/linux/s390x/hotspot/) | 👍 | 👍 | 📂 | 👍🏻  | 👍  |   |
| [ppc64 AIX](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/aix/ppc64/hotspot/)| 👍 | ⌛ | ⛔ |⛔  |   | machine issues  |
| [x32 Windows](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/windows/x86-32/hotspot/) | 👍  | 👍 | 👍🏻  | ⛔ | 👍   |   |
| [arm32 Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/linux/arm/hotspot/) | 👍  | 👍  | 📂 | 👍🏻 | 👍🏻   |   |
| [x64 alpine-Linux](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/alpine-linux/x64/hotspot/) | 👍  | 👍  | 📂 | 👍🏻  | 👍  | headless build  |
| [aarch64 Mac](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/xxx/artifact/target/mac/aarch64/hotspot/) | 👍  | 👍  | 📂 | ⛔ | 👍 |   |

**Comment by alkum** [comment]
Can you please search-replace the :+1: with something more easily recognizable (different color) like :heavy_check_mark: ? Thanks!

**Comment by Morl99** [comment]
I am sure many people not very familiar with the JDK release process will go to this issue because they are worried about the vulnerability. Would you be able to provide a legend what the different columns actually mean? I have no idea what AQA and TCK mean and if I should care. After looking at this page, I don't really know when to expect a release (in my case an updated container). I looked at the linked issue, but it seems kind of outdated and also isn't tangible for me as an outsider. 

And not to forget: Thanks for all the hard work you put into it, this is in no way meant to be a complaint, I just wanted to give you an outsider perspective. I have been on your side for other projects and I know, that you quickly get blind sighted, because it all looks so natural. I am solely commenting in this issue since it is linked from the adoptium homepage. If there is a better place to get this information, please adjust the link.

**Comment by JBritannia** [comment]
@Morl99 TCK is Oracle's proprietary test suite that a build must pass in order to be called Java (TM).
AQA is then AdoptOpenJDK's own foss tests. It's way more comprehensive. When all this became part of Eclipse, it just stuck around even though they now have access to TCK. It's just another layer of QC.
The working group is really poor. They don't have no where enough manpower and hardware to speed up the process so for popular platforms it'll take around a week or 2. You can help Adoptium through donations. Check out Eclipse Foundation's website

**Comment by Haroon-Khel** [comment]
@Morl99 The AQA test progress for each JDK can be tracked here
https://github.com/adoptium/aqa-tests/issues/3599 JDK18
https://github.com/adoptium/aqa-tests/issues/3596 JDK11
https://github.com/adoptium/aqa-tests/issues/3594 JDK17

The JDK8 pipeline has not yet been kicked off

**Comment by koldat** [comment]
I see that Java 8 is missing x64 alpine-Linux. Did Adoptium dropped the support for it?

**Comment by jeffalder** [comment]
@Haroon-Khel Adoptium hasn't previously released an aarch64 Mac (M1) port for Java 11. Is this a new supported platform?

**Comment by smlambert** [comment]
re: https://github.com/adoptium/adoptium/issues/140#issuecomment-1106579975 - it is recently added yes... https://github.com/adoptium/ci-jenkins-pipelines/pull/275

**Comment by sxa** [comment]
@jeffalder I added the support for building it fairly recently. The plan is to release it if it passes all of our tests :-)

**Comment by sxa** [comment]
> manpower and hardware to speed up the process so for popular platforms (x64 Win, Linux, Mac that is) it'll take around a week or 2 for the test to be done 

Windows/mac/linux on x64 are the platforms we prioritise and we should be able to get those out in less than a week. For JDK17 Linux went out yesterday, mac JDK17 as well as Linux 11 and 18 today, Windows 17 isn't too far behind :-) This is also the first time we've shipped four releases simultaneously (8, 11 and 17 LTS plus 18) and we have people frantically working through them all trying to get the releases out.

As you suggest we're mostly limited now in the amount of time it takes us to complete the testing with the release binaries, and the TCK certification specifically, and we can't give any more detail on how that is progressing until it's complete for each platform. We prioritize the three I mentioned, and we're doing those in order 17, 11, 8, 18 for this release and while I wish we could provide clearer ETAs it's very much a case of "When it's ready" at the moment.

**Comment by sxa** [comment]
> Can you please search-replace the +1 with something more easily recognizable (different color) like heavy_check_mark ? Thanks!

Is that to distinguish it from the folder icon which is also yellow? I was planning to replace the folder icon (which is quite meaningless) with ⏸ as in "paused and waiting to start" (I hadn't got round to updating the status for this release!)

**Comment by smlambert** [comment]
<img width="407" alt="Screen Shot 2022-04-22 at 2 45 09 PM" src="https://user-images.githubusercontent.com/2836948/164775585-10cd5bae-a222-4044-a1bb-b333b096780f.png">

**Comment by smlambert** [comment]
re: https://github.com/adoptium/adoptium/issues/140#issuecomment-1106755911 
see also https://adoptium.net/aqavit

> Should you care what AQA and TCK are?
If you are curious about these tests and why they are both important (AQA for quality and TCK for compliance), check out https://github.com/AdoptOpenJDK/TSC/issues/222#issuecomment-818020349

**Comment by borisdan** [comment]
Hi!
The deb package isn't availalble on the repo yet, is it coming soon?

**Comment by Haroon-Khel** [comment]
@borisdan We will begin releasing (Linux) Installers for each JDK once that JDK's platforms are complete. For example, for JDK17, we are waiting on x64 Alpine Linux

**Comment by minhtran83** [comment]
I still can't see Mac OS arm64 for JDK 11.0.15 here https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.15%2B10

**Comment by Haroon-Khel** [comment]
@minhtran83 Hi, that binary has not been released yet. Our team is working on it 👍🏻

**Comment by minhtran83** [comment]
Thanks a lot @Haroon-Khel. I can see it in the nightly build page

**Comment by jorgeyanesdiez** [comment]
> Can you please search-replace the ✔️ with something more easily recognizable (different color) like ✔️ ? Thanks!

While they think about it, you can use an UserScript with [Tampermonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) or equivalent
```
// ==UserScript==
// @name         Replace Adoptium release tracking icons
// @namespace    https://github.com/adoptium/adoptium
// @version      1.0
// @description  Replaces adoptium release tracking icons for better readability
// @author       jorgeyanesdiez@users.noreply.github.com
// @match        https://github.com/adoptium/adoptium/issues/140
// @icon         https://github.githubassets.com/images/icons/emoji/unicode/2714.png
// @require      http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    /* global $ */ //For the linter
    $("g-emoji[alias='+1']").each(function( index ) {
        $(this).text($(this).text().replaceAll("👍", "✔️"))
    });
})();
```

**Comment by smlambert** [comment]
re: https://github.com/adoptium/adoptium/issues/140#issuecomment-1113423973 - help wanted, since the new website went live a month ago, we have been without a release notes page: https://github.com/adoptium/website-v2/issues/103 and looking for someone to lift one back up.

Since our builds are directly builds of OpenJDK source code, you can look at release notes for the OpenJDK project in the absence of the page at our site (for [example from foojay](https://foojay.io/java-17/?quarter=042022&tab=component)).

**Comment by yanns** [comment]
Thanks a lot. A very welcome functionality would be the ability to be notified whenever a new docker image is published.

**Comment by borisdan** [comment]
> > @borisdan We will begin releasing (Linux) Installers for each JDK once that JDK's platforms are complete. For example, for JDK17, we are waiting on x64 Alpine Linux
> 
> That sounds strange. Why hold back the installers for a specific architecture when there is already a tarball? The installers should be available around the same time as the tarballs, so that users of your [repository](https://packages.adoptium.net/artifactory) can use them at the same time as users of the tarballs.

Hi team - is there an expected timeline on releasing the installers to the repo? These are critical security fixes and we are looking to apply the patch ASAP.

**Comment by adessaigne** [comment]
Hello,
I just noticed that JDK 17.0.3.1 (as well as other backports) was out to fix https://bugs.openjdk.java.net/browse/JDK-8285445
Is Adoptium affected? If so, will it be included in this issue or in a dedicated one? Thank you 👍

**Comment by zdtsw** [comment]
> Hello, I just noticed that JDK 17.0.3.1 (as well as other backports) was out to fix https://bugs.openjdk.java.net/browse/JDK-8285445, https://bugs.openjdk.java.net/browse/JDK-8284920 and https://bugs.openjdk.java.net/browse/JDK-8278186 Is Adoptium affected? If so, will it be included in this issue or in a dedicated one? Thank you +1

isn't JDK17.0.3.1 released yesterday (on 2022-05-02)? which is not included in Adoptium's April release (from 2022-04-19 JDK17.0.3)
I think you can expect the fix to be included in 17.0.4 (in July)
@smlambert correct me if I am wrong

**Comment by adessaigne** [comment]
> I think you can expect the fix to be included in 17.0.4 (in July)
Oracle thought they shouldn't wait for the 17.0.4 and release these bug fixes sooner. As far as I can remember there's no x.y.z.1 release until now. Maybe it is worth investigating if 17.0.3.1 (and others) should be delivered by Adoptium too.

**Comment by wongkwl** [comment]
The 17.0.3 release breaks Wildfly 26.0.1 from starting properly.  It is the same symptom as with Oracle JDK 17.0.3.

**Comment by Tomatenjoe** [comment]
Hi! I'm looking for a jdk-11.0.15+10 for Aix (ppc64). For all other available OS this version is already available but not for AIX. Is it still in test status? Thanks for an update!

**Comment by sxa** [comment]
@Tomatenjoe It is still in testing - our AIX TCK infrastructure suffered a machine failure which we expect to be resolved today, then we can resume work through the testing. Sorry for the delay on this one, but the outage was outside our direct control.

**Comment by sxa** [comment]
> Windows JRE8 332 msi and zip are still missing. when will they be ready?

I'm just back from vacation but hopefully you've seen they are now available @Tomatenjoe

**Comment by sxa** [comment]
> As far as I can remember there's no x.y.z.1 release until now. Maybe it is worth investigating if 17.0.3.1 (and others) should be delivered by Adoptium too.

I think we've only had two of them since I've been working at the project - the most recent was earlier thisk year when we had 11.0.14.1 so there is precedent: https://twitter.com/adoptium/status/1494321565059608580

**Comment by ZanzaZanzara** [comment]
> > Windows JRE8 332 msi and zip are still missing. when will they be ready?
> 
> I'm just back from vacation but hopefully you've seen they are now available @Tomatenjoe

yea thanks. already downloaded and deployed yesterday.

**Comment by sxa** [comment]
@ZanzaZanzara Apologies for tagging tomatenjoe instead of you in my post, but good to hear you have it deployed now 👍🏻

**Comment by adessaigne** [comment]
> Also, to be clear, 17.0.3.1 is not a formal level at openjdk (at the time of writing) as it does not appear in the tags at https://github.com/openjdk/jdk17u/tags

You're right and this is strange because the tag does exist in 18 https://github.com/openjdk/jdk18u/tags

**Comment by sxa** [comment]
> @Haroon-Khel Adoptium hasn't previously released an aarch64 Mac (M1) port for Java 11. Is this a new supported platform?

@jeffalder It's just been published :-)

**Comment by gounthar** [comment]
Could someone please explain to me why I can't seem to [find](https://adoptium.net/temurin/releases/?version=11) JDK11 valid links for Alpine Linux aarch64?
Or why I can't find Linux aarch64 nor Alpine Linux versions in the [archive](https://adoptium.net/temurin/archive?version=11)? The links are there but broken.
![Archive - Adoptium 5-16-2022 9-37-41 PM](https://user-images.githubusercontent.com/116569/168669226-358a8e99-e210-40bd-a1c7-a737f2802b16.png)

Thanks
.

**Comment by minhtran83** [comment]
Thanks a lot @sxa I really appreciate your great efforts

**Comment by sxa** [comment]
@gounthar The archive page was broken earlier this week - [the fix](https://github.com/adoptium/website-v2/pull/525) has just gone in so it should start working again shortly.

**Comment by gounthar** [comment]
That's good news @sxa , I will have another look tomorrow morning then!
Thank you 🙏

**Comment by gounthar** [comment]
> aarch64 isn't yet a supported platform.
How can I contribute so that it becomes a first class citizen? I don't mean I have the skills to do it, but if I ever can help.
Thanks @karianna .

**Comment by sxa** [comment]
> How can I contribute so that it becomes a first class citizen?

I'm actually hoping to have nightly development builds of Alpine/aarch64 coming out this week for most versions. I've had my team working on adding it over the last week :-) There is an initial test build of 17 that you can grab from https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-alpine-linux-aarch64-temurin/ but obviously it's untested, beta, may cause your machine to blow up etc.

**Comment by gounthar** [comment]
Thank you @sxa I will test that.

**Comment by sxa** [comment]
I'm going to close off this issue since all the updates for platforms/versions that we've already shipped are now complete.
