### ISSUE TITLE
[SSDF] [PS1.1] - Document Project Repositories & Access

### ISSUE THREAD

**Issue by steelhead31** [adoptium/adoptium#143]
Produce a document, detailing each of the repositories in the Adoptium Github organisation.

Tasks:
a) Identify and document each repository and Identify relevant functional area.
b) Identify any unused/defunct repositories.
c) Identify Github access control mechanisms, for each repository, and currently granted permissions/roles, etc.

**Comment by steelhead31** [comment]
Initial repository view diagram in Miro.. https://miro.com/app/board/uXjVO3WM154=/
Meeting scheduled for 10/05 for discussion.
Need to identify security model and procedures/documentation in place for access, removal and elevation of permissions.

**Comment by smlambert** [comment]
Public document for broader sharing is [here](https://docs.google.com/document/d/1NtG03VDr20DN8KX-wbdGr-lplMaXaSHfZQUMlDm7sCk/edit?usp=sharing)
