### ISSUE TITLE
[Marketplace]: Add Huawei BiSheng (JDK 8) to the marketplace

### ISSUE THREAD

**Issue by segment-fault** [adoptium/adoptium#149]
### Adoptium Working Group Member

- [X] Eligible Adoptium Working Group Member

### Adoptium Marketplace Publisher Agreement

- [X] Adoptium Marketplace Publisher Agreement Executed

### Publisher Logo

https://gitee.com/openeuler/BiSheng-Adoptium/blob/master/logo/logo.png

### Link to Product Listing Information

https://gitee.com/openeuler/BiSheng-Adoptium/blob/master/json/index.json

### Publisher Public Key

```
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEApy9nP1JyqG85I4zaokgy
v2wiWP2PplYaq3EylRSLHZVgh905kp6dpdMicc9GH0UlhI6z6tIMJmG5m2F2KZAt
O3EgDngFIlLQgNett435g+8HV17euGk3m8zIlWVP/7EepdVVCjXk7K6uWc8/v5tv
IV/Uf7kWrV6oAfenD28VlDcQ7v3m83RnFFVHqKQtqDcrwMP1NNxEZO6hhvjdE6jX
y2IdsRqH9G75+dcCZTooad5F1kza9IJo3H1RoWcEa+sF4xZjpi3PPrnB9L21P1Ee
EDVxxFdHGxWoipTVRLE5L6bLs6uwwRouME0ev4egNO31TUgLwq0D0L7trAtrxOKy
y1srvJnBgrfWHKuiGHOIc1BaRHvYLJW15ZjX8LZYY4kUMRcgPDc3kMMb46qghCsv
dn2HrIoZFYinxYBOq7Kle4vj7nIYbRtk104sxFRSHlCUDLd4I8j2eBI1JZQAA8EA
RPpkHe9kdvUvMwOxHkSBnXEhGRZOR791TUsYmqMXnFYkS86O+KQPjkbWx+JNlQeZ
paOSaVZVOLfEMVqEKAhT6+XypM6RXRFMaFUPJODpAerOBqe4DdIIhZWX3gKZAGtq
LS8DqfZfnsaifh51cEIEAaiUNZvMPKWudZ9nmxu1z56teIkfejp/AT6nYp/g1Wy8
p33LN4zz9+0wSTZxEc2ttrECAwEAAQ==
-----END PUBLIC KEY-----
```

### Post Download Page

https://mirror.iscas.ac.cn/kunpeng/archive/compiler/bisheng_jdk/

**Comment by tellison** [comment]
Thank you for the request.
Huawei builds are successfully appearing in the live marketplace now.
