### ISSUE TITLE
[Marketplace]: Add IBM Semeru Runtime Certified Edition

### ISSUE THREAD

**Issue by AdamBrousseau** [adoptium/adoptium#150]
### Adoptium Working Group Member

- [X] Eligible Adoptium Working Group Member

### Adoptium Marketplace Publisher Agreement

- [X] Adoptium Marketplace Publisher Agreement Executed

### Publisher Logo

IBM Logo

### Link to Product Listing Information

https://github.com/ibmruntimes/Semeru-Runtimes/blob/master/adoptium/marketplace/json/index.json

### Publisher Public Key

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: EKM

mQENBGAh0IABCACrOAxFfNYW+iJh+kaEgGdxpKjHc2OK+/MkvpQ/XsHr0IQ2KnhmkyQgRfTMa+ER
ZtZAcO2NkOGJf3/Edi1A/l96bStCdTlvLim7jJ3Q9cBQT1o1Dopq7wApIigjHtS8AjolhDnKPjbL
XgeWCnvBvBQxMevAuTwc/yj4/xX6I50lbuMlIqYCaMRITHMHqEbjpF8j1iH+QfAUqmu2VUaq+n1I
hN+iFMHCnr5hW4AivJrjar0Ex6d1vJbkSJysU9BwaeRAXuLDeXgxcrWUpF+TUQzIlbd89IvsCQkw
NBCxPVeoQ2YG/dyId++HV1MoOHUZTOPeV8arpvBQavuTkECJxEoZABEBAAG0CldpbmRvd3NTSEGJ
ATkEEwEIACMFAmAh0IACGy8HCwkIBwMCAQYVCAIJCgsEFgIDAQIeAQIXgAAKCRDTjm4am86WKV+4
CACUOTGfGmWjaPkMZX5K+2cDo475Fx+gOIrRd2hVpoq5TM+1jqAjSHjg1tbRlGd28wn2wZiFoA3G
BoUpnZyuFEzWuQH2yhvG3eLQJstnxnpQyc4fjKJBsI5nsZSZUd9gW/JPxLUyb6FICJEVswWk/ivO
kSpVRjaSV73w7f58yZJiiHW1+th/cg2WSq+YeRse+01pvs5VcsVr+NYw4LZqSFZlf/Smvfd/Xc8b
TVOegQCtB9e85f4q+L3vgAljJZL/RpTosEEoPLX/C3Q7cJ3+XaT5j6t2x+nqC+wI4trM2NNX4U6m
RI28hAPc09eC15kPilERuH2FP7cUJitC2ZyRRF2Q
=7Lyd
-----END PGP PUBLIC KEY BLOCK-----

### Post Download Page

https://developer.ibm.com/languages/java/semeru-runtimes/

**Comment by tellison** [comment]
Thank you for the request.
Semeru Certified Edition builds are successfully appearing in the live marketplace now.
