### ISSUE TITLE
[SSDF issue] PS1.1 - Code Security - Enable Github 2 Factor Authentication for Adoptium organisation

### ISSUE THREAD

**Issue by steelhead31** [adoptium/adoptium#151]
Whilst reviewing the security in place for the Github repositories, it has been noted that the Adoptium organisation within Github, does not have 2FA mandated at organisation level. Since Github will be mandating this across everything by the end of 2023, it would be beneficial to code security to enable this.

**Comment by tellison** [comment]
Ref: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1501

**Comment by tellison** [comment]
2FA is now mandated for all.
