### ISSUE TITLE
July 2022  Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/adoptium#153]
Please follow live updates in the [release](https://adoptium.slack.com/archives/CLCFNV2JG) channel in the Adoptium Slack workspace.

Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).

✔️ results in these Tables means the activity has successfully completed.

⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.

⛔ means there is no build planned for that version/platform combination.

⏸️ means activity not yet started.

### JDK8u342

Tag available & pipelines launched on July 22nd as at July 27, 5/11 tarballs published. 

| Platform | [jdk8 AQA](https://github.com/adoptium/aqa-tests/issues/3880) | jdk8 TCK | jdk8 installers | jdk8 containers | jdk8 published | Notes |
| -----  | ----- | ----- | ----- | ----- | ----- | ----- |
| **x64 Linux** |✔️  | ✔️ | ⏸️ | ✔️ | ✔️ |  |
| **x64 Windows** | ✔️ | ✔️ |  ✔️| ✔️ |✔️  |  |
| **x64 Mac** | ✔️ | ⏳ | ⏸️ | ⛔ | ⏸️ | Defer to 8u345 |
| aarch64 Linux | ✔️  | ✔️ | ⏸️ | ✔️ | ✔️ |  |
| ppcle64 Linux | ✔️ | ✔️ | ⏸️ | ✔️ | ✔️ |  |
| ppc64 AIX | ✔️ | ✔️ | ⛔ | ⛔ | ✔️ |  |
| x32 Windows | ✔️ | ✔️ | ⏸️ | ⛔ | ✔️ |  |
| arm32 Linux | ✔️ | ✔️ | ⏸️ | ✔️ | ✔️ | JFR testcase issue in AQA but will not block release |
| sparcv9 solaris | ⏳ | ⏳ | ⛔  | ⛔ |⏸️  | Defer to 8u345 |
| x86 solaris |  ✔️   | ✔️   | ⛔  | ⛔ | ⏸️ |  Issue ~~running system tests~~ resolved, packaging issue needs investigation, defer to 8u345 |
| x64 alpine-Linux |  ✔️ | ✔️  | ⏸️  | ✔️ |✔️  | This will be a headless build |

### JDK8u345

Tag available & pipelines launched on August 2nd (11/11 published, ending with sparcv9 solaris on Aug 19)

| Platform | [jdk8 AQA](https://github.com/adoptium/aqa-tests/issues/3904) | jdk8 TCK | jdk8 installers | jdk8 containers | jdk8 published | Notes |
| -----  | ----- | ----- | ----- | ----- | ----- | ----- |
| **x64 Linux** | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| **x64 Windows** | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| **x64 Mac** | ✔️ | ✔️ | ✔️ | ⛔ | ✔️ |  |
| aarch64 Linux | ✔️ | ✔️ | ✔️ | ✔️ |✔️  |  |
| ppcle64 Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| ppc64 AIX |✔️ | ✔️ | ⛔ | ⛔ | ✔️ |  |
| x32 Windows | ✔️ | ✔️ | ✔️ | ⛔ | ✔️ |  |
| arm32 Linux | ✔️ | ✔️ | ✔️ |✔️ | ✔️ |  |
| sparcv9 solaris | ✔️ | ✔️ | ⛔  | ⛔ |✔️  |  |
| x86 solaris | ✔️   | ✔️   | ⛔  | ⛔ | ✔️ |  |
| x64 alpine-Linux |  ✔️ | ✔️  | ✔️  | ✔️ |✔️  | This will be a headless build |

### JDK11.0.16

Tag available & pipeline launched on July 19th as at July 29, 10/11 tarballs published. 
(Jul 19, 2022, 10:23:33 PM / 4:23 PM EST)

| Platform |[ jdk11 AQA](https://github.com/adoptium/aqa-tests/issues/3868) | jdk11 TCK | jdk11 installers | jdk11 containers | jdk11 published | Notes |
| ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| **x64 Linux** | ✔️ | ✔️ |✔️|✔️| ✔️ |  |
| **x64 Windows** | ✔️ |✔️ |  ✔️| ✔️ |✔️  |  |
| **x64 Mac** | ✔️ | ✔️ | ⏸️  | ⛔ |✔️  |  |
| aarch64 Linux | ✔️ | ✔️ |✔️ | ✔️| ✔️ |  |
| ppcle64 Linux |  ✔️ | ✔️ | ✔️ | ✔️ |✔️  |  |
| s390x Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| ppc64 AIX | ✔️ | ✔️ | ⛔ |⛔ |✔️  |  |
| x32 Windows | ✔️ |✔️ |  ✔️ | ⛔ | ✔️ |  |
| arm32 Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| x64 alpine-Linux | ✔️ | ✔️ | ⏸️ | ✔️ | ✔️ | This will be a headless build |
| aarch64 Mac | ✔️ | ✔️ | ⏸️ | ⛔ | ✔️ | Single TCK machine, delayed/bottlenecked due machine issue. |

### JDK11.0.16.1+1 
Pipeline launched Aug18, 11/11 published as at Aug 23
| Platform | [jdk11 AQA](https://github.com/adoptium/aqa-tests/issues/3924) | jdk11 TCK | jdk11 installers | jdk11 images | jdk11 published | Notes |
| ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| **x64 Linux** | ✔️ | ✔️ |✔️ |✔️ | ✔️ |  |
| **x64 Windows** | ✔️ | ✔️ |✔️ | ✔️ | ✔️ |  |
| **x64 Mac** | ✔️ | ✔️ | ✔️ | ⛔ | ✔️ |  |
| aarch64 Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| ppcle64 Linux |  ✔️ | ✔️| ✔️ | ✔️ |✔️  |  |
| s390x Linux | ✔️ | ✔️ | ✔️ | ✔️ |✔️  |  |
| ppc64 AIX | ✔️ | ✔️ | ⛔ |⛔ | ✔️ |  |
| x32 Windows | ✔️ | ✔️ |✔️ | ⛔ | ✔️ |  |
| arm32 Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| x64 alpine-Linux | ✔️ | ✔️ | ⏸️ | ✔️ | ✔️ | This will be a headless build |
| aarch64 Mac | ✔️ | ✔️ | ✔️ | ⛔ | ✔️ |  |

### JDK17.0.4

Tag available & pipeline launched on July 19th at 2143UTC as at July 27, 8/11 tarballs published.
(Jul 19, 2022, 9:43:00 PM / 3:43 PM EST)

| Platforms | [jdk17 AQA ](https://github.com/adoptium/aqa-tests/issues/3869)| jdk17 TCK | jdk17 installers | jdk17 containers | jdk17 published | Notes |
| ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| **x64 Linux**| ✔️ | ✔️ |✔️ | ✔️ | ✔️ |  |
| **x64 Windows** | ✔️ |  ✔️ |  ✔️  | ✔️  | ✔️ |  |
| **x64 Mac** | ✔️ | ✔️ | ⏸️  | ⛔ | ✔️ |  |
| aarch64 Linux | ✔️ | ✔️ | ✔️ | ✔️| ✔️ |  |
| ppcle64 Linux |  ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| s390x Linux | ✔️ | ✔️ |  ✔️| ✔️ | ✔️ |  |
| ppc64 AIX| ✔️ | ✔️| ⛔ |⛔  | -- | Unlikely to release / TCK column paused |
| x32 Windows | ✔️ | ✔️ | ⏸️ | ⛔ | ✔️ |   |
| arm32 Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| x64 alpine-Linux | ✔️ | ✔️ | ⏸️ | ✔️ | ✔️ | This will be a headless build |
| aarch64 Mac | ✔️ | ✔️ | ⏸️ | ⛔ | ✔️ | Single TCK machine, delayed/bottlenecked due machine issue. |

### JDK17.0.4.1+1 
Pipeline launched Aug 18, 11/11 published as of Aug 23
| Platforms | jdk17 AQA | jdk17 TCK | jdk17 installers | jdk17 images | jdk17 published | Notes |
| ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| **x64 Linux**| ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| **x64 Windows** | ✔️ | ✔️| ✔️  | ✔️  | ✔️ |  |
| **x64 Mac** | ✔️ | ⏳ | ✔️  | ⛔ | ✔️ |  |
| aarch64 Linux | ✔️ | ✅ |✔️ | ✔️ | ✔️ |  |
| ppcle64 Linux | ✔️ | ✔️ |✔️ | ✔️ | ✔️ |  |
| s390x Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| ppc64 AIX| ✔️ | ⏸️ | ⛔ |⛔  | -- |  |
| x32 Windows | ✔️ | ✔️ | ✔️ | ⛔ | ✔️ |  |
| arm32 Linux | ✔️ | ✔️ | ✔️ | ✔️ |✔️  |  |
| x64 alpine-Linux | ✔️ | ✔️ | ⏸️ | ✔️ | ✔️ | This will be a headless build |
| aarch64 Mac | ✔️ | ✔️ |✔️ | ⛔ |✔️  |  |

### JDK18.0.2

Tag available & pipeline launched on July 20 as at July 25, 11/11 tarballs published (x64 Mac Aug 14 final). 
(Jul 20, 2022, 3:30:52 PM / 9:30 AM EST)

| Platform |[ jdk18 AQA ](https://github.com/adoptium/aqa-tests/issues/3872)| jdk18 TCK | jdk18 installers | jdk18 containers | jdk18 published | Notes |
| ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| **x64 Linux**| ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| **x64 Windows** | ✔️ | ✔️ |  ✔️  | ✔️  | ✔️ |  |
| **x64 Mac** |  ✔️| ✔️ | ✔️  | ⛔ | ✔️ |  |
| aarch64 Linux | ✔️ | ✔️ | ✔️ |✔️ |  ✔️ |  |
| ppcle64 Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| s390x Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| ppc64 AIX| ✔️ | ⏸️ | ⛔ |⛔  | -- | Unlikely to release / TCK column paused |
| x32 Windows | ✔️ | ✔️ | ⏸️ | ⛔ | ✔️  |  |
| arm32 Linux | ✔️ | ✔️ | ✔️  | ✔️ | ✔️ |  |
| x64 alpine-Linux | ✔️ | ✔️ | ⏸️ | ✔️ | ✔️ | This will be a headless build |
| aarch64 Mac | ✔️ | ✔️ | ⏸️ | ⛔ | ✔️ | Single TCK machine, delayed/bottlenecked due machine issue. |

### JDK18.0.2.1

Tag available on August 22nd, pipeline launched on August 25, 6/10 published as at Aug 26.

| Platform |[ jdk18 AQA ](https://github.com/adoptium/aqa-tests/issues/3940)| jdk18 TCK | jdk18 installers | jdk18 containers | jdk18 published | Notes |
| ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| **x64 Linux**| ✔️ | ✔️ | ✔️ | ✔️ |✔️ |  |
| **x64 Windows** | ✔️ | ✔️ | ✔️  | ✔️  | ✔️ |  |
| **x64 Mac** | ✔️ | ✔️ | ✔️  | ⛔ | ✔️ |  |
| aarch64 Linux | ✔️ | ✔️ | ✔️ | ✔️ |  ✔️ |  |
| ppcle64 Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| s390x Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| ppc64 AIX| ✔️ | ⏸️ | ⛔ |⛔  | -- | Unlikely to release / TCK column paused |
| x32 Windows | ✔️ | ✔️ | ✔️ | ⛔ | ✔️ |  |
| arm32 Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |
| x64 alpine-Linux | ✔️ | ✔️ | ⏸️ | ✔️ | ✔️ | This will be a headless build |
| aarch64 Mac | ✔️ | ✔️ | ⏸️ | ⛔ | ✔️ | Single TCK machine, delayed/bottlenecked due machine issue. |

**Comment by koldat** [comment]
JDK8u342 table is missing Alpine Linux. Is it intentional? Last release included this build.

**Comment by sophia-guo** [comment]
Thanks @koldat for asking. Added.

**Comment by tellison** [comment]
See also https://github.com/adoptium/adoptium/issues/157

**Comment by jgrueneis** [comment]
This overview is great <3 - thank you very much for it

Is something similar available for the docker images?

**Comment by smlambert** [comment]
re: https://github.com/adoptium/adoptium/issues/153#issuecomment-1195625666 - the "containers" column in the tables above are meant to reflect whether the docker images have been published or not...  (highlighting a note in the [release guide](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#steps-for-every-version) / step 15 that we currently publish containers only after all tarballs for Linux architectures are published).

**Comment by kwin** [comment]
Any ETA for Aarch64 Mac binaries or a public issue where the build machine problems are tracked?

**Comment by c0bw3b** [comment]
I'm not familiar with your release process but we're also missing the RPM and DEB Linux packages for 8u342.

On the other hand 11.0.16 and 17.0.4 packages already appeared on `https://packages.adoptium.net`

**Comment by sxa** [comment]
> I'm not familiar with your release process but we're also missing the RPM and DEB Linux packages for 8u342.

Yep I'm working on that (it requires all linux architectures to be complete and we had the last one finished yesterday, although there is now going to be an 8u345 that will supercede it anyway (We're building that now)

**Comment by sxa** [comment]
> Is something similar available for the docker images?

The "containers" column in the table are the docker images.

**Comment by sxa** [comment]
> Any ETA for Aarch64 Mac binaries or a public issue where the build machine problems are tracked?

We do not have support for that platform in JDK8. The others are being worked on but limited by the number of people currently working on completing the testing. We are working on it as hard as we practically can with what we have available. Sadly we are also restricted by legal agreements on how much volunteer effort we can have on the testing.

**Comment by breun** [comment]
> The "containers" column in the table are the docker images.

What Adoptium offers are technically images, not containers. Containers are the instances that you can run based on an image. It might be good to rename the containers column to images (maybe 'container images').

**Comment by c0bw3b** [comment]
So what's the ETA of 8u345 x64 RPM packages?

**Comment by sxa** [comment]
> > The "containers" column in the table are the docker images.
> 
> What Adoptium offers are technically images, not containers. Containers are the instances that you can run based on an image. It might be good to rename the containers column to images (maybe 'container images').

`Container images` would be nicer although it would likely mean the text is split over three lines in the column heading.  Thinking about it I'd also be ok with "DockerHub" since that's a bit more explicit about saying where we push them to. The template is at https://github.com/adoptium/adoptium/blob/main/.github/ISSUE_TEMPLATE/release-status.md if you wanted to create a PR against it. I've added a note to our retrospective on this point regardless.
