### ISSUE TITLE
Race condition in release cycle when using automated download scripts

### ISSUE THREAD

**Issue by DaveJarvis** [adoptium/adoptium#156]
We'd like to ensure that our system is always built using the latest version of JDK 17. However, doing so introduces a race condition due to the relationship between GitHub's "latest" URL and when archives are uploaded. In effect:

1. Fetch https://github.com/adoptium/temurin17-binaries/releases/latest
1. Extract Java version number from redirected URL (e.g., jdk-17.0.4+8).
1. Fetch https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4+8/OpenJDK17U-jre_arm_linux_hotspot_jdk-17.0.4_8.tar.gz

This fails because there are several hours where a new release has been tagged but not all binaries are present.

**Example script**

The following shell script attempts to download the latest ARM version of JRE 17:

``` bash
readonly URL="https://github.com/adoptium/temurin17-binaries/releases"
readonly JRE_VERSION=$(curl -Ls -w %{url_effective} -o /dev/null \
  "${URL}/latest/" |\
  awk -F/ '{ print $8 }')
readonly JRE_URL="${URL}/download/${JRE_VERSION}/OpenJDK17U-jre_arm_linux_hotspot_${JRE_VERSION//+/_}.tar.gz"
curl -C - ${JRE_URL}
```

**Expected results**
The script completes and the JRE is downloaded.

**Actual results**
The script fails because even though a new release has been published, not all the artifacts have been uploaded.

**Work around**
Maintain the script using a hard-coded version number.

**Request**
Would it be possible to generate all artifacts for the latest release ahead of time, and publish them simultaneously when a new release is tagged?

**Comment by tellison** [comment]
Hello @DaveJarvis, thanks for sharing your script and goals.

I advise not using the GitHub API directly - that is 'just' where we store the releases, and as you have discovered we work to get the Java versions and platforms out in priority order and as soon as they are available. We don't wait for the slowest platform to complete before publishing anything.

I recommend you utilize [the Adoptium API](https://api.adoptium.net/q/swagger-ui/) to download the latest binary for the platform you are interested in using. The Adoptium API will avoid you having to parse URLs to get the release information too.

For example:

You can get details of the latest release for arm/linux using
```https://api.adoptium.net/v3/assets/latest/17/hotspot?architecture=arm&image_type=jdk&os=linux```

and directly download the latest arm/linux at any time using
```https://api.adoptium.net/v3/binary/latest/17/ga/linux/arm/jdk/hotspot/normal/eclipse```

That will send you the latest, whenever it is released. HTH

**Comment by DaveJarvis** [comment]
This looks great, thank you.

https://api.adoptium.net/v3/binary/latest/17/ga/linux/arm/jre/hotspot/normal/eclipse
