### ISSUE TITLE
Scorecard/Timeline for July 2022 Release

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#157]
Grey indicates "Done"
Blue with red outline indicates "Not done, Active"
Red indicates "Not done, not active"

## Primary platforms (all versions)

12 of 12 primaries published.  (29 days to deliver jdk18 mac)

```mermaid
gantt
    title Timelines for Primary Platforms for July 2022 Release
    dateFormat  YYYY-MM-DD

    section JDK17 x64 Linux
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 1d
    Publish   :done, milestone, 2022-07-21, 0d

    section JDK17 x64 Windows
    Tagged build           :done, a2, 2022-07-19, 1d
    AQAvit     :done, after a2  , 6h
    TCK         :done, after a2, 1d
    Publish   :done, milestone, 2022-07-21, 0d

    section JDK17 x64 Mac
    Tagged build           :done, a3, 2022-07-19, 1d
    AQAvit     :done, after a3  , 1d
    TCK         :done, after a3, 7d
    Publish        :done, milestone, 2022-07-27, 0d

    section JDK11 x64 Linux
    Tagged build           :done, a4, 2022-07-19, 1d
    AQAvit     :done, after a4  , 6h
    TCK         :done, after a4, 1d
    Publish   :done, milestone, 2022-07-21, 0d

    section JDK11 x64 Windows
    Tagged build           :done, a5, 2022-07-19, 1d
    AQAvit     :done, after a5  , 6h
    TCK         :done, after a5, 2d
    Publish   :done, milestone, 2022-07-22, 0d

    section JDK11 x64 Mac
    Build           :done, a6, 2022-07-19, 1d
    AQAvit     :done, after a6 , 6h
    TCK         :done, after a6, 3d
    Publish   :done, milestone, 2022-07-23, 0d

    section JDK8 x64 Linux
    Build      :done, a10, 2022-07-22, 1d
    AQAvit      :done, after a10, 6h
    TCK      :done, a10b, after a10,  10h
    Publish   :done, milestone, after a10b, 0d

    section JDK8 x64 Windows
    Build      :done, a11, 2022-07-22, 1d
    AQAvit      :done, after a11, 6h
    TCK      :done, after a11, 3d
    Publish   :done, milestone, 2022-07-26, 0d

    section JDK8 x64 Mac
    Build      :done, a12, 2022-07-22, 1d
    AQAvit      :done, after a12, 1d
    TCK      :done, after a12, 16d
    Publish        :done, milestone, 2022-08-08, 0d

    section JDK18 x64 Linux
    Build      :done, a13, 2022-07-20, 1d
    AQAvit     :done, after a13, 6h
    TCK     :done, after a13, 1d
    Publish   :done, milestone, 2022-07-22, 0d

    section JDK18 x64 Windows
    Build      :done, a14, 2022-07-20, 1d
    AQAvit     :done, after a14, 6h
    TCK     :done, after a14, 4d
    Publish   :done, milestone, 2022-07-25, 0d

    section JDK18 x64 Mac
    Build      :done, a15, 2022-07-20, 1d
    AQAvit     :done, after a15, 1d
    TCK     :done, after a15, 29d
    Publish        :done, milestone, 2022-08-19, 0d
```

Need to check with 'owners' of "not done" platforms on ETA, as the target goal is to publish these within 2 days of the tagged build being completed.

---

### JDK17 Secondaries

7 of 7 published (8 secondary platforms in total, but AIX not expected to be published).  Target to complete the majority within _7 days_ of tagged build.

```mermaid
gantt
    title Timelines for Secondary Platforms for JDK17 for July 2022 Release
    dateFormat  YYYY-MM-DD

    section JDK17 aarch64 Linux
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 1d
    Publish   :done, milestone, 2022-07-21, 0d

    section JDK17 ppc64le Linux
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 2d
    Publish   :done, milestone, 2022-07-22, 0d

    section JDK17 alpine-linux
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 2d
    Publish   :done, milestone, 2022-07-22, 0d

    section JDK17 x32 Windows
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 5d
    Publish   :done, milestone, 2022-07-25, 0d

    section JDK17 s390x Linux
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 7d
    Publish   :done, milestone, 2022-07-27, 0d

    section JDK17 arm32 Linux
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 7d
    Publish   :done, milestone, 2022-07-27, 0d

    section JDK17 aarch64 Mac
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 13d
    Publish   :done, milestone, 2022-08-02, 0d
```
---

### JDK11 Secondaries

8 of 8 published.  Target to complete the majority within _7 days_ of tagged build.

```mermaid
gantt
    title Timelines for Secondary Platforms for JDK11 for July 2022 Release
    dateFormat  YYYY-MM-DD

    section JDK11 aarch64 Linux
    Tagged build   :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 1d
    Publish   :done, milestone, 2022-07-21, 0d

    section JDK11 ppc64le Linux
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 3d
    Publish   :done, milestone, 2022-07-23, 0d

    section JDK11 alpine-linux
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 3d
    Publish   :done, milestone, 2022-07-23, 0d

    section JDK11 x32 Windows
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 6d
    Publish   :done, milestone, 2022-07-26, 0d

    section JDK11 arm32 Linux
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 6d
    Publish   :done, milestone, 2022-07-26, 0d

    section JDK11 s390x Linux
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 7d
    Publish   :done, milestone, 2022-07-27, 0d

    section JDK11 aarch64 Mac
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 13d
    Publish   :done, milestone, 2022-08-02, 0d

    section JDK11 ppc64 AIX
    Tagged build           :done, a1, 2022-07-19, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 12d
    Publish   :done, milestone, 2022-08-01, 0d
```

---

### JDK8 Secondaries

8 of 8 published.  Target to complete the majority within _7 days_ of tagged build.

```mermaid
gantt
    title Timelines for Secondary Platforms for JDK8 for July 2022 Release
    dateFormat  YYYY-MM-DD

    section JDK8 aarch64 Linux
    Tagged build   :done, a1, 2022-07-22, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 4d
    Publish   :done, milestone, 2022-07-27, 0d

    section JDK8 ppc64le Linux
    Tagged build           :done, a1, 2022-07-22, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 3d
    Publish   :done, milestone, 2022-07-26, 0d

    section JDK8 alpine-linux
    Tagged build           :done, a1, 2022-07-22, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 3d
    Publish   :done, milestone, 2022-07-26, 0d

    section JDK8 x32 Windows
    Tagged build           :done, a1, 2022-07-22, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 4d
    Publish   :done, milestone, 2022-07-27, 0d

    section JDK8 arm32 Linux
    Tagged build           :done, a1, 2022-07-22, 1d
    AQAvit     :done, after a1, 3d
    TCK         :done, after a1, 18d
    Publish   :done, milestone, 2022-08-10, 0d

    section JDK8 sparcv9 Solaris
    Tagged build           :done, a1, 2022-07-22, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 27d
    Publish   :done, milestone, 2022-08-19, 0d

    section JDK8 x64 Solaris
    Tagged build           :done, a1, 2022-07-22, 1d
    AQAvit     :done, after a1, 5d
    TCK         :done, after a1, 5d
    Packaging issue :done, after a1, 17d
    Publish   :done, milestone, 2022-08-09, 0d

    section JDK8 ppc64 AIX
    Tagged build   :done, a1, 2022-07-22, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 9d
    Publish   :done, milestone, 2022-08-01, 0d
```

---

### JDK18 Secondaries

7 of 7 published (8 secondary platforms, but AIX will not get published this release).  Target to complete the majority within _10 days_ of tagged build.

```mermaid
gantt
    title Timelines for Secondary Platforms for JDK18 for July 2022 Release
    dateFormat  YYYY-MM-DD

    section JDK18 aarch64 Linux
    Tagged build   :done, a1, 2022-07-20, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 4d
    Publish   :done, milestone, 2022-07-25, 0d

    section JDK18 ppc64le Linux
    Tagged build           :done, a1, 2022-07-20, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 2d
    Publish   :done, milestone, 2022-07-23, 0d

    section JDK18 alpine-linux
    Tagged build           :done, a1, 2022-07-20, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 3d
    Publish   :done, milestone, 2022-07-24, 0d

    section JDK18 x32 Windows
    Tagged build           :done, a1, 2022-07-20, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 7d
    Publish   :done, milestone, 2022-07-28, 0d

    section JDK18 arm32 Linux
    Tagged build           :done, a1, 2022-07-20, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 7d
    Publish   :done, milestone, 2022-07-28, 0d

    section JDK18 s390x Linux
    Tagged build           :done, a1, 2022-07-20, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 11d
    Publish   :done, milestone, 2022-08-01, 0d

    section JDK18 aarch64 Mac
    Tagged build           :done, a1, 2022-07-20, 1d
    AQAvit     :done, after a1, 6h
    TCK         :done, after a1, 12d
    Publish   :done, milestone, 2022-08-02, 0d
```

**Comment by jgrassel** [comment]
When will JDK 19 builds start showing up for download?

**Comment by karianna** [comment]
> When will JDK 19 builds start showing up for download?

Late Sept is the release date

**Comment by jiekang** [comment]
@jgrassel more exactly from https://www.java.com/releases/ it will be after 2022-09-20

**Comment by smlambert** [comment]
In summary:

Primary Platforms delivered within the targeted delivery goals:
| Platform | Version | Days to Release |
| --- | --- | --- |
|  | 17 |  |
|  | 17 |  |
|  | 17 |  |
|  | 17 |  |
|  | 17 |  |
|  | 17 |  |

Primary Platforms NOT delivered within targeted delivery goals (and how badly were goals missed):

**Comment by smlambert** [comment]
Secondary Platforms Scorecard, compare with the 7 days targeted delivery goals, in summary:

| Platform | Version | Days to Release | Days over Target | Achieved Target ✅ or ❌ |
| --- | --- | --- | --- |  --- |
| aarch64 Linux | 17 | 1 | -6 | ✅ |
| ppc64le Linux  | 17 | 2 | -5 | ✅ |
| alpine-linux  | 17 | 2 | -5 | ✅ |
| x32 Windows  | 17 | 5 | -2 | ✅ |
|  s390x Linux | 17 | 7 | -1 | ✅ |
|  arm32 Linux | 17 | 7 | 0 | ✅ |

**Comment by smlambert** [comment]
This assessment does not take into account the respins of jdk8u345, jdk11, jdk17 at this time (may add comments for posterity if required).

There are 44 platforms in total that the project would consider to release, with 2 of those (ppc64 AIX JDK17/JDK18) not produced this release as expected.  Of the 42 platforms released (not counting respins), 27 were released within the stated goals (64.3%), 15 missed the target (35.7%).  

Of the 15 that missed the target, 7 of them badly missed the target (by more than 5 days, 1 business week), 16.6%.  

Closing this issue as completed.  It can be used in the retrospectives / postmortem to make decisions and take action to improve in the future.  For example, since the time of compiling this, a 2nd aarch64 Mac machine has been added to the temurin-compliance project, which should help the delivery times for that platform.

**Comment by smlambert** [comment]
### Additional notes for respins 

Noting that Aug20/21 were weekend days & we include them as workable days, targets below would look better if we counted 'business' days only.

JDK8u345 pipeline launched Aug 2, all platforms published by Aug 19, but still need to gather stats

| Platform | Version | Days to Release | Days over Target | Achieved Target ✅ or ❌ |
| --- | --- | --- | --- |  --- |
| **x64 Linux** | 8 / primary |  |  |  |
| **x64 Windows** | 8 / primary | |  |  |
| **x64 Mac** | 8 / primary |  |  |  |
| aarch64 Linux | 8 |  |  |  |
| ppc64le Linux  | 8 |  |  |  |
| alpine-linux  | 8 |  |  |  |
| x32 Windows  | 8 |  |  |  |
|  arm32 Linux | 8 |  |  |  |
|  ppc64 AIX | 8 |  |  |  |
|  x86 Solaris | 8 |  |  |  |
|  sparcv9 Solaris | 8 | |  |  |

---

JDK11.0.16.1+1 pipeline launched Aug 18, all platforms published by Aug 23 (**90.9%** within targets)

| Platform | Version | Days to Release | Days over Target | Achieved Target ✅ or ❌ |
| --- | --- | --- | --- |  --- |
| **x64 Linux** | 11 / primary | 1 | -1 | ✅ |
| **x64 Windows** | 11 / primary | 1 | -1 | ✅ |
| **x64 Mac** | 11 / primary | 5 | 3 | ❌ |
| aarch64 Linux | 11 | 1 | -6 | ✅ |
| ppc64le Linux  | 11 | 5 | -2 | ✅ |
| alpine-linux  | 11 | 1 | -7 | ✅ |
| x32 Windows  | 11 | 1 | -6 | ✅ |
|  s390x Linux | 11 | 4 | -3 | ✅ |
|  arm32 Linux | 11 | 1 | -6 | ✅ |
|  aarch64 Mac | 11 | 1 | -6 | ✅ |
|  ppc64 AIX | 11 | 5 | -2 | ✅ |

---

JDK17.0.4.1+1 pipeline launched Aug 18, all platforms published by Aug 23 (**72.7%** within targets)

| Platform | Version | Days to Release | Days over Target | Achieved Target ✅ or ❌ |
| --- | --- | --- | --- |  --- |
| **x64 Linux** | 17 / primary | 5 | 3 | ❌ |
| **x64 Windows** | 17 / primary | 5 | 3 | ❌ |
| **x64 Mac** | 17 / primary | 5 | 3 | ❌ |
| aarch64 Linux | 17 | 5 | -2 | ✅ |
| ppc64le Linux  | 17 | 2 | -5 | ✅ |
| alpine-linux  | 17 | 5 | -2 | ✅ |
| x32 Windows  | 17 | 5 | -2 | ✅ |
|  s390x Linux | 17 | 5 | -2 | ✅ |
|  arm32 Linux | 17 | 5 | -2 | ✅ |
|  aarch64 Mac | 17 | 5 | -2 | ✅ |

---

jdk-18.0.2.1+1 pipeline launched Aug 25, WIP

| Platform | Version | Days to Release | Days over Target | Achieved Target ✅ or ❌ |
| --- | --- | --- | --- |  --- |
| **x64 Linux** | 18 / primary | | | |
| **x64 Windows** | 18 / primary | 1 | -1 | ✅|
| **x64 Mac** | 18 / primary | 1 | -1 | ✅|
| aarch64 Linux | 18 | 1 | -6 | ✅|
| ppc64le Linux  | 18 |  | | |
| alpine-linux  | 18 |  | | |
| x32 Windows  | 18 | 1 | -6|✅ |
|  s390x Linux | 18 |1  |-6 |✅ |
|  arm32 Linux | 18 |  | | |
|  aarch64 Mac | 18 | 1 |-6 | ✅|

**Comment by smlambert** [comment]
| Release activity | % within target |
| --- | --- | 
| Initial July release | 64.3% |
| jdk8u345 respin | 63.6% |
|jdk11.0.16.1+1 respin | 90.9%|
|jdk17.0.4.1+1 respin | 72.7%|
|jdk-18.0.2.1+1 respin | 100%|

**Comment by smlambert** [comment]
From the initial July release activity, the _Sickest Seven_ (7 products that took more than 5 business days over the 2 or 7 day target to publish), plus the _two outliers_ from the respins:

| Platform | Version | Days over Target | Underlying Reasons / Notes | Actions to Improve | 
| -- | -- | -- | -- | -- |
| x64 Mac | jdk8 | 14 | Owners failed to treat as urgent, poor communication, slow connectivity | Clarify requirements with owners |
| x64 Mac | jdk18 | 27 | Owners failed to treat as urgent, poor communication, slow connectivity | Clarify requirements with owners |
| aarch64 Mac | jdk17 | 6 | Bottlenecked on having only 1 machine for TCK | 2nd machine now added to temurin-compliance project |
| aarch64 Mac | jdk11 | 6 | Bottlenecked on having only 1 machine for TCK | 2nd machine now added to temurin-compliance project |
| arm32 Linux | jdk8 | 11 | ? unclear, possibly slow to add an owner to it, also short-handed, team vacations | Close follow-up to ensure ownership early |
| x86 Solaris | jdk8 | 10 | Delayed on packaging issue | Issue now fixed, https://github.com/adoptium/temurin-build/issues/3061 |
| sparcv9 Solaris | jdk8 | 20 | Considered a best effort platform, team would/should prioritize this last | No specific action required, Reduction in effort on other platforms, and no respins would mean these lower priority platforms get released quicker |
|  |  |  |  |  |
|ppc64 AIX | jdk8u345 | 8 | comms fail, ready in 8 days, took 15 to publish, related [Slack thread](https://adoptium.slack.com/archives/CLCFNV2JG/p1660133850604949) | Better communication & follow-up by release team |
| sparcv9 Solaris | jdk8u345 | 10 | Considered a best effort platform, team would/should prioritize this last | No specific action required, Reduction in effort on other platforms, and no respins would mean these lower priority platforms get released quicker |

**Comment by smlambert** [comment]
Respins calculated in an automated way using Github and Adoptium API calls (as opposed to the manual tracking above which used the manual launch of the pipeline as the starting time rather than when the tag was available in our github mirror):

---

Release tag: jdk8u345-b01_adopt on Mon Aug  1 12:14:14 EDT 2022

|  Platform        |   OS   | Released |Target/Actual(days)   | On-time              |        RTAG |
| --- | --- | --- | --- | --- | --- |
  |      x64  |       linux  | 08-04-2022       |         2/3      |    No  |       jdk8u345-b01_adopt| 
|    aarch64  |       linux |  08-04-2022    |            7/3      |   Yes     |    jdk8u345-b01_adopt| 
|        x64 | alpine-linux |  08-04-2022     |           7/3     |    Yes     |    jdk8u345-b01_adopt| 
 |   ppc64le     |    linux  | 08-08-2022    |            7/6    |     Yes   |      jdk8u345-b01_adopt| 
|        x64     |      mac |  08-08-2022    |            2/6    |      No    |     jdk8u345-b01_adopt| 
|        x64    |   solaris  | 08-09-2022   |             7/8       |   No      |   jdk8u345-b01_adopt| 
|        arm     |    linux  | 08-10-2022 |               7/8       |   No|  jdk8u345-ga-aarch32-20220802_adopt| 
|        x64    |   windows |  08-04-2022   |             2/3    |      No      |   jdk8u345-b01_adopt| 
  |      x32      | windows  | 08-04-2022    |            7/3   |      Yes       |  jdk8u345-b01_adopt| 
 |     ppc64    |       aix |  08-19-2022   |            7/18    |      No   |      jdk8u345-b01_adopt| 
 |   sparcv9   |    solaris |  08-19-2022    |           7/18    |      No     |    jdk8u345-b01_adopt| 

On-Time 4(36%)  Late: 7(63%)

---

Release tag: jdk-11.0.16.1+1_adopt on Mon Aug 15 10:02:21 EDT 2022

|  Platform        |   OS   | Released |Target/Actual(days)   | On-time              |        RTAG |
| --- | --- | --- | --- | --- | --- |
 |       x64   |    windows|   08-19-2022    |            2/4      |    No   |   jdk-11.0.16.1+1_adopt| 
 |       x32  |     windows |  08-19-2022     |           7/4      |   Yes  |    jdk-11.0.16.1+1_adopt| 
|        arm     |    linux  | 08-19-2022   |             7/4    |     Yes  |    jdk-11.0.16.1+1_adopt| 
|        x64 | alpine-linux |  08-19-2022  |              7/4      |   Yes   |   jdk-11.0.16.1+1_adopt| 
|    aarch64     |    linux |  08-19-2022  |              7/4   |      Yes     | jdk-11.0.16.1+1_adopt| 
  |      x64     |    linux |  08-19-2022   |             2/4      |    No  |    jdk-11.0.16.1+1_adopt| 
|    aarch64     |      mac  | 08-19-2022         |       7/4    |     Yes   |   jdk-11.0.16.1+1_adopt| 
|      s390x    |     linux|   08-22-2022  |              7/7     |    Yes   |   jdk-11.0.16.1+1_adopt| 
|    ppc64le    |     linux  | 08-23-2022    |            7/8    |      No  |    jdk-11.0.16.1+1_adopt| 
 |       x64      |     mac  | 08-23-2022      |          2/8   |       No    |  jdk-11.0.16.1+1_adopt| 
 |     ppc64    |       aix  | 08-23-2022    |            7/8    |      No   |   jdk-11.0.16.1+1_adopt| 

On-Time 6(54%)  Late: 5(45%)

---

Release tag: jdk-17.0.4.1+1_adopt on Wed Aug 17 07:17:42 EDT 2022

|  Platform        |   OS   | Released |Target/Actual(days)   | On-time              |        RTAG |
| --- | --- | --- | --- | --- | --- |
  |    s390x    |     linux  | 08-23-2022  |              7/6       |  Yes   |    jdk-17.0.4.1+1_adopt| 
|    aarch64  |       linux  | 08-23-2022      |          7/6   |      Yes    |   jdk-17.0.4.1+1_adopt| 
 |       x64      |   linux  | 08-23-2022     |           2/6    |      No   |    jdk-17.0.4.1+1_adopt| 
 |   ppc64le    |     linux |  08-23-2022 |               7/6    |     Yes   |    jdk-17.0.4.1+1_adopt| 
  |      arm    |     linux  | 08-23-2022   |             7/6      |   Yes   |    jdk-17.0.4.1+1_adopt| 
  |      x64 | alpine-linux |  08-23-2022       |         7/6  |       Yes   |    jdk-17.0.4.1+1_adopt| 
 |   aarch64      |     mac |  08-23-2022    |            7/6      |   Yes    |   jdk-17.0.4.1+1_adopt | 
|    x64  |     windows |   08-23-2022 |               2/6 |         No    |   jdk-17.0.4.1+1_adopt| 
|        x32    |   windows |  08-23-2022    |            7/6        | Yes     |  jdk-17.0.4.1+1_adopt| 
|        x64    |       mac  | 08-23-2022        |        2/6        |  No    |   jdk-17.0.4.1+1_adopt| 

On-Time 7(70%)  Late: 3(30%)

---

**Comment by smlambert** [comment]
| Release activity | % within target (manual tracking) | % within target (automated tracking) | 
| --- | --- | --- |
| jdk8u345 respin | 63.6% | 36% |
|jdk11.0.16.1+1 respin | 90.9%| 54% |
|jdk17.0.4.1+1 respin | 72.7%| 70%|
|jdk-18.0.2.1+1 respin | 100%|70% |

Discrepancy lies with how the start time was measured, manual launch of pipeline versus when tag was actually available.
