### ISSUE TITLE
Update uses of Adoptium wordmark to use registered trademark symbol

### ISSUE THREAD

**Issue by tellison** [adoptium/adoptium#158]
The Adoptium wordmark in the United States is now fully registered. We can now proceed to use the :registered: (Unicode U+00AE) symbol when using the mark.

**Comment by tellison** [comment]
Waiting on Shanda Giacomoni to provide details of correct usage and words to appear on website

**Comment by tellison** [comment]
Logo locations requiring update include [website display](https://github.com/adoptium/website-v2/tree/main/static/images), and [EF artwork](https://www.eclipse.org/org/artwork/zip_files/adoptium-logo.zip), and [website download](https://github.com/adoptium/website-v2/tree/main/static/images/doc/logo-styleguide)

**Comment by meKokabi** [comment]
Hello, Please find attached the Adoptium logo with the registration mark.

[Adoptium- Revised.zip](https://github.com/adoptium/adoptium/files/9320678/Adoptium-.Revised.zip)

**Comment by tellison** [comment]
Website updated being handled in https://github.com/adoptium/website-v2/pull/909

**Comment by tellison** [comment]
Updates completed
