### ISSUE TITLE
Run platform groups in separate pipelines to reduce interdependency on completion time

### ISSUE THREAD

**Issue by jiekang** [adoptium/adoptium#162]
Due to the design of the build pipeline where JDK binaries / artifacts are only copied at the end of the pipeline to their 'final archival spot', it implies that we lose time on launching TCKs.  Example: from the time of the launch of the jdk17 pipeline to the time it will complete all platforms and copy artifacts, is several hours.  Meanwhile some of the child jobs within the platform complete quickly, and testing could proceed without waiting for all platforms to complete.

One way to mitigate this could be by running the 'fast to build' platforms together and separating the 'slow to build' platforms into a second run.  I think we decided last retrospective that we should do this, but have launched the jdk17 and jdk11 with all platforms together.

_Originally posted by @smlambert in https://github.com/adoptium/adoptium/issues/155#issuecomment-1189563474_

We should analyze the build times and priorities to decide how we want to group platforms and if certain platforms should be launched separately due to their build length.

It should eventually be made clear in documentation for running the release jobs on how things should be structured.

**Comment by jiekang** [comment]
See also

https://github.com/adoptium/adoptium/issues/155#issuecomment-1190227099

https://github.com/adoptium/adoptium/issues/155#issuecomment-1190249458

**Comment by sxa** [comment]
The important thing here is to ensure that the primary platforms are not delayed unnecessarily. At the moment some of the Windows pipelines have proven to be particularly slow and that needs to be understood before making a decision on this. https://github.com/adoptium/temurin-build/issues/3065 has been raised with an intention of ensuring that we have sufficient capacity across our build and test farm, that it is online and functional, and that we do not end up in the situation where 32-bit windows (Not a primary platform) does not block 64-bit windows (Which is a primary platform).

**Comment by sxa** [comment]
Build+AQA times for 11.0.16.1+1:
- **PRIMARY**
  - Win64 [5h13](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-temurin/98/)
  - Linux/x64: [4h49](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-temurin/100/)
  - Mac/x64: [6h04](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-temurin/102/)
- Mac/aarch64: [???](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-aarch64-temurin/68/)
- Linux/aarch64: [4h50](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-temurin/99/)
- Linux/ppc64le: [???](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-ppc64le-temurin/93/)
- Linux/arm: [4h24](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-arm-temurin/95/)
- Linux/s390x: [4h13](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-temurin/91/)
- Win32: [5h40](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x86-32-temurin/100/)
- Alpine/x64: [5h06](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-alpine-linux-x64-temurin/95/)
- AIX/ppc64: [6h04](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-temurin/110/)

**Comment by sxa** [comment]
Related: JDK8/11 build+AQA times: https://github.com/adoptium/adoptium/issues/162

**Comment by sxa** [comment]
The correct way to address the concerns here is to have the pipelines be able to trigger the TCK runs as soon as the builds are complete and in parallel with starting the main AQA jobs.

**Comment by smlambert** [comment]
This issue can now be closed as https://github.com/adoptium/ci-jenkins-pipelines/pull/405 has been delivered which brings in the use of the Remote Trigger plugin to launch TCK pipelines on the temurin-compliance server automatically.
