### ISSUE TITLE
[Marketplace]: Please add Azul to the marketplace

### ISSUE THREAD

**Issue by sashapepin** [adoptium/adoptium#163]
### Adoptium Working Group Member

- [X] Eligible Adoptium Working Group Member

### Adoptium Marketplace Publisher Agreement

- [X] Adoptium Marketplace Publisher Agreement Executed

### Publisher Logo

https://raw.githubusercontent.com/zulu-openjdk/azul-adoptium/main/marketplace-data/vendor-azul.png

### Link to Product Listing Information

https://raw.githubusercontent.com/zulu-openjdk/azul-adoptium/main/marketplace-data/index.json

### Publisher Public Key

```shell
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAnFscuVYcWq1zRRoF5mMB
bZvdBZdO9W6Ze14O/b4Qav1atklAF4nVh1bWk/afWaFmRENtUfIXqAa2FdEQZF/U
YVZBmNVckrLWGfG7iRVTPl59AeIubhe+C1Abvag8d+1ul+pE+bnk8ot92l7T9Wbs
jLhls/xg5pXjW0MqaLzMLlfBKuUnk3mNNGIZ7X0wYG8sbYgNQNUbT4O+rP121k6y
C1krtGw7jKK1VEWnT4fGM1sdAGScHm103mG0KEUzCrzXN9lotCkBNhHFrZE8oVdf
yQkMYIbMFnnY9okFkqNcBq9Sdn0xa/3iyFrY5y/3sRgx+PndPAhloLoBbjZZzbmo
Xz2dPz9VtYNrfksX8pJ/0UUpG/KgbqV3dsx1iz2ylI9OwyRsYZlVwiFyMwhkPjad
l1KQdEhfFJ7DgXviM/vezX6oL+YBzrPsFG3IQ5a8mDcDMbERj9U6zPRLsi6INvhg
4D8vaCY9Ld5IpzhARmOu0EwqTZXFZQMgrsleY5oolY9myzt1jkMwD2W+GxdaPKfk
yUlCZHVi/BQTvV7p3h/ImAkx4EmXr3S/k5ykLpShxSwQIuFbydfaTpQjmX11aUk5
btAZ+Hz7IJq7Mcq7Z5aPi25y+OaM0MgjwSgUd/ghdYdH0FSsxJXbbCgSgswWFpa5
vZYH2pCBtzbrpXXdk5SPPcECAwEAAQ==
-----END PUBLIC KEY-----
```

### Post Download Page

https://www.azul.com/downloads

**Comment by tellison** [comment]
Thank you @sashapepin.

**Comment by tellison** [comment]
Into the production API here
https://marketplace-api.adoptium.net/v1/assets/latestForVendors?vendor=azul

and displayed in the UI here (select Linux/x64/JDK/8)
https://adoptium.net/marketplace/?version=8

**Comment by sashapepin** [comment]
Hi @tellison,
 yes, information about Azul as a vendor exists but that information is incomplete and outdated. Could you please use new information instead.

**Comment by tellison** [comment]
> Hi @tellison, yes, information about Azul as a vendor exists but that information is incomplete and outdated. Could you please use new information instead. Thanks.

Which information is out of date? This is being pulled live from [your repository referenced above](https://github.com/zulu-openjdk/azul-adoptium/tree/main/marketplace-data). When you update that repository the Adoptium marketplace information will be updated (assuming the data is valid). I have [an open PR to check validity](https://github.com/zulu-openjdk/azul-adoptium/pull/1) for you.

We do need to fix the icon, so it would be helpful to have a transparent background version of [the one you provided](https://raw.githubusercontent.com/zulu-openjdk/azul-adoptium/main/marketplace-data/vendor-azul.png) then I can update it

**Comment by sashapepin** [comment]
Our logo which is currently displayed is out of date, could you please update it. New logo which I provided has transparent background. As far as I know neither "Link to Product Listing Information" nor public key were previously provided.
So I guess they also should be put somewhere.
Thanks.

**Comment by tellison** [comment]
@sashapepin should the Azul company logo in the "Vendor" column (below) and [members page](https://adoptium.net/members) also be changed, or are you happy with it like this?

![Screenshot 2022-08-11 at 13 52 12](https://user-images.githubusercontent.com/621161/184137841-d1c9adb9-d4c1-4257-967c-01e4e4ab2b45.png)

**Comment by sashapepin** [comment]
Thanks a lot @tellison !
I'am happy with this view, no need to change the logo in Vendor column.
