### ISSUE TITLE
Indicate whether a given release is LTS or not in java -version

### ISSUE THREAD

**Issue by thekalinga** [adoptium/adoptium#164]
Ubuntu does this simple yet neat thing of specifying whether a given version is LTS or not when we run ` lsb_release -a`

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

Its easy for people to know whether they are on LTS (or) not without searching on the internet. Since Java is fast moving, it would help users to know if they are on LTS/not when they type `java -version` too.

In the world of sdkman where we can pull multiple versions of java, this minor thing would come quite handy.

**Comment by karianna** [comment]
We follow the formal upstream versioning JEP and so this won't be changed in the forseable future.
