### ISSUE TITLE
[Marketplace]: Add Alibaba Dragonwell Standard Edition

### ISSUE THREAD

**Issue by sanhong** [adoptium/adoptium#165]
### Adoptium Working Group Member

- [X] Eligible Adoptium Working Group Member

### Adoptium Marketplace Publisher Agreement

- [X] Adoptium Marketplace Publisher Agreement Executed

### Publisher Logo

https://github.com/dragonwell-releng/dragonwell-adoptium/tree/master/logo

### Link to Product Listing Information

https://github.com/dragonwell-releng/dragonwell-adoptium/blob/master/json/index.json

### Publisher Public Key

```shell
Publisher Public Key
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3Ijgnr3YCY0KyMVvgVmq
i3PAkCVw6JaR4n4OlLHr0lSzl2cukUBx6FSM3MnWonbmrXriU7WZyHCbuhe9e1S+
9rki7EofuT5cqEzzUT+sHpJxYOEBb0zQSESGSZuQq/RHfauxTCgF+9Yyb3VZwE99
4Cj8WZhv3Fchzigb3SBnOcMqnS8D+AcThuwLTCUdZiIXjzIYc/sN/TYdq4+CNRM2
xeWlA5CNvy9sw945oYYb6eoa4XAhKhHcs09sygzxQVkPE6xHgAtUuaYf1QwJYUdf
6ITAPf7dIEPRu2gaeR5rnHO1jl/G9dmT/ay2FlUzPGQvNqL+8uxyODaU114dOT9i
JRT7AJ8XrKQDqU/CCWkPwzZ0vUbwpmsXYWztPve2YdieGWSHxnZzQ8NIiGCltv6A
yC/iyhphBgW0iZ+w6A0LSKimAW9Emh2ArDJ0JEPwh+T6d80xeSCLtTptEC/e09UJ
nC4EZKTpEn/KzyFLWiFEas4x1uzLGroV1biMHkzxwNhljiEq0TvpeYSzUg46r6NO
/eqwQq54bEKDzjbIZtfMdZX3xZGAD9Sr/pHBjKJ80WMYBhzLPhPdzStXaCUC2AGn
8oZpdR99t2wIwWLBmDzMjwKRr7KPLoYdFyP5hi2zP1ljTHsmuQbG92B4ySnAT/Bm
vXIShl3XzS34soZEIZsxtaMCAwEAAQ==
-----END PUBLIC KEY-----
```

### Post Download Page

https://dragonwell-jdk.io/

**Comment by tellison** [comment]
Thank you Sanhong, this in in progress now. I will send you any questions that arise.

**Comment by tellison** [comment]
The data is now live in [the Adoptium marketplace](https://adoptium.net/marketplace) (be sure to select appropriate filters) - thanks.
