### ISSUE TITLE
verify items in Checklist are valid and correct them

### ISSUE THREAD

**Issue by zdtsw** [adoptium/adoptium#169]
https://github.com/adoptium/adoptium/blob/main/.github/ISSUE_TEMPLATE/release-checklist.md

- `**Edit the [Homebrew Temurin Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/temurin.rb) and replace the version and sha256 as appropriate. This means for Homebrew users that they install the latest by default and can use the @ notation to install older versions if they wish.` check if this still need manual update or it is done by GH action in homebrew-cask repo.
- `- [ ] **Update support page** (_automate_* github workflow to create a PR to update [support.handlebars](https://github.com/adoptium/adoptium.net/blob/master/src/handlebars/support.handlebars))` update link to https://github.com/adoptium/website-v2/blob/main/src/asciidoc-pages/support.adoc
- `- [ ] **Update release notes** (_automate_* - github workflow to create update for [release notes page](https://adoptium.net/release_notes.html))` skip this step till we have a release note and then update link

**Comment by tellison** [comment]
Checklist has been revised a few times. Closing this older issue.
