### ISSUE TITLE
Mark intermediate builds appropriately

### ISSUE THREAD

**Issue by tellison** [adoptium/adoptium#17]
Part of #5 

Intermediate builds (which are formally defined [here](https://projects.eclipse.org/projects/adoptium/governance), but take as non-JCK'd builds) need to be marked with the word "UNTESTED" or "INCOMPATIBLE" or "UNSTABLE" or "BETA".

**Comment by smlambert** [comment]
Prefer the use of the term BETA, followed by INCOMPATIBLE.  

The other 2 terms do not seem appropriate or correct statements unless there is more context given in the statement.

**Comment by tellison** [comment]
"beta" is fine by me.

**Comment by andrew-m-leonard** [comment]
So presumably we need such a field in the binary "Release" file and MetaData, eg: in here somewhere...?
Metadata:
```
{
13:41:49      "vendor": "Eclipse Foundation",
13:41:49      "os": "aix",
13:41:49      "arch": "ppc64",
13:41:49      "variant": "hotspot",
13:41:49      "version": {
13:41:49          "minor": 0,
13:41:49          "patch": null,
13:41:49          "msi_product_version": "17.0.0.23",
13:41:49          "security": 0,
13:41:49          "pre": null,
13:41:49          "adopt_build_number": null,
13:41:49          "major": 17,
13:41:49          "version": "17+23",
13:41:49          "semver": "17.0.0+23",
13:41:49          "build": 23,
13:41:49          "opt": null
13:41:49      },
```
Release file:
```
IMPLEMENTOR="AdoptOpenJDK"
IMPLEMENTOR_VERSION="AdoptOpenJDK"
JAVA_VERSION="11.0.11"
JAVA_VERSION_DATE="2021-04-20"
MODULES="java.base java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.logging java.management java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.jvmstat jdk.attach jdk.charsets jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.dynalink jdk.internal.ed jdk.editpad jdk.httpserver jdk.internal.le jdk.internal.opt jdk.jartool jdk.javadoc jdk.jcmd jdk.management jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jlink jdk.jshell jdk.jsobject jdk.localedata jdk.naming.dns jdk.naming.ldap jdk.naming.rmi jdk.net jdk.pack jdk.rmic jdk.scripting.nashorn jdk.scripting.nashorn.shell jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported jdk.unsupported.desktop jdk.xml.dom jdk.zipfs openj9.cuda openj9.dataaccess openj9.traceformat openj9.dtfj openj9.dtfjview openj9.gpu openj9.jvm openj9.sharedclasses openj9.zosconditionhandling"
OS_ARCH="x86_64"
OS_NAME="Darwin"
SOURCE="OpenJDK:7222dc7018 OpenJ9:d780e8d8b OMR:5b6b694d8"
BUILD_SOURCE="git:daed513"
FULL_VERSION="11.0.11+4-202103041813"
SEMANTIC_VERSION="11.0.11+4"
BUILD_INFO="OS: Mac OS X Version: 10.14.6 18G84"
JVM_VARIANT="Openj9"
JVM_VERSION="master-d780e8d8b"
HEAP_SIZE="Standard"
OPENJ9_TAG="openj9-0.24.0-m1"
IMAGE_TYPE="JDK"
```

**Comment by sxa** [comment]
I would personally prefer "UNSTABLE" for nightlies which sounds like exactly the right term to me. For any other sort of of "almost ready" builds (such as the ones we have previously marked as "ea" my preference is for BETA, which would probably be the best term for the April GA rebuilds we are looking to do at first via Adoptium in the absence of a TCK.

**Comment by tellison** [comment]
> So presumably we need such a field in the binary "Release" file and MetaData, eg: in here somewhere...?
> Metadata:

@andrew-m-leonard the requirement is as written in the [governance document](https://projects.eclipse.org/projects/adoptium/governance), which does not specify the nature of the mark. It could be as simple as making the status clear on the website where the binary is hosted, or have it "built into" the binary as you describe. We should decide what fits the requirement and does our users a service.

We may see value in having the mark ('beta' or 'unstable' etc.) printed out as part of the java -version so we can easily identify it after installation. Otherwise, I suggest we just add the mark as part of the non-release artefact filename, e.g. `OpenJDK16U-jre_x64_mac_hotspot_16.0.1_9_beta.tar.gz`

**Comment by tellison** [comment]
Completed via https://github.com/adoptium/temurin-build/pull/2654
