### ISSUE TITLE
September 2022 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by gdams** [adoptium/adoptium#170]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).

✔️ results in these Tables means the activity has successfully completed.

⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.

⛔ means there is no build planned for that version/platform combination.

⏸️ means activity not yet started.

### JDK19+36
Pipeline launched September 20, 2022

| Platform  | jdk19 AQA | jdk19 TCK | jdk19 published| jdk19 installers | jdk19 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| aarch64 Linux | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| s390x Linux   | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppc64 AIX | ✔️         | ⏳         | ⏸️              | ⛔               | ⛔            |       |
| x32 Windows | ✔️       | ✔️         | ⏸️              | ⏸                | ⛔            |       |
| arm32 Linux | ✔️       | ✔️         | ✔️              | ✔️                | ✔️             |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ⛔                | ✔️             | This will be a headless build |
| aarch64 Mac | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |

**Comment by karianna** [comment]
Note Alpine on Aarch64 and Linux s390 currently have blockers found in testing.  Investigation continues.  @gdams Are we missing the Alpine Aarch64 row above?

**Comment by gdams** [comment]
> Note the the "Alpine on Aarch64" platform (which we are not releasing anyhow) currently has a blocker found in testing.

@karianna we can add it if you think it's going to be possible to ship this time round?

**Comment by karianna** [comment]
I think it's pretty short notice.  Maybe for 19.0.1 with PMC approval?

**Comment by smlambert** [comment]
Closing as complete
