### ISSUE TITLE
Update release checklist to add a "re-enable tests" reminder

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#177]
Add a check list item at the end of the [release checklist](https://github.com/adoptium/adoptium/blob/main/.github/ISSUE_TEMPLATE/release-checklist.md) to remind release champions to re-enable testing.

**Comment by mahamtariq58** [comment]
I would like to work to on this issue!

**Comment by tellison** [comment]
> I would like to work to on this issue!

Thank you @mahamtariq58 . You have been assigned to this task.

**Comment by Ndacyayisenga-droid** [comment]
@tellison can I take this on?
