### ISSUE TITLE
Scorecard/Timeline for Oct 2022 Release

### ISSUE THREAD

**Issue by zdtsw** [adoptium/adoptium#184]
## Primary platforms (4 JDK versions, 12 primaries releases)

12 of 12 primaries have been published.
AQAvit: when auto tests of AQAvit start till test result triage finish
TCK: when auto TCK tests start till all tests done with result triaged
The target goal is to publish each within **2 business days** of the tagged build being completed.

```mermaid
gantt
title Timelines for Primary Platforms for Oct 2022 Release
dateFormat  YYYY-MM-DD


section JDK17 x64 Linux
Build           :done, a1, 2022-10-19, 0d
AQAvit     :done, after a1, 30h
TCK         :done, after a1, 7d
Publish   :done, milestone, 2022-10-26, 0d


section JDK17 x64 Windows
Build           :done, a2, 2022-10-19, 0d
AQAvit     :done, after a2  , 30h
TCK         :done, after a2, 7d
Publish   :done, milestone, 2022-10-26, 0d

section JDK17 x64 Mac
Tagged build           :done, a3, 2022-10-19, 0d
AQAvit     :done, after a3  , 30h
TCK         :done, after a3, 9d
Publish        :done, milestone, 2022-10-28, 0d

section JDK11 x64 Linux
Build :done, a4, 2022-10-19, 0d
AQAvit :done, after a4 ,  30h
TCK :done, after a4, 6d
Publish :done, milestone, 2022-10-25, 0d

section JDK11 x64 Windows
Build :done, a5, 2022-10-19, 0d
AQAvit :done, after a5 ,  30h
TCK :done, after a5, 6d
Publish :done, milestone, 2022-10-25, 0d

section JDK11 x64 Mac
Build           :done, a6, 2022-10-19, 0d
AQAvit     :done, after a6 , 30h
TCK         :done, after a6, 9d
Publish   :done, milestone, 2022-10-28, 0d

section JDK8 x64 Linux
Build :done, a10, 2022-10-21, 0d
AQAvit :done, after a10, 3d
TCK :done, after a10, 5d
Publish :done, milestone, 2022-10-26, 0d

section JDK8 x64 Mac
Build      :done, a12, 2022-10-21, 0d
AQAvit      :done, after a12, 3d
TCK      :done, after a12, 13d
Publish        :done, milestone, 2022-11-03, 0d

section JDK8 x64 Windows
 Build      :done, a11, 2022-10-21, 0d
 AQAvit      :done, after a11, 3d
 TCK      :done, after a11, 14d
 Publish   :done, milestone, 2022-11-04, 0d


section JDK19 x64 Linux
Build :done, a13, 2022-10-19, 0d
AQAvit :done, after a13, 3d
TCK :done, after a13,7d
Publish :done, milestone, 2022-10-26, 0d

section JDK19 x64 Mac
Build      :done, a15, 2022-10-19, 0d
AQAvit     :done, after a15, 6d
TCK     :done, after a15, 12d
Publish        :done, milestone, 2022-10-31, 0d

section JDK19 x64 Windows
Build      :done, a14, 2022-10-19, 0d
AQAvit     :done, after a14, 3d
TCK     :done, after a14, 12d
Publish        :done, milestone, 2022-10-31, 0d


```
---

## Secondary platforms (by version) 
---

7 of 7 published (8 secondary platforms in total, but AIX not expected to be published)
Target to complete the majority within **5 business days** of tagged build.
### JDK17 Secondaries
```mermaid
gantt
title Timelines for Secondary Platforms for JDK17 for Oct 2022 Release
dateFormat  YYYY-MM-DD
excludes Sunday, Saturday

section JDK17 aarch64 Linux
Tagged build           :done, a1, 2022-10-19, 0d
AQAvit     :done, after a1, 30h
TCK         :done, after a1, 5d
Publish   :done, milestone, 2022-10-26, 0d

section JDK17 alpine-linux
Tagged build           :done, a2, 2022-10-19, 0d
AQAvit     :done, after a2, 30h
TCK         :done, after a2, 4d
Publish   :done, milestone, 2022-10-25, 0d

section JDK17 ppc64le Linux
Tagged build           :done, a3, 2022-10-19, 0d
AQAvit     :done, after a3, 30h
TCK         :done, after a3, 7d
Publish   :done, milestone, 2022-10-28, 0d

section JDK17 aarch64 Mac
Tagged build           :done, a4, 2022-10-19, 0d
AQAvit     :done, after a4, 30h
TCK         :done, after a4, 7d
Publish   :done, milestone, 2022-10-28, 0d

 section JDK17 x32 Windows
 Tagged build           :done, a5, 2022-10-19, 0d
 AQAvit     :done, after a5, 30h
 TCK         :done, after a5, 9d
 Publish   :done, milestone, 2022-11-01, 0d

section JDK17 arm32 Linux
Tagged build           :done, a6, 2022-10-19, 0d
AQAvit     :done, after a6, 9d
TCK         :done, after a6, 9d
Publish   :done, milestone, 2022-11-01, 0d


section JDK17 s390x Linux
Tagged build           :done, a7, 2022-10-19, 0d
AQAvit     :done, after a7, 13d
TCK         :done, after a7, 7d
Publish   :done, milestone, 2022-11-06, 0d

```
---

8 of 8 published. 
Target to complete the majority within **5 business days** of tagged build.
### JDK11 Secondaries
```mermaid
gantt
title Timelines for Secondary Platforms for JDK11 for Oct 2022 Release
dateFormat  YYYY-MM-DD
excludes Sunday, Saturday

section JDK11 aarch64 Linux
Tagged build   :done, a1, 2022-10-19, 0d
AQAvit     :done, after a1, 30h
TCK         :done, after a1, 4d
Publish   :done, milestone, 2022-10-25, 0d

section JDK11 ppc64le Linux
Tagged build           :done, a2, 2022-10-19, 0d
AQAvit     :done, after a2, 30h
TCK         :done, after a2, 5d
Publish   :done, milestone, 2022-10-26, 0d

section JDK11 alpine-linux
Tagged build           :done, a3, 2022-10-19, 0d
AQAvit     :done, after a3, 30h
TCK         :done, after a3, 4d
Publish   :done, milestone, 2022-10-25, 0d

section JDK11 aarch64 Mac
Tagged build           :done, a4, 2022-10-19, 0d
AQAvit     :done, after a4, 30h
TCK         :done, after a4, 6d
Publish   :done, milestone, 2022-10-27, 0d

section JDK11 x32 Windows
Tagged build           :done, a5, 2022-10-19, 0d
AQAvit     :done, after a5, 30h
TCK         :done, after a5, 9d
Publish   :done, milestone, 2022-11-01, 0d

section JDK11 arm32 Linux
Tagged build           :done, a6, 2022-10-19, 0d
AQAvit     :done, after a6, 30h
TCK         :done, after a6, 9d
Publish   :done, milestone, 2022-11-01, 0d


section JDK11 s390x Linux
Tagged build           :done, a7, 2022-10-19, 0d
AQAvit     :done, after a7, 6d
TCK         :done, after a7, 12d
Publish   :done, milestone, 2022-11-04, 0d

section JDK11 ppc64 AIX
Tagged build           :done, a8, 2022-10-19, 0d
AQAvit     :done, after a8, 30h
TCK         :done, after a7, 15d
Publish   :done, milestone, 2022-11-09, 0d	

```
---

8 of 8 published. 
Target to complete the majority within **5 business days** of tagged build.
### JDK8 Secondaries
```mermaid
gantt
title Timelines for Secondary Platforms for JDK8 for Oct 2022 Release
dateFormat  YYYY-MM-DD
excludes Sunday, Saturday

section JDK8 ppc64le Linux
Tagged build           :done, a1, 2022-10-21, 0d
AQAvit     :done, after a1, 3d
TCK         :done, after a1, 4d
Publish   :done, milestone, 2022-10-27, 0d

section JDK8 aarch64 Linux
Tagged build   :done, a2, 2022-10-21, 0d
AQAvit     :done, after a2, 3d
TCK         :done, after a2, 5d
Publish   :done, milestone, 2022-10-28, 0d

section JDK8 alpine-linux
Tagged build           :done, a3, 2022-10-21, 0d
AQAvit     :done, after a3, 3d
TCK         :done, after a3, 8d
Publish   :done, milestone, 2022-11-02, 0d

section JDK8 arm32 Linux
Tagged build           :done, a4, 2022-10-24, 2d
AQAvit     :done, after a4, 6d
TCK         :done, after a4, 6d
Publish   :done, milestone, 2022-11-03, 0d

section JDK8 x64 Solaris
Tagged build           :done, a5, 2022-10-21, 0d
AQAvit     :done, after a5, 3d
TCK         :done, after a5, 10d
Publish   :done, milestone, 2022-11-04 0d

section JDK8 x32 Windows
Tagged build           :done, a6, 2022-10-21, 0d
AQAvit     :done, after a6, 3d
TCK         :done, after a6, 10d
Publish   :done, milestone, 2022-11-04, 0d

section JDK8 ppc64 AIX
Tagged build           :done, a7, 2022-10-21, 0d
AQAvit     :done, after a7 ,  3d
TCK         :done, after a7, 14d
Publish   :done, milestone, 2022-11-10, 0d


section JDK8 solaris sparcv9
Tagged build           :done, a8, 2022-10-21, 0d
AQAvit     :done, after a8, 17d
TCK         :done, after a8, 11d
Publish   :done, milestone, 2022-11-15, 0d

```
---

7 of 7 published (8 secondary platforms in total, but AIX not expected to be published)
 Target to complete the majority within **7 business days** of tagged build.
### JDK19 Secondaries
```mermaid
gantt
title Timelines for Secondary Platforms for JDK19 for Oct 2022 Release
dateFormat  YYYY-MM-DD
excludes Sunday, Saturday

section JDK19 alpine-linux
Tagged build           :done, a1,2022-10-19, 0d
AQAvit     :done, after a1, 6d
TCK         :done, after a1, 2d
Publish   :done, milestone, 2022-10-27, 0d

section JDK19 aarch64 Mac
Tagged build           :done, a2, 2022-10-19, 0d
AQAvit     :done, after a2, 2d
TCK         :done, after a2, 7d
Publish   :done, milestone, 2022-10-28, 0d

section JDK19 aarch64 Linux
Tagged build   :done, a3, 2022-10-19, 0d
AQAvit     :done, after a3, 2d
TCK         :done, after a3, 7d
Publish   :done, milestone, 2022-10-28, 0d

section JDK19 x32 Windows
Tagged build           :done, a4, 2022-10-19, 0d
AQAvit     :done, after a4, 2d
TCK         :done, after a4, 10d
Publish   :done, milestone, 2022-11-02, 0d

section JDK19 ppc64le Linux
Tagged build           :done, a5, 2022-10-19, 0d
AQAvit     :done, after a5, 2d
TCK         :done, after a5, 11d
Publish   :done, milestone, 2022-11-03, 0d

section JDK19 arm32 Linux
Tagged build           :done, a6, 2022-10-19, 0d
AQAvit     :done, after a6, 2d
TCK         :done, after a6, 11d
Publish   :done, milestone, 2022-11-03, 0d


section JDK19 s390x Linux
Tagged build           :done, a7, 2022-10-19, 0d
AQAvit     :done, after a7, 6d
TCK         :done, after a7, 12d
Publish   :done, milestone, 2022-11-04, 0d

```

**Comment by zdtsw** [comment]
close issue , all data has been capture in description.

**Comment by smlambert** [comment]
Primary platforms target = 2 days, Secondary platforms target = 7 days

---

Release tag: jdk8u352-b08_adopt on Thu Oct 20 04:39:59 EDT 2022

|  Platform    |       OS  |  Released | Target/Actual(days)   | On-time            |          RTAG |
|  --- |  --- |  --- |  --- |  --- |  --- | 
|        x64   |      linux |  10-25-2022    |            2/5     |     No    |     jdk8u352-b08_adopt| 
|    ppc64le    |     linux |  10-27-2022       |         7/7      |   Yes     |    jdk8u352-b08_adopt| 
|    aarch64     |    linux |  10-28-2022   |             7/8     |     No    |     jdk8u352-b08_adopt| 
|        x64|  alpine-linux |  11-02-2022        |       7/13       |   No     |    jdk8u352-b08_adopt| 
  |      x64      |     mac |  11-03-2022  |             2/14   |       No  |       jdk8u352-b08_adopt| 
   |     arm    |     linux  | 11-03-2022         |      7/14    |      No|  jdk8u352-b08-aarch32-20221020_adopt| 
 |       x64 |      solaris|   11-04-2022      |         7/15  |        No       |  jdk8u352-b08_adopt| 
 |       x64   |    windows  11-04-2022    |           2/15      |    No |        jdk8u352-b08_adopt| 
  |      x32   |    windows  | 11-04-2022   |            7/15       |   No    |     jdk8u352-b08_adopt| 
|      ppc64      |     aix |  11-10-2022   |            7/21  |        No   |      jdk8u352-b08_adopt| 
|    sparcv9  |     solaris |  11-15-2022    |           7/26  |        No    |     jdk8u352-b08_adopt| 

On-Time 1(9%)  Late: 10(90%)

---

Release tag: jdk-11.0.17+8_adopt on Tue Oct 18 17:07:11 EDT 2022

|  Platform    |       OS  |  Released | Target/Actual(days)   | On-time            |          RTAG |
|  --- |  --- |  --- |  --- |  --- |  --- | 
|        x64  |     windows |  10-25-2022       |         2/6    |      No    |    jdk-11.0.17+8_adopt | 
|        x64    |     linux |  10-25-2022    |            2/6   |       No |       jdk-11.0.17+8_adopt| 
  |      x64 | alpine-linux |  10-25-2022   |             7/6   |      Yes      |  jdk-11.0.17+8_adopt| 
|    aarch64    |     linux |  10-25-2022   |             7/6     |    Yes  |      jdk-11.0.17+8_adopt | 
|    ppc64le    |     linux  | 10-26-2022     |           7/7     |    Yes       | jdk-11.0.17+8_adopt| 
 |   aarch64   |        mac  | 10-27-2022        |        7/8     |     No   |     jdk-11.0.17+8_adopt| 
  |      x64    |       mac|   10-28-2022  |              2/9  |        No   |     jdk-11.0.17+8_adopt| 
|        x32  |     windows  | 11-01-2022      |         7/13   |       No    |    jdk-11.0.17+8_adopt| 
 |       arm  |       linux |  11-02-2022  |             7/14    |      No   |     jdk-11.0.17+8_adopt| 
  |    s390x     |    linux  | 11-04-2022      |         7/16  |        No |       jdk-11.0.17+8_adopt| 
  |    ppc64   |        aix |  11-09-2022 |              7/21       |   No     |   jdk-11.0.17+8_adopt| 

On-Time 3(27%)  Late: 8(72%)

---

Release tag: jdk-17.0.5+8_adopt on Tue Oct 18 16:42:12 EDT 2022

|  Platform    |       OS  |  Released | Target/Actual(days)   | On-time            |          RTAG |
|  --- |  --- |  --- |  --- |  --- |  --- | 
|        x64 | alpine-linux |  10-25-2022  |              7/6      |   Yes    |     jdk-17.0.5+8_adopt| 
|    aarch64   |      linux |  10-26-2022    |            7/7      |   Yes     |    jdk-17.0.5+8_adopt| 
 |       x64   |      linux |  10-26-2022 |               2/7    |      No     |    jdk-17.0.5+8_adopt| 
|        x64      |windows  | 10-26-2022     |           2/7     |     No    |     jdk-17.0.5+8_adopt| 
|    ppc64le   |      linux  | 10-28-2022  |              7/9  |        No     |    jdk-17.0.5+8_adopt| 
|        x64   |        mac |  10-28-2022  |              2/9      |    No  |       jdk-17.0.5+8_adopt| 
 |   aarch64       |    mac |  10-28-2022 |               7/9     |     No     |    jdk-17.0.5+8_adopt| 
 |       x32  |     windows |  11-01-2022     |          7/13      |    No  |       jdk-17.0.5+8_adopt| 
 |       arm     |    linux |  11-02-2022      |         7/14      |    No   |      jdk-17.0.5+8_adopt| 
   |   s390x    |     linux  | 11-06-2022       |        7/18     |     No |        jdk-17.0.5+8_adopt| 

On-Time 2(20%)  Late: 8(80%)

---

Release tag: jdk-19.0.1+10_adopt on Wed Oct 19 05:52:19 EDT 2022

|  Platform    |       OS  |  Released | Target/Actual(days)   | On-time            |          RTAG |
|  --- |  --- |  --- |  --- |  --- |  --- | 
 |        x64   |       linux  |  10-26-2022     |            2/6     |      No    |     jdk-19.0.1+10_adopt|  
|         x64 |  alpine-linux  |  10-27-2022    |             7/8      |     No    |     jdk-19.0.1+10_adopt|  
|     aarch64    |        mac|    10-28-2022    |             7/9       |    No   |      jdk-19.0.1+10_adopt|  
|     aarch64      |    linux  |  10-28-2022      |           7/9    |       No     |    jdk-19.0.1+10_adopt|  
  |       x64      |      mac|    10-31-2022   |             2/12   |        No |        jdk-19.0.1+10_adopt|  
  |       x64   |     windows  |  10-31-2022     |           2/12     |      No  |       jdk-19.0.1+10_adopt|  
  |       x32     |   windows |   11-02-2022   |             7/13    |       No   |      jdk-19.0.1+10_adopt|  
 |    ppc64le  |        linux  |  11-03-2022   |             7/15   |        No   |      jdk-19.0.1+10_adopt|  
  |       arm   |       linux  |  11-03-2022     |           7/15      |     No  |       jdk-19.0.1+10_adopt|  
 |      s390x      |    linux  |  11-04-2022     |           7/16  |         No     |    jdk-19.0.1+10_adopt|  

On-Time 0(0%)  Late: 10(100%)

**Comment by smlambert** [comment]
| Release activity | % within target |
| --- | --- | 
| jdk8u352-b08 | 9% |
| jdk-11.0.17+8 | 27%|
| jdk-17.0.5+8 | 20%|
| jdk-19.0.1+10 | 0%|
