### ISSUE TITLE
Temurin Compliance Improvements Checklist: Nov 2022

### ISSUE THREAD

**Issue by jiekang** [adoptium/adoptium#189]
Placeholder to track compliance work for Project planning

- https://github.com/temurin-compliance/temurin-compliance/issues/151
- https://github.com/temurin-compliance/temurin-compliance/issues/225
- https://github.com/temurin-compliance/temurin-compliance/issues/193
- https://github.com/temurin-compliance/temurin-compliance/issues/156
- https://github.com/temurin-compliance/temurin-compliance/issues/245
- [EF 2032: Upgrade jenkins agents to use JDK11+ to support next jenkins LTS](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2032)

**Comment by jiekang** [comment]
Closing, replaced by https://github.com/adoptium/adoptium/issues/206

**Comment by zdtsw** [comment]
can have this one closed
