### ISSUE TITLE
Bi-weekly Adoptium Community Call - June 1, 2021

### ISSUE THREAD

**Issue by adamfarley** [adoptium/adoptium#19]
**Time**

Tuesday June 1, 2021 4pm-5pm GMT (11am-12pm EST/Ontario)

**Location**

https://bluejeans.com/956754991/2833?src=calendarLink

Add this recurring bi-weekly Adoptium Community Call to your calendar, if you wish. Available via the [Adoptium community calendar.](https://calendar.google.com/calendar/u/1?cid=Y191YW5ub3VtczVobzBvbGhqazN1bGVjZGtiY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

**Overall Purpose**

Mainly to make announcements regarding planned actions that affect the Adopt community
(Emphasis on non-test efforts, as those are covered in AQAvit call on Wednesdays)

Secondary purposes include debate, discussion, and community socializing.

Call to be recorded for reference, and linked in this issue afterwards.

**Proposed Meeting Agenda** - TBD / topics to be confirmed

- [x] First Temurin release - status update
- [x] Update on linux installers work
- [ ] Update on reproducible builds prototype
- [x] Review PMC Highlights.
- [x] Make a “revoked public access to builds” announcement.
- [x] Review this issue growth chart.

![image](https://user-images.githubusercontent.com/26874628/118981201-036fc900-b972-11eb-99b6-6807d6bfb670.png)

**Comment by AdamBrousseau** [comment]
Agenda item
https://github.com/adoptium/ci-jenkins-pipelines/pull/154

**Comment by smlambert** [comment]
Meeting [Recording link](https://bluejeans.com/s/isBdHuPWdG6)

Minutes: 

- First Temurin release 
  - today received final signature on 3way agreement, will proceed to download TCK material as per https://github.com/adoptium/adoptium/issues/3
  - we will start with jdk8 builds for xlinux/mac/win64 as outlined in Milestone 1 
- Update on linux installers work 
  - https://github.com/adoptium/installer/tree/master/linuxNew has been added, there is a Jenkins job, but we are not going to move to it fully until a new hosting solution is determined
- Update on reproducible builds prototype 
  - being progressed under https://github.com/adoptium/temurin-build/issues/2594, perhaps we can get an update from @andrew-m-leonard in upcoming meeting
- Review PMC Highlights 
  - PMC minutes will be published to the mailing list (see here: https://projects.eclipse.org/projects/adoptium/contact) 
- Make a “revoked public access to builds” announcement. 
  - non-Temurin builds no longer visible on Jenkins server (as per agreement between Eclipse Foundation and Oracle)
  - infra item to give TRSS access to query for build log and status (but not artifacts)
- Review this issue growth chart
  - we should review regularly and make a plan to reduce the issue set back down to under 150
  - divide features from issues
  - look at PR backlog numbers
  - Zenhub added to adoptium org, available for project mgmt (will be used by AQAvit to manage 7 test-related repos under one board)

**Comment by smlambert** [comment]
Link to next meeting: https://github.com/adoptium/adoptium/issues/23
