### ISSUE TITLE
[Marketplace]: Add Microsoft Build of OpenJDK

### ISSUE THREAD

**Issue by gdams** [adoptium/adoptium#190]
### Adoptium Working Group Member

- [X] Eligible Adoptium Working Group Member

### Adoptium Marketplace Publisher Agreement

- [X] Adoptium Marketplace Publisher Agreement Executed

### Publisher Logo

https://adoptium.net/images/vendors/vendor-microsoft.png

### Link to Product Listing Information

https://raw.githubusercontent.com/microsoft/openjdk-adoptium-marketplace-data/main/index.json

### Publisher Public Key

```shell
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAthk+3LmwJB8DPgmm26Z9
M08ONQDFVwpK1GdDDxcqoTb0g6uEFOhM3uxofl2WZe3Hy6Z7s+m8ostxqpTSkBFe
UcWv8xtDWduSrl+dtV3NqkRXbn0fvhQdULihKq5NWfIOQq/rAOX+HCelpw5XXJzd
bzltqV0pncrqKX6p386lYj5n0UexEat1FV7RAEm5zK9OXDJqWfFPrS3lOwUZgHlH
LnUHnez9INZjOqbjNek0TCbwohJMoFGxkSCPF7Iwn7nDxaip4HLZtYYl6AJfvDDZ
hqKlfEHeN7+TiBURlEGkZkH1QW3T57/q8TBaYro6Bgx9C4iIRhhSwCTIAgTEejWw
dEI1UEmJrEZy8jwKYj5KkzfaxvDrbjSnOl4CX995H2JRBQ40JPMffBW3Ty9+6WRJ
y3CAjm7Ns+cRJYFUaK9vi61hB/8pXcao4F08OYxlY2R1ULWOSemOVrF0YK4Gh+VA
XYARH2Wo08AqS972Wlkedjxohvqlr4vrdAQdxjR/mPvzo60ig3JL30kH1nNiTGtF
fGcZWoUIP3v1S11NQf/GZcK2sxe/chQqtPJTbGCcRgloa9QGs/4+ArAbMNX7TVrC
ZpYv0VyqUeBsf5mm/uYRZECORvekYKl/btYsFR6Rj9E4HSK+7rtvhR6JAVZCeuev
NOO1AQexnIfvsFduGfCpNiECAwEAAQ==
-----END PUBLIC KEY-----
```

### Post Download Page

https://learn.microsoft.com/java/openjdk/

**Comment by tellison** [comment]
@gdams ar you happy with [the Microsoft logo](https://github.com/adoptium/website-v2/blob/main/static/images/microsoft-logo.png) being used for the **distribution** identifier as well as the vendor? We don't ask that in the request template at the moment.

**Comment by gdams** [comment]
> @gdams are you happy with [the Microsoft logo](https://github.com/adoptium/website-v2/blob/main/static/images/microsoft-logo.png) being used for the **distribution** identifier as well as the vendor? We don't ask that in the request template at the moment.

Yes that's fine

**Comment by tellison** [comment]
This is now complete. Thanks for the participation in Adoptium's marketplace!
