### ISSUE TITLE
General Retrospective for January 2023 Releases

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#200]
**Summary**

A retrospective for all efforts surrounding the titular releases. 
All community members are welcome to contribute to the agenda via comments below.
This will be a virtual meeting after the release, with at least a week of notice in the #release Slack channel.
On the day of the meeting the agenda items will be iterated over, with a list of actions added in a comment at/near the end.

Invited: Everyone.

**Time, Date, and URL**
During regular Wednesday community call

Time: 8:30am EST / 1:30pm UTC
Date: Feb 1, 2023

URL: https://eclipse.zoom.us/j/81872484707?pwd=dGl1QzcrTllWUkNWRUVGNzdYVUx4dz09 
Meeting ID: 818 7248 4707 
Passcode: 951478

**Details**

Retrospective Owner Tasks (in order):

- [ ] Post this issue's URL on the \#Release Slack channel around the start of the new release.
- [ ] Copy actions from the previous retrospective into this issue, while ignoring actions that are ticked or have issue links (i.e. clearly-completed actions).
- [ ] Wait until 90% of all builds have been released, with no clear signs of additional respins.
- [ ] Announce the retrospective Slack call's date + time on \#Release at least one full week in advance, and send out meeting invites.
- [ ] Host the slack call for the retrospective, including:
  - [ ] Iterating over the actions from the previous retrospective issue, ticking off completed items.
  - [ ] Iterate over the agenda, ensuring everything gets debated.
  - [ ] Create a clear list of actions at the end of the retrospective, including volunteer names.
- [ ] Create a new retrospective issue for the next release.
- [ ] Set yourself a calendar reminder so that you remember to commence step 1 (in the new issue) just before the next release.
- [ ] Close this issue.

**Comment by smlambert** [comment]
re: https://github.com/adoptium/adoptium/issues/199#issuecomment-1380171049 
I like the build views that @steelhead31 has created in Jenkins.

I typically use TRSS for an overall view of the pipeline, either to look at the tree view of it which helps me see parent->child->grandchild relationships, example [here](https://trss.adoptium.net/buildTreeView?parentId=63c028a8ed0b30773b99558e)

<img width="505" alt="Screen Shot 2023-01-12 at 11 25 18 AM" src="https://user-images.githubusercontent.com/2836948/212123800-df15ac49-05ef-4b5d-bf6f-3f80886b9889.png">


Or my go to view, the Grid view (which we have added the build and smoke tests jobs to as well, which helps show cases where builds failed, so no tests were triggered, example [here](https://trss.adoptium.net/resultSummary?parentId=63c028a8ed0b30773b99558e), though I see we have a 'bug' with handling the new release pipelines and the change to the names of build/smoke tests...  

Raised https://github.com/adoptium/aqa-test-tools/issues/765 but would also like to look at improving naming in build pipelines so we do not need to do mapping.

<img width="388" alt="Screen Shot 2023-01-12 at 4 33 18 PM" src="https://user-images.githubusercontent.com/2836948/212185916-c138f47e-3864-4451-b385-5d98041eb356.png">

Also see that we should not be running the dev level tests as part of the release pipelines, those are part of weekly builds, but should not be triggered as part of a release.  Raised https://github.com/adoptium/ci-jenkins-pipelines/issues/570 to address.

**Comment by zdtsw** [comment]
we do have release-openjdkXX-piepline  log saved (keep this build forever) but the downstream jobs are not.
do we want to save these jobs' log too? (every year 6 releases, should not be more than 10 logs per each jobs)

**Comment by zdtsw** [comment]
some downstream jobs were created when first time generating release jobs, they are not intended for temurin (but openj9 bisheng dragonwell etc) good to have them cleaned up to not confuse others.
e.g 
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk8u/  https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk11u/  https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/

**Comment by zdtsw** [comment]
can we move the `create_install_*` and `sign_installer` before aqa tests (after smoketest done)? 
or running as parallel with aqa tests
so they can fail faster.
e.g
in the mac pipeline, https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-mac-x64-temurin/8/console
it falied in sign_installer step, even all tests are passed. 
took 12hr6min to finish build+tests and reach "create_installer_mac" then we still need to re-build the whole pipeline.

**Comment by andrew-m-leonard** [comment]
The disabling of the weekly-pipeline jobs got re-enabled, I think because a git triggered re-gen of the jobs probably re-generated them enabled... We need to disable in a better way next time

**Comment by smlambert** [comment]
Smoketests will likely need to always be triggered with GENERATE_JOBS=true (for release pipeline config) see https://github.com/adoptium/temurin-build/issues/3212#issuecomment-1382827921.

**Comment by smlambert** [comment]
Likely good to disable nightly testing before dry run triage activities begin, since it slows down triage (Grinders are queued up waiting for machines).

**Comment by andrew-m-leonard** [comment]
Setting build-pipeline-generator job Configuration param ENABLE_PIPELINE_SCHEDULE to False, effectively disableds weekly & nightly builds.. https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/build-pipeline-generator/

**Comment by andrew-m-leonard** [comment]
Now we have settled on "branching" the build repos, I am thinking, we should branch it say 2 weeks before a release, then cherry-pick anything that must go into the release... and stabilise the build over several "dry-runs" during the 2 weeks.

**Comment by zdtsw** [comment]
> Now we have settled on "branching" the build repos, I am thinking, we should branch it say 2 weeks before a release, then cherry-pick anything that must go into the release... and stabilise the build over several "dry-runs" during the 2 weeks.

also need to ensure, if any (should not in most cases) changes done in the release branch is essential for later release (bug fix), the code need to merge back to master.

**Comment by zdtsw** [comment]
> Smoketests will likely need to always be triggered with GENERATE_JOBS=true (for release pipeline config, no need for changing nightly/weekly) see [adoptium/temurin-build#3212 (comment)](https://github.com/adoptium/temurin-build/issues/3212#issuecomment-1382827921).

created https://github.com/adoptium/ci-jenkins-pipelines/issues/585

**Comment by smlambert** [comment]
Nightly build&test kept kicking off despite being disabled (https://adoptium.slack.com/archives/C09NW3L2J/p1674040533536599)

**Comment by smlambert** [comment]
Deleting existing Jenkins jobs and rerunning from scratch as we did for the new release pipelines during the dry run period is a difficult scenario to handle on the monitoring side and resulted in https://github.com/adoptium/aqa-test-tools/issues/767.

**Comment by llxia** [comment]
Not only it is hard to handle on TRSS, but Jenkins also has a similar issue.

**Comment by sxa** [comment]
Process step to ensure that the pinned issue in adoptium/adoptium is set to the current status document and not a previous one (I've just switched it from October -> January

**Comment by jiekang** [comment]
I noticed https://github.com/adoptium/temurin-compliance still exists. Sticking here so I don't forget but maybe this is a future housekeeping item to archive

**Comment by jiekang** [comment]
> > Now we have settled on "branching" the build repos, I am thinking, we should branch it say 2 weeks before a release, then cherry-pick anything that must go into the release... and stabilise the build over several "dry-runs" during the 2 weeks.
> 
> also need to ensure, if any (should not in most cases) changes done in the release branch is essential for later release (bug fix), the code need to merge back to master.

I'd recommend policy to be to require contribution to master followed by backporting to the release branch to prevent this.

**Comment by jerboaa** [comment]
> > > Now we have settled on "branching" the build repos, I am thinking, we should branch it say 2 weeks before a release, then cherry-pick anything that must go into the release... and stabilise the build over several "dry-runs" during the 2 weeks.
> > 
> > 
> > also need to ensure, if any (should not in most cases) changes done in the release branch is essential for later release (bug fix), the code need to merge back to master.
> 
> I'd recommend policy to be to require contribution to master followed by backporting to the release branch to prevent this.

Yes, that --^ +1

**Comment by Haroon-Khel** [comment]
I am not able to edit issues like https://github.com/adoptium/adoptium/issues/202, to update the table when things get done. I notice other users are able to

**Comment by andrew-m-leonard** [comment]
jdk17 x64 Mac Installer actually failed to sign, but that is after all tests are submitted and Passed, we didn't notice that the Installer had problems until we were about to publish the binary!
If the "release-pipeline" had perhaps returned an overall "Unstable" results maybe we would have noticed earlier?

**Comment by zdtsw** [comment]
is it better to use a release branch for **installer** as well?  when the whole release done, merge back to master branch.

the reason is, we need to update rules and changelogs for each jdk version and different distro.
Tto get it quickly out to be able to  build installer, release champion can easily make a commit to the release branch and require one approval.  this can be done by one distro+version. 
instead of a big PR with all changes in batch and merge to master branch with 2 approvals

**Comment by zdtsw** [comment]
last week before release, we should try to dry-run installer jobs as well.
Since we change machines (add new ones, decommission old ones) between two release and the GH action check does not test the case with gpg is enabled.  we need a stable env when the time we build for installer to not block release.

**Comment by smlambert** [comment]
Many infrastructure issues this release (this may not be an exhaustive list):
- https://github.com/adoptium/infrastructure/issues/2882 
- https://github.com/adoptium/infrastructure/issues/2883
- https://github.com/adoptium/infrastructure/issues/2884
- https://github.com/adoptium/infrastructure/issues/2885
- https://github.com/adoptium/infrastructure/issues/2886
- https://github.com/adoptium/infrastructure/issues/2887
- https://github.com/adoptium/infrastructure/issues/2888
- https://github.com/adoptium/infrastructure/issues/2890
- https://github.com/adoptium/infrastructure/issues/2893
- https://github.com/adoptium/infrastructure/issues/2894

This made AQA runs unstable (they should all generally run green, over 90% of failures during release were infra related) and triage difficult and slow.  

Some things we can look at doing to improve:
- ensure new machines are tested thoroughly before adding them (instructions for this were added to an infra FAQ last year)
- more regular AQA triage to catch infra issues regularly
- machine change logs, to be able to answer the question "_when was the last time this machines configuration was changed and what Github issue does the change relate to?_" either by Ansible playbooks, or by humans manually changing things
- machine audits, it appears that the machines are not all configured the same.  Be able to quickly articulate the differences between machine configuration, to aid in debug/triage issues
- label static docker machines so they can be identified and avoided when needed during triage
- consider revisiting the static docker machine approach, in favour of dynamic agents
- if machines are not configured properly, disable them.  Consider turning on an existing feature in test jobs that would automatically disable machines if certain types of failures occur (out of disk space, etc).

**Comment by steelhead31** [comment]
Inadvertenly reran the installer pipelines for the previous jdk8 release for Suse & Rhel...  this causes issues for people downloading the previous releases, as the signatures will have changed.  This needs to be prevented.

**Comment by zdtsw** [comment]
> Inadvertenly reran the installer pipelines for the previous jdk8 release for Suse & Rhel... this causes issues for people downloading the previous releases, as the signatures will have changed. This needs to be prevented.

have a link to the job? think artifactory set to not allow overwritten but might not cover all cases if i recall

**Comment by zdtsw** [comment]
> > > Inadvertenly reran the installer pipelines for the previous jdk8 release for Suse & Rhel... this causes issues for people downloading the previous releases, as the signatures will have changed. This needs to be prevented.
> > 
> > 
> > have a link to the job? think artifactory set to not allow overwritten but might not cover all cases if i recall
> 
> https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline_new/106/
> 
> &
> 
> https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline_new/105/

normally this should not happen, and i can see the reason is because of https://github.com/adoptium/installer/pull/569, which is supposed to build new installer with .2 version, but i very doubt if that happened. that's why today's "accident" made the uploader part worked. (not as an overwritten but as a new .2 release)

**Comment by zdtsw** [comment]
during release weeks, we can dsiable "Adoptium Nightly Build Success" job,
do not feel like keeps posting "yellow" because we stop nightly pipelines.

**Comment by jiekang** [comment]
Closing as comments have been discussed in retros after the January release.
