### ISSUE TITLE
Consider applying to 'Season of Docs' program for Docs improvement

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#201]
In order to assist with improving all Adoptium project documentation (or a subset), we should consider submitting an application to https://developers.google.com/season-of-docs.  Need to see if we'd need to create an org there, or if there is an existing one we can dovetail under.

This issue is to investigate what is involved, and create an outline/proposal for an Adoptium project.

Applications due by March 24th (according to the [timeline](https://developers.google.com/season-of-docs/docs/timeline)).

**Comment by jiekang** [comment]
Useful link to docs to read for what is involved:
https://developers.google.com/season-of-docs/docs/admin-guide

**Comment by jiekang** [comment]
If we choose to participate, here is a short summary of expected work for the organization:

1. Create a web-accessible proposal page, and write an application to be submitted it by March 24, 2023
2. Hire a technical writer by May 10, 2023
3. Work with the technical writer between March 31, 2023 and November 13, 2023
4. Submit five monthly evaluations starting in June and participate in three follow-up surveys in the following year (2024)
5. Submit a final evaluation & case study by November 21, 2023

**Comment by jiekang** [comment]
TODO: Understand contract setup for technical writer payment. Contact EMO about situation

**Comment by smlambert** [comment]
We submitted a project proposal last week for this, details can be found here: https://github.com/adoptium/adoptium/wiki/2023-Google-Season-of-Docs

Special thanks to @jiekang for pulling the bulk of that proposal together!
