### ISSUE TITLE
January 2023 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by steelhead31** [adoptium/adoptium#202]
Please follow live updates in the [release](https://adoptium.slack.com/archives/CLCFNV2JG) channel in the Adoptium Slack workspace.

Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).

✔️ results in these Tables means the activity has successfully completed.

⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.

⛔ means there is no build planned for that version/platform combination.

⏸️ means activity not yet started.

### JDK8u362-b09
| Platform  | [jdk8 AQA](https://github.com/adoptium/aqa-tests/issues/4258)  | jdk8 TCK  | jdk8 published | jdk8 installers  | jdk8 images   | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️        | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   |✔️        | ✔️              | ✔️                 | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️             | ✔️                | ⛔            |       |
| aarch64 Linux | ✔️      | ✔️         | ✔️               | ✔️                | ✔️             |       |
| ppcle64 Linux | ✔️     | ✔️         |  ✔️              | ✔️                | ✔️             |       |
| ppc64 AIX | ✔️         | ✔️         | ✔️              | ⛔               | ⛔            |       |
| x32 Windows | ✔️       | ✔️        | ✔️             | ⛔               | ✔️             |       |
| arm32 Linux | ✔️       | ✔️        | ✔️             | ✔️                | ✔️             |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build  |
| sparcv9 solaris | ✔️   | ✔️         | ✔️              | ⛔               | ⛔            |       |
| x86 solaris | ✔️       | ✔️        | ✔️              | ⛔               | ⛔            |       |

### JDK11.0.18
| Platform | [jdk11 AQA](https://github.com/adoptium/aqa-tests/issues/4256) | jdk11 TCK  | jdk11 published| jdk11 installers | jdk11 images  | Notes |
| -----    | -----     | -----      | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** |✔️   |✔️         | ✔️             | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️              | ✔️               | ⛔            |       |
| aarch64 Linux | ✔️     | ✔️         | ✔️             | ✔️                | ✔️             |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️            | ✔️                | ✔️             |       |
| s390x Linux   | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppc64 AIX | ✔️         | ✔️         | ✔️              | ⛔               | ⛔            |       |
| x32 Windows | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| arm32 Linux | ✔️       | ✔️      | ✔️              | ✔️                | ✔️             |       |
| x64 alpine-Linux | ✔️  | ✔️        | ✔️             |✔️               | ✔️             | This will be a headless build |
| aarch64 Mac | ✔️       | ✔️         | ✔️              | ✔️               | ⛔            |       |

### JDK17.0.6
| Platforms | [jdk17 AQA](https://github.com/adoptium/aqa-tests/issues/4254) | jdk17 TCK | jdk17 published| jdk17 installers | jdk17 images | Notes |
| -----     | -----     | -----     | -----          | -----            | -----        | ----- |
| **x64 Linux** | ✔️     | ✔️     | ✔️              | ✔️                | ✔️            |       |
| **x64 Windows** | ✔️   | ✔️    | ✔️              | ✔️                | ✔️            |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔           |       |
| aarch64 Linux | ✔️     | ✔️        | ✔️              | ✔️                | ✔️            |       |
| ppcle64 Linux | ✔️     | ✔️        | ✔️              | ✔️                | ✔️            |       |
| s390x Linux   | ✔️    | ✔️         | ✔️             | ✔️                | ✔️            |       |
| ppc64 AIX | ✔️         | ✔️         | ✔️              | ⛔               | ⛔           |       |
| x32 Windows | ✔️       | ✔️         | ✔️               | ✔️                 | ⛔           |       |
| arm32 Linux | ✔️       | ✔️         | ✔️              | ✔️                | ✔️            |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️             | ✔️            | ✔️            | This will be a headless build |
| aarch64 Mac | ✔️       | ✔️         |  ✔️             | ✔️                | ⛔           |       |

### JDK19.0.2
| Platform  | [jdk19 AQA](https://github.com/adoptium/aqa-tests/issues/4257) | jdk19 TCK | jdk19 published| jdk19 installers | jdk19 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️             | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️              | ✔️               | ⛔            |       |
| aarch64 Linux | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️             | ✔️                | ✔️             |       |
| s390x Linux   | ✔️     | ✔️         | ✔️             | ✔️                | ✔️             |       |
| x32 Windows | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| arm32 Linux | ✔️       | ✔️          | ✔️              | ✔️                | ✔️             |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |
| aarch64 Mac | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |

**Comment by breun** [comment]
According to the table above the 11.0.18 should have been published for aarch64 Mac, but https://adoptium.net/temurin/releases/?version=11 still shows 11.0.17+8 as the latest 11.x for aarch64 Mac. Is the table or the download page incorrect?

**Comment by zdtsw** [comment]
> According to the table above 11.0.18 should have been published for aarch64 Mac, but https://adoptium.net/temurin/releases/?version=11 still shows 11.0.17+8 as the latest 11.x for aarch64 Mac. Is the table or the download page incorrect?

No, the table says aarch64 Mac only passed AQA but not done TCK or started publish yet.
so the behavior of showing last Oct's version from website or API is correct.
we are working on the TCK part, once it is done we will publish it asap.

**Comment by breun** [comment]
Ah, my bad. I saw aarch64 under x64 Mac and probably read that as aarch64 Mac, but that was aarch64 Linux and aarch64 Mac is on the last row.

**Comment by smlambert** [comment]
re: https://github.com/adoptium/adoptium/issues/202#issuecomment-1402412338 - its close to ready, but limited on 2 aarch64 mac machines in the Temurin Compliance project means not as fast as we'd like.

**Comment by steelhead31** [comment]
Release completed.
