### ISSUE TITLE
Fix typos in release-checklist.md

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#216]
The following should be fixed in https://github.com/adoptium/adoptium/blob/main/.github/ISSUE_TEMPLATE/release-checklist.md

1. None Branched Repos -> Non-Branched Repos 
2. Disable Setup JCK_MUltinode -> Disable Setup_JCK_Multinode
3. ...Adoptium public retro & TC retroes -> Adoptium public retro & TC retro

**Comment by Ndacyayisenga-droid** [comment]
Hi @smlambert. Can I fix this?

**Comment by tellison** [comment]
@Ndacyayisenga-droid I have assigned it to you - so go ahead! Thank you ❤️
