### ISSUE TITLE
March 2023 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by steelhead31** [adoptium/adoptium#218]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).

✔️ results in these Tables means the activity has successfully completed.

⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.

⛔ means there is no build planned for that version/platform combination.

⏸️ means activity not yet started.

### JDK20.0.00+36
| Platform  | [jdk20 AQA](https://github.com/adoptium/aqa-tests/issues/4463) | jdk20 TCK | jdk20 published| jdk20 installers | jdk20 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️    |  ✔️        | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   |  ✔️        | ✔️             | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️               | ✔️                | ⛔            |       |
| aarch64 Linux | ✔️       |✔️         | ✔️             | ✔️                | ✔️             |       |
| ppcle64 Linux |✔️    |✔️           | ✔️              | ✔️                | ✔️             |       |
| s390x Linux   | ✔️ | :hourglass:          | ⏸️              | ⏸️                | ⏸️             |       |
| ppc64 AIX | ✔️         | :hourglass:          | ⏸️              | ⛔               | ⛔            |       |
| arm32 Linux | ✔️      | :hourglass:          | ⏸️              | ⏸️                | ⏸️             |       |
| x64 alpine-Linux | ✔️  | ✔️        | ✔️              | ✔️                | ✔️             | This will be a headless build |
| aarch64 Mac |✔️     | ✔️           | ✔️              | ✔️                | ⛔            |       |

**Comment by johanjanssen** [comment]
@smlambert thanks for your quick reply! Good to know, then I'll proceed with the release.

**Comment by MDoswaldSchiller** [comment]
Is there an ETA on the arm32 Linux version or any update on the progress of that particular platform? The state is set to 'actively working on' jdk20 TCK for two weeks now. Are there any problems with that version or does the TCK test take that long on arm32?

**Comment by tellison** [comment]
> Is there an ETA on the arm32 Linux version or any update on the progress of that particular platform? The state is set to 'actively working on' jdk20 TCK for two weeks now. Are there any problems with that version or does the TCK test take that long on arm32?

Hi @MDoswaldSchiller unfortunately there is no ETA for arm32 Linux JDK20 since it is not passing required tests to be declared release ready. The problematic area is part of Oracle's proprietary-licensed tests so we can't share them openly. There have been discussions with the OpenJDK project who are aware of the shortfall on this platform, and if/when things change while JDK20 is in service then we'll release it.

**Comment by MDoswaldSchiller** [comment]
@tellison Thank you for the updated. Let's hope this can be resolved.

**Comment by jiekang** [comment]
The TCK issue that Tim mentions applies to:

s390x Linux
arm32 Linux
ppc64 AIX

@tellison would it be alright to close this issue with the note that they will only be released if/when things change for JDK 20?

I can make that note.

**Comment by tellison** [comment]
@jiekang sure - thanks

**Comment by jiekang** [comment]
Closing the issue as March release work has been completed.

At this time of writing, Adoptium will not be releasing for the following platforms:

s390x Linux
arm32 Linux
ppc64 AIX

due to known issues with TCK for these platforms. If/when things change for JDK 20, we will release them.
