### ISSUE TITLE
General Retrospective for March 2023 Releases

### ISSUE THREAD

**Issue by steelhead31** [adoptium/adoptium#219]
**Summary**

A retrospective for all efforts surrounding the titular releases. 

All community members are welcome to contribute to the agenda via comments below.

This will be a virtual meeting after the release, with at least a week of notice in the #release Slack channel.

On the day of the meeting the agenda items will be iterated over, with a list of actions added in a comment at/near the end.

Invited: Everyone.

**Time, Date, and URL**

Time: 8:30am EST / 1:30pm UTC
Date: TBC - Proposed Apr 5th 2023

URL: https://eclipse.zoom.us/j/81872484707?pwd=dGl1QzcrTllWUkNWRUVGNzdYVUx4dz09
Meeting ID: 818 7248 4707
Passcode: 951478

**Details**

Retrospective Owner Tasks (in order):

- [ ] Post this issue's URL on the \#Release Slack channel around the start of the new release.
- [ ] Copy actions from the previous retrospective into this issue, while ignoring actions that are ticked or have issue links (i.e. clearly-completed actions).
- [ ] Wait until 90% of all builds have been released, with no clear signs of additional respins.
- [ ] Announce the retrospective Slack call's date + time on \#Release at least one full week in advance, and send out meeting invites.
- [ ] Host the slack call for the retrospective, including:
  - [ ] Iterating over the actions from the previous retrospective issue, ticking off completed items.
  - [ ] Iterate over the agenda, ensuring everything gets debated.
  - [ ] Create a clear list of actions at the end of the retrospective, including volunteer names.
- [ ] Create a new retrospective issue for the next release.
- [ ] Set yourself a calendar reminder so that you remember to commence step 1 (in the new issue) just before the next release.
- [ ] Close this issue.

**Comment by steelhead31** [comment]
Action: “Look like we noticed it is released” .. perhaps a column added to the public tracking issue to show the builds are in progress / completed .

**Comment by smlambert** [comment]
Prioritize this before the April release https://github.com/adoptium/aqa-test-tools/issues/649 as the release report as it is is very noisy and needs improvement.  Consider asking triagers to put only the table in the description of the triage issue, and individual comments for each of the platform details.

**Comment by smlambert** [comment]
When rerunning AQA tests in Grinders, encourage triagers to update the PARALLEL param to None, so that there is one less click to follow-up on test reruns.

**Comment by smlambert** [comment]
Trial the automatic rerun feature for Jenkins test jobs prior to April release to see if we may want to use it for April.

**Comment by smlambert** [comment]
We saw less issues with machines than in January, which was good.  

There are still some outstanding infra issues.  We still saw the issue where only 1 windows machine (test-azure-win2012r2-x64-1) seems to be setup with wix toolkit, so its the only machine where jdk_tools test target can pass (as reported in https://github.com/adoptium/infrastructure/issues/2885 and https://github.com/adoptium/infrastructure/issues/2310).

**Comment by smlambert** [comment]
Ensure it is easy to find the top-level release pipeline(s) that was triggered.  I often find it difficult to locate the Job ID that is the 'official' run.  We could link to it in the summary issue https://github.com/adoptium/adoptium/issues/218 for convenience.

**Comment by adamfarley** [comment]
The actions from this retro have been copied into the [July 2023 General Retro issue](https://github.com/adoptium/adoptium/issues/240#issuecomment-1662060816). 

@steelhead31 - Please close, thank you.
