### ISSUE TITLE
April 2023 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/adoptium#224]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).

✔️ results in these Tables means the activity has successfully completed.

⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.

⛔ means there is no build planned for that version/platform combination.

⏸️ means activity not yet started.

### JDK8u372-b07
| Platform  |[ jdk8 AQA](https://github.com/adoptium/aqa-tests/issues/4518)  | jdk8 TCK  | jdk8 published | jdk8 installers  | jdk8 images   | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️    | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️            |       |
| **x64 Mac** | ✔️ | ✔️         | ✔️              | ✔️                | ⛔            |       |
| aarch64 Linux | ✔️     | ✔️         | ✔️               | ✔️                | ✔️             |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppc64 AIX | ✔️         | ✔️         | ✔️              | ⛔               | ⛔            |       |
| x32 Windows | ✔️       | ✔️         | ✔️              | ✔️               | ⛔             |       |
| arm32 Linux | ✔️       | ✔️         | ✔️              | ✔️                | ✔️             |    Tag available Apr 26th     |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |
| sparcv9 solaris | ✔️   | ✔️         | ✔️              | ⛔               | ⛔            |       |
| x86 solaris | ✔️       | ✔️         | ✔️              | ⛔               | ⛔            |       |

### JDK11.0.19+7
| Platform | [jdk11 AQA](https://github.com/adoptium/aqa-tests/issues/4517) | jdk11 TCK  | jdk11 published| jdk11 installers | jdk11 images  | Notes |
| -----    | -----     | -----      | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️ | ✔️        | ✔️            | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| aarch64 Linux | ✔️     | ✔️         |  ✔️              | ✔️                | ✔️             |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| s390x Linux   | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppc64 AIX | ✔️        | ✔️         | ✔️              | ⛔               | ⛔            |       |
| x32 Windows | ✔️      | ✔️         | ✔️              | ✔️                | ⛔            |       |
| arm32 Linux | ✔️      | ✔️         | ✔️              | ✔️                | ✔️             |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |
| aarch64 Mac |   ✔️     | ✔️         |  ✔️           | ✔️                | ⛔            |       |

### JDK17.0.7+7
| Platforms | [jdk17 AQA](https://github.com/adoptium/aqa-tests/issues/4515) | jdk17 TCK | jdk17 published| jdk17 installers | jdk17 images | Notes |
| -----     | -----     | -----     | -----          | -----            | -----        | ----- |
| **x64 Linux** | ✔️     | ✔️  | ✔️              | ✔️                | ✔️            |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️            | ✔️                 | ✔️            |       |
| **x64 Mac** | ✔️       | ✔️         |   ✔️            | ✔️                | ⛔           |       |
| aarch64 Linux | ✔️   | ✔️         | ✔️              | ✔️                | ✔️            |       |
| ppcle64 Linux | ✔️     | ✔️         | [✔️](https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/6379/)              | ✔️                | ✔️            |       |
| s390x Linux   | ✔️     | ✔️         | ✔️              | ✔️                | ✔️            |       |
| ppc64 AIX | ✔️         | ✔️         | ✔️              | ⛔               | ⛔           |       |
| x32 Windows | ✔️       | ✔️         | ✔️              | ✔️                | ⛔           |       |
| arm32 Linux | ✔️      | ✔️         | ✔️              | ✔️                | ✔️            |     |
| x64 alpine-Linux |  ✔️  | ✔️         | ✔️              | ✔️                | ✔️            | This will be a headless build |
| aarch64 Mac | ✔️       | ✔️         | ✔️              | ✔️                | ⛔           |       |

### JDK20.0.1+9
| Platform  | [jdk20 AQA](https://github.com/adoptium/aqa-tests/issues/4524) | jdk20 TCK | jdk20 published| jdk20 installers | jdk20 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     |    ✔️      | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️               | ✔️                | ⛔            |       |
| aarch64 Linux |  ✔️  | ✔️       | ✔️             | ✔️                | ✔️             |       |
| ppcle64 Linux | ✔️     | ⛔         | ⛔              | ⛔                | ⛔             |   Not available    |
| s390x Linux   | ⛔     | ⛔         | ⛔              | ⛔                | ⛔             |   Not available    |
| ppc64 AIX | ⛔         | ⛔         | ⛔              | ⛔               | ⛔            |   Not available     |
| x32 Windows | ⛔     | ⛔         | ⛔              | ⛔                | ⛔            |   Not available     |
| arm32 Linux | ⛔       | ⛔         | ⛔              | ⛔                | ⛔             |    Not available    |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |
| aarch64 Mac | ✔️       | ✔️          | ✔️               | ✔️                | ⛔            |       |

**Comment by smlambert** [comment]
Believe we can strikeout s390x Linux, ppc64 AIX, and arm32 Linux from the JDK20 table, as currently we will not plan to release them and want to set expectations for what to expect out of this release.

**Comment by zdtsw** [comment]
Impressive progress! 
Adoptium rock :rocket:  :heart:

**Comment by namrata-ibm** [comment]
@andrew-m-leonard , Thank you for sharing these updates publicly. As per the table, JDK20 is not released for s390x.
We were waiting for this release as it is needed for Apache ActiveMQ.
Reference: https://issues.apache.org/jira/browse/INFRA-24430?focusedCommentId=17708725&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17708725
https://github.com/apache/activemq/blob/main/Jenkinsfile#L71-L79
Can we please consider adding s390x?

**Comment by iron-paradise** [comment]
Indeed! Adoptium rocks 🚀
Can you tell me, when  JDK-jre of 11.0.18 x32 will be released approximately?

**Comment by andrew-m-leonard** [comment]
> Indeed! Adoptium rocks 🚀 Can you tell me, when JDK-jre of 11.0.18 x32 will be released approximately?

@iron-paradise Presume you mean Win32 11.0.19 ? hopefully later today

**Comment by iron-paradise** [comment]
Oh yes, you're right.   11.0.19 x32
Thanks man!

**Comment by Vishnumr70** [comment]
What about win32 for 8u372 JDK_JRE? will it get released today?

**Comment by jiekang** [comment]
> What about win32 for 8u372 JDK_JRE? will it get released today?

The zip for JDK8 on Win32 has been released now. Thanks for your patience!

**Comment by jiekang** [comment]
> Oh yes, you're right. 11.0.19 x32 Thanks man!

The zip for JDK 11 on Win32 has also been released!

**Comment by andrew-m-leonard** [comment]
> @andrew-m-leonard , Thank you for sharing these updates publicly. As per the table, JDK20 is not released for s390x. We were waiting for this release as it is needed for Apache ActiveMQ. Reference: https://issues.apache.org/jira/browse/INFRA-24430?focusedCommentId=17708725&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17708725 https://github.com/apache/activemq/blob/main/Jenkinsfile#L71-L79 Can we please consider adding s390x?

Hi @namrata-ibm , so for several of the jdk-20 architectures (win32, pLinux, s390xLinux, AIX, arm32) there are upstream support issues that mean it currently does not pass all the necessary TCK tests, and as such we cannot publish them. Upstream contributors are working on fixes for these, but we don't yet know when they will be available.

**Comment by harridu** [comment]
I wonder for when can we hope for the temurin JDK8 Debian packages? cgroupv2 awareness is the most important feature here.

Thank you in advance

**Comment by qeepcologne** [comment]
temurin-20-jre is older then temurin-20-jdk in repos (both apt and yum repos), this is only the case for 20 why?
direct download for the same package is available.

`
apt list|grep temurin
temurin-11-jdk/jammy 11.0.19.0.0+7 amd64
temurin-11-jre/jammy 11.0.19.0.0+7-1 amd64
temurin-17-jdk/jammy,now 17.0.7.0.0+7 amd64 [installed]
temurin-17-jre/jammy 17.0.7+7 amd64
temurin-18-jdk/jammy 18.0.2.1+1 amd64
temurin-19-jdk/jammy 19.0.2.0.0+7 amd64
temurin-19-jre/jammy 19.0.2.0.0+7-1 amd64
temurin-20-jdk/jammy,now 20.0.1.0.0+9 amd64 [installed]
temurin-20-jre/jammy 20.0.0.0.0+36 amd64
temurin-8-jdk/jammy,now 8.0.362.0.0+9-1 amd64 [installed]
temurin-8-jre/jammy 8.0.362.0.0.9 amd64
`

`
dnf list|grep temurin
temurin-20-jre.x86_64                                                                    20.0.0.0.0.36-1                          @Adoptium    
temurin-11-jdk.x86_64                                                                    11.0.19.0.0.7-1                          Adoptium     
temurin-11-jre.x86_64                                                                    11.0.19.0.0.7-1                          Adoptium     
temurin-17-jdk.x86_64                                                                    17.0.7.0.0.7-1                           Adoptium     
temurin-17-jre.x86_64                                                                    17.0.7.0.0.7-1                           Adoptium     
temurin-18-jdk.x86_64                                                                    18.0.2.1.0.1-1                           Adoptium     
temurin-19-jdk.x86_64                                                                    19.0.2.0.0.7-2                           Adoptium     
temurin-19-jre.x86_64                                                                    19.0.2.0.0.7-3                           Adoptium     
temurin-20-jdk.x86_64                                                                    20.0.1.0.0.9-1                           Adoptium     
temurin-8-jdk.x86_64                                                                     8.0.362.0.0.9-2                          Adoptium     
temurin-8-jre.x86_64                                                                     8.0.362.0.0.9-3                          Adoptium  
`

**Comment by karianna** [comment]
> I wonder for when can we hope for the temurin JDK8 Debian packages? cgroupv2 awareness is the most important feature here.
> 
> Thank you in advance

Inmstallers are 

> temurin-20-jre is older (20.0.0 VS 20.0.1) then temurin-20-jdk in repos (both apt and yum repos), this is only the case for 20 why? direct download for the same package (jre 20.0.1) is available. (tested on linux amd64 jammy and kinetic and el9, btw there is kinetic but no lunar repo)
> 
> ```
> apt list|grep temurin
> temurin-11-jdk/jammy 11.0.19.0.0+7 amd64
> temurin-11-jre/jammy 11.0.19.0.0+7-1 amd64
> temurin-17-jdk/jammy,now 17.0.7.0.0+7 amd64 [installed]
> temurin-17-jre/jammy 17.0.7+7 amd64
> temurin-18-jdk/jammy 18.0.2.1+1 amd64
> temurin-19-jdk/jammy 19.0.2.0.0+7 amd64
> temurin-19-jre/jammy 19.0.2.0.0+7-1 amd64
> temurin-20-jdk/jammy,now 20.0.1.0.0+9 amd64 [installed]
> temurin-20-jre/jammy 20.0.0.0.0+36 amd64
> temurin-8-jdk/jammy,now 8.0.362.0.0+9-1 amd64 [installed]
> temurin-8-jre/jammy 8.0.362.0.0.9 amd64
> ```
> 
> ```
> dnf list|grep temurin
> temurin-20-jre.x86_64                                                                    20.0.0.0.0.36-1                          @Adoptium    
> temurin-11-jdk.x86_64                                                                    11.0.19.0.0.7-1                          Adoptium     
> temurin-11-jre.x86_64                                                                    11.0.19.0.0.7-1                          Adoptium     
> temurin-17-jdk.x86_64                                                                    17.0.7.0.0.7-1                           Adoptium     
> temurin-17-jre.x86_64                                                                    17.0.7.0.0.7-1                           Adoptium     
> temurin-18-jdk.x86_64                                                                    18.0.2.1.0.1-1                           Adoptium     
> temurin-19-jdk.x86_64                                                                    19.0.2.0.0.7-2                           Adoptium     
> temurin-19-jre.x86_64                                                                    19.0.2.0.0.7-3                           Adoptium     
> temurin-20-jdk.x86_64                                                                    20.0.1.0.0.9-1                           Adoptium     
> temurin-8-jdk.x86_64                                                                     8.0.362.0.0.9-2                          Adoptium     
> temurin-8-jre.x86_64                                                                     8.0.362.0.0.9-3                          Adoptium  
> ```

Hi there, sorry it's not clear what bug you are reporting here?

**Comment by qeepcologne** [comment]
> Hi there, sorry it's not clear what bug you are reporting here?

I just telling that temurin-20-jre update 20.0.0 -> 20.0.1 is missing in apt+yum repos.

**Comment by karianna** [comment]
Ah OK< yes that's because they have not been released yet.

**Comment by andrew-m-leonard** [comment]
All done, thank you @steelhead31
