### ISSUE TITLE
Marketplace: Request to rotate key for IBM Semeru Runtimes

### ISSUE THREAD

**Issue by AdamBrousseau** [adoptium/adoptium#234]
~Currently, the marketplace API verifies vendor binaries using the public key they have supplied. I am requesting that a change is made to allow different releases to be signed by different keys. It is common practice to rotate keys from time to time. IBM Semeru has rotated keys. We need to support all existing releases using the old key as well as all releases going forward (until the next rotation), using the new key.~

~Impact: We cannot publish the April CPU release to the Marketplace until this is supported.~

We (IBM Semeru Runtimes) have rotated our key used to sign our binaries and therefore also our [Marketplace json](https://github.com/ibmruntimes/Semeru-Runtimes/tree/master/adoptium/marketplace/json). The new keys can be found on our [Verification Page](https://www.ibm.com/support/pages/semeru-runtimes-verification/) at the bottom (20 May 2023).
Direct link: https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/certificates/20230520/ibm-semeru-public-20230520.pem
Public key:
```
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0f/8LoePKgsHKx5xq1Eb
HqhBu24py2MW+RuH6TkHfbR/+3SyAolOx8qBWzJhoj0tQT+7CfoJ/Cm9XVOSDPWa
QQDuC5TCwpu4NqsnPm5FakCmHs0wWn76YAyYWfnu2+D9b2JMdRMfV6Q3du0v6OGl
Cxp5j40PUjLU96pWX9m+fXJTfcd9GFVzNqqEUa6RQJIZKBGECG6GNOuOE2ra1beQ
jQEIhAnWQZ/3NM+aKdG+NiVk3l7wJQ/xRDloYpUso0nmO3PADbz/at1K9JNfMAQj
7eO74V1n+f4fYGwcTbb9KfrylTVSkPAiXTx5spVnbR8lkLDZMRcBmeBFM4T+mMcV
dyUMMuXjZxwfDLdV2/Cxoam0XcUgRNHZR3kCM8wJJ3sepoQLSslMSf/tZsXFNcPp
FomEga1sO9XiBBCoSFhrM6lvSTQ9xTydLTZbk5ZDCUpW6CuOe//KygfzWOaoKgy0
2sRemUo2VCO64G9RXBhH1dE3t5dHDhHVHY4OHzNg163lWXeeCQXKdmxFHXEDpqJV
CKOMBUzY0GsBegKT5m+6s6uUlexGYwrqeCYOKxP0iYbTlVDOASGJENkizqOHSKgH
RcDqx6IF1ZtZ3lCYDCeVEuLaZctfAkSQrfVWxk5ohc0JMTIACl4YvUBbrxE9V3OR
lAs5DoKF0qB/yL3XlJfHlCcCAwEAAQ==
-----END PUBLIC KEY-----
```

Please update our key on Adoptium side so the API will pickup our new content.
Our latest content will be merged shortly via https://github.com/ibmruntimes/Semeru-Runtimes/pull/53

**Comment by tellison** [comment]
Adoptium doesn't maintain the keys for the distributions (Semeru), only the publishers' (IBM) metadata (json files) used to provide the listing in the marketplace.

If you have rotated the keys for the marketplace data please provide the new public key, and resign all the marketplace metadata json files - we will co-ordinate the key update and your publication of the resigned data.

**Comment by AdamBrousseau** [comment]
My misunderstanding. I have updated the title and description with the right request.

**Comment by tellison** [comment]
Linking this as related to original request https://github.com/adoptium/adoptium/issues/150
