### ISSUE TITLE
Release Champion: Process and Role Revision

### ISSUE THREAD

**Issue by adamfarley** [adoptium/adoptium#235]
**Summary**

The release process has grown and become a lot for one person. Too much? Discuss.

**Points for discussion**

- Should we break down the process to become more modular?
  - Enables the work to be shared between multiple people.
  - How would the process be subdivided?
  - Would there be a singular release champion with tasks/areas delegated and managed by them, or a distributed release council?
- RC training discussion.
- How is July going to look?

**Slack announcement**

https://adoptium.slack.com/archives/CLCFNV2JG/p1686564785041689

**Conclusion/Actions**

None yet.

**Comment by adamfarley** [comment]
Brain dump: By "modular" I mean "Chunks of the overall process that can safely be operated by separate people, possibly concurrently".

Maybe the people executing these "chunks" would be coordinated by the Release Champion, or perhaps they'd form a sort of "council" of Release Champions ("JCK Champion", "Test Champion", etc etc) that meet regularly.

An agile approach might be to design the modules to be worked concurrently. As in "each individual module can be operated by multiple people at the same time", allowing for maximum throughput on tricky modules, or seamless redundancy in case of sudden absences.

Food for thought.

**Comment by andrew-m-leonard** [comment]
Thoughts:
- "Release Champion" => "Release ChampionS" : 2 people
- Breakdown "chunks", rest done by "Team":
    - "dry-runs"
    - Build mirror, and triggers
    - JCK Issue templates, and triage "JCK jobs" since mostly Green
    - dockerhub Containers updates
    - JFrog Installers updates

**Comment by adamfarley** [comment]
Meeting minutes:

- Attendees: Adam Farley, Andrew Leonard, Scott Fryer, Stewart Addison, Scott Fryer.

- Installers process could be made more smoothly, as it currently requires 40-ish file changes in 4 PRs.
  - 2 or 3 things specifically that are problematic.
  - Work is error prone via C+Ping checksums.
  - Installer jobs are clunky but smooth enough.
  - If jobs go wrong, they cannot just be rerun. They need to be idempotent.
- Overall process is fairly quick if nothing goes wrong.
- Scott really Helped Andrew in the April release by jumping on the jFrog issue.
- Andrew found it helpful when he chatted with people about the issues encountered in a daily basis.
- Stewart feels the process is easiest if only one person is doing it.
- Scott found it valuable to RC two releases back-to-back.
- "Break" arm if needed.
-

**Comment by adamfarley** [comment]
Potential actions:
- Make installer process automated and idempotent.
