### ISSUE TITLE
July 2023 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by sxa** [adoptium/adoptium#239]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX and aarch64 Linux/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).  We retrospectively measure and track how well we do against these targets in these [Adoptium Release Scorecards](https://github.com/adoptium/adoptium/wiki/Adoptium-Release-Scorecards) in order to continuously assess and improve.

✔️ results in these Tables means the activity has successfully completed.

⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.

⛔ means there is no build planned for that version/platform combination.

⏸️ means activity not yet started.

### JDK8u382-b05
| Platform  | [jdk8 AQA](https://github.com/adoptium/aqa-tests/issues/4679)  | jdk8 TCK  | jdk8 published | jdk8 installers  | jdk8 images   | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️              | ✔️               |  ✔️           |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| **aarch64 Linux** | ✔️     | ✔️        | ✔️              | ✔️                | ✔️             |       |
| ppcle64 Linux | ✔️    | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppc64 AIX | ✔️         | ✔️         | ✔️              | ⛔               | ⛔            |       |
| x32 Windows | ✔️       | ✔️         | ✔️              | ⛔               | ⛔            |       |
| arm32 Linux | ✔️       | ✔️         | ✔️              | ✔️                | ✔️             |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |
| sparcv9 solaris | ✔️   | ✔️         | ✔️              | ⛔               | ⛔            |       |
| x86 solaris | ✔️      | ✔️         | ✔️              | ⛔               | ⛔            |       |

### JDK11.0.20+8
| Platform | [jdk11 AQA](https://github.com/adoptium/aqa-tests/issues/4678) | jdk11 TCK  | jdk11 published| jdk11 installers | jdk11 images  | Notes |
| -----    | -----     | -----      | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️              | ✔️               | ⛔            |       |
| **aarch64 Linux** | ✔️     | ✔️        | ✔️              | ✔️                | ✔️             |       |
| **aarch64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️              | ✔️               | ✔️             |       |
| s390x Linux   | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppc64 AIX | ⏸️         | ⏸️         | ⏸️              | ⛔               | ⛔            |       |
| x32 Windows | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| arm32 Linux | ✔️       | ✔️         | ✔️              | ✔️                | ✔️             |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |

### JDK17.0.8+7
| Platforms | [jdk17 AQA](https://github.com/adoptium/aqa-tests/issues/4677) | jdk17 TCK | jdk17 published| jdk17 installers | jdk17 images | Notes |
| -----     | -----     | -----     | -----          | -----            | -----        | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️            |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️            |       |
| **x64 Mac** | ✔️      | ✔️       | ✔️              | ✔️               | ⛔           |       |
| **aarch64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️            |       |
| **aarch64 Mac** | ✔️       | ✔️        | ✔️              | ✔️                | ⛔           |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️              | ✔️               | ✔️            |       |
| s390x Linux   | ✔️     | ✔️         | ✔️             | ✔️                | ✔️            |       |
| ppc64 AIX | ⏸️         | ⏸️         | ⏸️              | ⛔               | ⛔           |       |
| x32 Windows | ✔️       | ✔️         | ✔️              | ✔️                | ⛔           |       |
| arm32 Linux | ✔️       | ✔️         | ✔️              | ✔️                | ✔️            |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️            | ✔️               | ✔️            | This will be a headless build |

### JDK20.0.2+9
| Platform  | [jdk20 AQA](https://github.com/adoptium/aqa-tests/issues/4680) | jdk20 TCK | jdk20 published| jdk20 installers | jdk20 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️             | ✔️                | ⛔            |       |
| **aarch64 Linux** | ✔️     | ✔️         | ✔️            | ✔️                 | ✔️             |       |
| **aarch64 Mac** | ✔️       | ✔️        | ✔️              | ✔️                | ⛔           |       |
| ppcle64 Linux | ⛔     | ⛔         | ⛔              | ⛔                | ⛔             |   Not in plan    |
| s390x Linux   | ⛔     | ⛔         | ⛔              | ⛔                | ⛔             |    Not in plan   |
| ppc64 AIX | ⛔         | ⛔        | ⛔              | ⛔               | ⛔            |  Not in plan     |
| x32 Windows | ⛔      | ⛔         | ⛔              | ⛔                | ⛔            |  Not in plan     |
| arm32 Linux | ⛔       | ⛔         | ⛔              | ⛔                | ⛔             |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              |  ✔️                | ✔️             | This will be a headless build |

**Comment by Vishnumr70** [comment]
When will 32 bit jre 8 be relasing?

**Comment by sxa** [comment]
> When will 32 bit jre 8 be relasing?

We are working as fast as we can and we cannot provide specific ETAs other than "When it's fully tested". We have already released 8u382 on two Linux platforms, the rest will follow. The code for JDK8u was confirmed much later than the other versions (Friday) so it will take longer to complete the testing on that version for all platforms.

**Comment by gowthamv** [comment]
When will JDK11.0.20+8 release notes published?

**Comment by tellison** [comment]
> When will release notes of JDK11.0.20+8 available?

The plan is to [publish them here](https://adoptium.net/temurin/release-notes/?version=jdk-11.0.20+8) by the end of this week.

**Comment by adamfarley** [comment]
Installer Dry runs:

JDK8: Pending.

JDK11: https://ci.adoptium.net/job/adoptium-packages-linux-pipeline_new/435/

JDK17: https://ci.adoptium.net/job/adoptium-packages-linux-pipeline_new/436/

JDK20 x64: https://ci.adoptium.net/job/adoptium-packages-linux-pipeline_new/438/
JDK20 aarch64: https://ci.adoptium.net/job/adoptium-packages-linux-pipeline_new/439/

**Comment by dave-voltdb** [comment]
A clarification, please.  What should I expect for 'installers'?  For example, will there be .deb files for Ubuntu, and if so, what versions of Ubuntu?   Or is that not within your remit?

(Not asking for dates, just for description of what it'll be).

Thanks.

**Comment by karianna** [comment]
@dave-voltdb see https://adoptium.net/en-GB/supported-platforms/ - installers are still being worked on

**Comment by steelhead31** [comment]
This release is now complete, with the exceptions detailed in this blog post..

https://adoptium.net/blog/2023/08/eclipse-temurin-8u382-11020-1708-and-2002-available/
