### ISSUE TITLE
General Retrospective for July 2023 Releases

### ISSUE THREAD

**Issue by adamfarley** [adoptium/adoptium#240]
**Summary**

A retrospective for all efforts surrounding the titular releases. 

All community members are welcome to contribute to the agenda via comments below.

This will be a virtual meeting after the release, with at least a week of notice in the #release Slack channel.

On the day of the meeting the agenda items will be iterated over, with a list of actions added in a comment at/near the end.

Invited: Everyone.

**Time, Date, and URL**

Time: 13:30 GMT, 08:30 EDT
Date: 2023/08/02

URL: https://eclipse.zoom.us/j/81872484707?pwd=dGl1QzcrTllWUkNWRUVGNzdYVUx4dz09

**Details**

Retrospective Owner Tasks (in order):

- [x] Post this issue's URL on the \#Release Slack channel around the start of the new release.
- [x] Copy actions from the previous retrospective into this issue, while ignoring actions that are ticked or have issue links (i.e. clearly-completed actions).
- [x] Wait until 90% of all builds have been released, with no clear signs of additional respins.
- [x] Announce the retrospective Slack call's date + time on \#Release at least one full week in advance, and send out meeting invites.
- [x] Host the slack call for the retrospective, including:
  - [x] Iterating over the actions from the previous retrospective issue, ticking off completed items.
  - [x] Iterate over the agenda, ensuring everything gets debated.
  - [x] Create a clear list of actions at the end of the retrospective, including volunteer names.
- [x] Create a new retrospective issue for the next release.
- [x] Set yourself a calendar reminder so that you remember to commence step 1 (in the new issue) just before the next release.
- [x] Close this issue.

**Actions**
[Actions from previous retrospective](https://github.com/adoptium/adoptium/issues/240#issuecomment-1662060816)
[Actions from this retrospective](https://github.com/adoptium/adoptium/issues/240#issuecomment-1662062556)

**Comment by adamfarley** [comment]
I noticed the new JDK21 ea-tag-triggered pipelines do not run all of the tests that used to be present in the JDK21 weekly pipelines.

The missing test targets are:
- special.functional
- extended.openjdk
- extended.perf

After the release, can we add these tests to the JDK21 ea-tag-triggered pipelines?

**Comment by adamfarley** [comment]
ci.adoptium.net logs me out several times a day. Is it possible to extend the login period? 12 hours or more would be great, but any increase would help.

**Comment by adamfarley** [comment]
The release checklist template needs to be updated to consolidate the following checks, as the same action handles both.

- Disable standard & evaluation nightly builds completely
- Disable standard & evaluation weekend builds completely

**Comment by adamfarley** [comment]
The [build-pipeline-generator](https://ci.adoptium.net/job/build-scripts/job/utils/job/build-pipeline-generator/) jenkins job currently disables pipeline scheduling by setting the various nightly/weekly pipelines to only build on February 31st.

I don't see why we don't leave the values as-is and simply disable the tick-box.

**Comment by adamfarley** [comment]
Either I lack permissions to see "release-build-pipeline-generator", or it got renamed to "release-pipeline-generator".

Being discussed on Slack [here](https://adoptium.slack.com/archives/CLCFNV2JG/p1689608972729559).

If it turns out the job got renamed, we'll need to update the release checklist accordingly.

**Comment by sxa** [comment]
Dry run builds prevented the [JDK8 mirror](https://ci.adoptium.net/view/git-mirrors/job/git-mirrors/job/adoptium/job/git-skara-jdk8u/) from working properly so we didn't get `_adopt` tags. Unclear why - we should try to understand for next time.

```
To github.com:adoptium/jdk8u.git
 ! [rejected]              jdk8u382-dryrun-ga -> jdk8u382-dryrun-ga (already exists)
error: failed to push some refs to 'git@github.com:adoptium/jdk8u.git'
hint: Updates were rejected because the tag already exists in the remote.
```

**Comment by sxa** [comment]
Look at recommendations for expressions for filenames in RELEASING.md vs the examples shown in the job (Particularly in terms of the sources tarball)

**Comment by adamfarley** [comment]
> Look at recommendations for expressions for filenames in RELEASING.md vs the examples shown in the job (Particularly in terms of the sources tarball and inclusion of testimage files)

Given that it's a long string that easy to get wrong, I'd consider automating the strings. Maybe internalising the patterns and replacing that field with a drop-down menu to pick the platform?

**Comment by adamfarley** [comment]
Releasing JDK8 on Aarch32 had a number of challenges.

- testenv_arm32.properties was not updated prior to the release.
- The following aarch32-jdk8u tags caused confusion. Do we really need to keep all of these?
  - jdk8u382-ga
  - jdk8u382-b05_adopt
  - jdk8u382-b05-aarch32-20230719_adopt
  - jdk8u382-ga-aarch32-20230719
  - jdk8u382-b05-aarch32-20230719
  - jdk8u382-b05
- When testenv had the JDK8 branch set to jdk8u382-b05-aarch32-20230719 and the scmReference for the release job was set to jdk8u382-b05_adopt, the release job did not allow the release to proceed as they did not "match".
  - Note that the problem isn't the _adopt bit. Changing the scmReference to jdk8u382-b05-aarch32-20230719_adopt worked just fine.

**Comment by adamfarley** [comment]
The error message [here](https://ci.adoptium.net/job/build-scripts/job/release-openjdk8-pipeline/24/console) has a typo in "branch".

```
[ERROR] scmReference does not match with any JDK brnach in testenv_arm32.properties in aqa-tests release branch. Please update aqa-tests v0.9.8-release release branch. Set the current build result to FAILURE!
```

**Comment by smlambert** [comment]
Update release notes job link in checklist from
https://ci.adoptium.net/job/create_release_notes/
to
https://ci.adoptium.net/job/build-scripts/job/release/job/create_release_notes/

**Comment by smlambert** [comment]
Update https://adoptium.net/release_notes.html link in checklist as that page does not seem to exist (or need to find it on the website).

**Comment by adamfarley** [comment]
Does anyone know why the SHA256 for the tarballs is stored in its own file, when the exact same sha can be found in the json?

We have a lot of artifacts with every build, and I'm curious why we add 50% more just to duplicate data that's already available.

**Comment by adamfarley** [comment]
Looks like an installer Git check (possibly more than 1, looking now) was broken 2 months ago. It could never have compiled in its current state, and I think we should find these things out prior to release week.

Advising that we run all the Installer repo's Git checks regularly, or at least as part of the pre-release work.

**Comment by adamfarley** [comment]
The Slack messages produced by using the "/merge" command (used to request approval to merge PRs into release-frozen repos) can quickly fill the \#release channel due to the bulky previews.

Can we suppress the issue preview?

**Comment by adamfarley** [comment]
The Installer repo appears to be slow, which can be inconvenient. Not sure if all repos are slow right now, and I'm just more aware of it in Installer because I'm writing PRs for that repo, or if it's Installer-specific.

Example:
0 Mins: I push a second commit to an existing PR.
4 Mins: Ctrl-F5 refreshes the PR's web page, but the page does not show the 2nd PR yet.
5 Mins: The PR now shows the second commit.
6 Mins: The branch's checks finish running on my branch as it was **9 mins ago**, telling me that it failed due to the error my 2nd commit fixed.

**Comment by adamfarley** [comment]
The ci server's job history limits seem excessive, and this has resulted in output being lost and files being deleted before both were needed. Would it be possible (in regard to text (limited), not files) to:

- Purchase more space
- Increase the job history limit and compensate by storing *all* files somewhere with cheaper storage. No more jenkins-stored artifacts.
- Something else?

**Comment by adamfarley** [comment]
**Actions from this retrospective**

- [ ] Person: To do a thing. 
  - When complete, or an issue is raised, please tick the above box, and replace this sub-bullet with relevant links.

**Comment by smlambert** [comment]
Creating a workflow in installers repo to automate the creation of the PR to update the spec file, and watch for when tarballs show up in the API, in a step towards full automation the publishing of Linux installers.

**Comment by adamfarley** [comment]
A few notes on the JDK21 nightly builds during the release:

- These builds continued during the release. We should make sure they are cancelled during the next release, so as to not use up valuable machine time.
- These builds appear to be running nightly. This is wrong, as they *should* only be triggered when a new "ea" tag is detected. Perhaps the ea-tag-detection code is having issues? @sxa - What do you think?

P.S. I'm holding off on adding the weekly tests (mentioned in my action [here](https://github.com/adoptium/adoptium/issues/240#issuecomment-1662062556)) until these ea builds are not running every day.

**Comment by sxa** [comment]
Consider creating the status issues in temurin-build instead of the adoptium repository to make it easier for all temurin committees who may be involved in releases to be able to update them.

**Comment by adamfarley** [comment]
New general retrospective issue raised [here](https://github.com/adoptium/adoptium/issues/249).
