### ISSUE TITLE
General Retrospective for September/October 2023 Releases

### ISSUE THREAD

**Issue by adamfarley** [adoptium/adoptium#249]
**Summary**

A retrospective for all efforts surrounding the titular releases. 

All community members are welcome to contribute to the agenda via comments below.

This will be a virtual meeting after the release, with at least a week of notice in the #release Slack channel.

On the day of the meeting we'll review the agenda and add a list of actions at the end.

Invited: Everyone.

**Time, Date, and URL**

Time: TBD
Date: TBD
URL: TBD

**Details**

Retrospective Owner Tasks (in order):

- [x] Post retro URL in \#Release around the start of the new release.
- [ ] Copy actions from previous retrospectives into this issue, ignoring anything ticked.
  - Include owner names.
- [ ] Wait until most builds are released, with no clear signs of additional respins.
- [ ] Announce the retrospective's date + time on \#Release a week before.
- [ ] Host the retrospective:
  - [ ] Tick completed actions from last retrospective/s.
  - [ ] Go through the agenda.
  - [ ] Create a tickable list of actions with owner names.
- [ ] Create a new retrospective issue for the next release.
- [ ] Set a calendar reminder so you remember to do step 1 before the next release.
- [ ] Close this issue.

**Comment by andrew-m-leonard** [comment]
jdk-21 mac x64 installers failed with an unknown notarize failure: https://github.com/adoptium/installer/issues/737
So mac x64 had to be re-run, however the unsigned installer artifacts were still stored in the top level pipeline, which could lead to confusion especially if the error had not been seen...
Maybe ensure the artifacts are not always stored in the top-level on this sort of failure?
Although hard to distinguish between just a test job failing, and the installer failing...?

**Comment by adamfarley** [comment]
Should we do a community-wide release champion process overview? There seems to be a lack of awareness surrounding the general shape of the process.

**Comment by adamfarley** [comment]
Closing this because retrospectives should now be created and stored inside https://github.com/adoptium/temurin.

The retrospective notes mentioned above have been copied across.
