### ISSUE TITLE
Can x86-simd-sort be backported to Temurin OpenJDK 21 LTS?

### ISSUE THREAD

**Issue by volkert-fastned** [adoptium/adoptium#251]
Intel's [x86-simd-sort](https://github.com/intel/x86-simd-sort) library was recently [merged into OpenJDK upstream](https://github.com/openjdk/jdk/pull/14227#issuecomment-1751356061). Unfortunately, this happened after the recent release of OpenJDK 21 LTS, and the next LTS is quite some time away.

In the meantime, the performance improvements of x86-simd-sort are apparently [very compelling](https://www.phoronix.com/news/Intel-x86-simd-sort-3.0). So much so that it would seem worth it to backport this to OpenJDK 21 LTS.

Perhaps Adoptium could do this for its Temurin builds? Or would this really have to done upstream?

Thank you for considering this.

**Comment by tellison** [comment]
Hello @volkert-fastned thank you for the question.

Indeed, it is good to see this enhancement made to OpenJDK code, and I appreciate that it would be desirable to have this in the OpenJDK 21 LTS code stream.

As you imply, the best place to raise this request is in the [OpenJDK updates project](https://openjdk.org/projects/jdk-updates/). Your request will then be seen by everyone who can evaluate the options and advise on a way forward for consideration in an OpenJDK 21 update release.

As a general rule, Temurin tries to keep as close to the upstream codebase as possible. Features and fixes that apply to all OpenJDK distributions are best applied there to the benefit of everyone, and to ensure that code and behavior on other publishers can run unmodified on Temurin.

**Comment by volkert-fastned** [comment]
Makes perfect sense. Thanks for the quick response!
