### ISSUE TITLE
Update the "Eclipse Adoptium Interim Build Labeling Requirements" text on the governance page, website, and other documentation if needed.

### ISSUE THREAD

**Issue by CarmenDelgadoEclipse** [adoptium/adoptium#252]
As shared with the SC and PMC, we have available the v2.0 of the  "Eclipse Adoptium Interim Build Labeling Requirements", our suggested change to be done:

- [x] Create a new page for Adoptium governance documentation https://projects.eclipse.org/projects/adoptium/governance named as "previous-versions" e.g. https://projects.eclipse.org/projects/adoptium/governance/previous-versions. Wayne from EMO will take care of this and let us know.
- [x] Have a link to the new "v 1.0" page, as it will be needed to publish the latest version.

- [x] Move the text below the title "Eclipse Adoptium Interim Build Labeling Requirements: ....
The Eclipse Adoptium project may make available for testing, but not market or promote for extended or production use, binary builds created as a development step towards what is intended to be a Java SE implementation passing the Java SE TCK licensed to the Eclipse..." to the new previous versions page, with the new title "Eclipse Adoptium Interim Build Labeling Requirements v1.0".
 
- [x] Edit the [governance page](https://projects.eclipse.org/projects/adoptium/governance) with the new v 2.0 , change the  title of the corresponding section to "Eclipse Adoptium Interim Build Labeling Requirements v2.0" and the new version text: 

> The Eclipse Adoptium project may make available for testing, but not market or promote for extended or production use, binary builds created as a development step towards what is intended to be a Java SE implementation passing the Java SE TCK licensed to
> the Eclipse Adoptium project by Oracle that in each case (a) otherwise complies with the Eclipse Adoptium project charter, (b) excepting portions from OpenJDK, is developed primarily within the Eclipse Adoptium project, and (c) does not include any
> content from the OpenJ9 Project or Oracle’s GraalVM project(s) or any successors of either of the foregoing, except to the extent present in any future version of the Java SE reference implementation from Oracle (“Intermediate Builds”) subject to the following
> conditions:
> 
> i. such Intermediate Build is marked with the word "UNTESTED" or "INCOMPATIBLE" or "UNSTABLE" or "BETA";
> ii. the Eclipse Adoptium project displays the following notice in such a manner that anyone downloading the Intermediate Build must see the notice before commencing the download:
> 
> "This is an intermediate build made available for testing purposes only. The code is untested and presumed incompatible with the Java SE Specification. You should not deploy or write to this code, but instead use a tested and certified Java SE compatible version of the code. Redistribution of this build must retain this notice."
> 
> The Eclipse Adoptium project must also include the same notice as a README.JAVASE file with any source code bundle (e.g. tarball) download that corresponds to the Intermediate Build;
> 
> iii. the Eclipse Adoptium project shall not distribute (except as a passive download as provided above), market or promote  intermediate Builds, including without limitation in connection with providing any goods or services.
> 
> iv. excepting mirror repositories of unmodified source code directly obtained from OpenJDK, the Eclipse Adoptium project must include the following README.JAVASE file in the root directory of any source code that is used in an Intermediate Build and that it may make available through access to a revision control system (e.g. git) (substituting in the relevant Project name and
> link where noted):
> 
> “This version of [Project name] source code is made available in support of the open source development process. Some numbered or tagged revisions of this source may have been tested and found to pass the Java SE TCK, and you can find information on which revisions or tags at [include URL and link]. Please note that since only binaries can be tested, source code cannot be described as a compatible implementation of the Java SE Specification. The different build environment on your machine and any changes you may make to this code could render your resulting build incompatible. Because of this, writing or deploying applications to builds based on this code can lead to lack of portability. You should instead consider deploying production applications on the pre-built binaries of [Project Name] that are available at [include a url and a link] that have been tested and certified to meet the Java SE compatibility requirements."
> 
> v. Notwithstanding the foregoing, for
> (i) Java SE 21 and later Intermediate Builds created prior to April 6, 2024 and (ii) Java SE 8-20 Intermediate Builds, the Eclipse Adoptium project must apply one of the following:
> (1) the notices set forth for Intermediate Builds in Attachment D version 1.0 [link to be added],
> (2) the notices set forth for Intermediate Builds in this Attachment D version 2.0.or
> (3) the notices set forth in the OpenJDK Community TCK and EA TCK License Agreement v 4.0[link].
> For Java SE 21 and later Intermediate Builds created after April 6, 2024, the notices set forth in the OpenJDK Community TCK and EA TCK License Agreement v 4.0[link] must be applied.
> 
> vi. any mirror repository of unmodified source code directly obtained from OpenJDK that is used in an Intermediate Build that is made available through access to a revision control system (e.g. git) must include the following in a public facing description of such source code:
> 
> "This source code is an unmodified mirror of source code obtained from OpenJDK [include a url and a link]. It has been and may still be used to create builds that are untested and incompatible with the Java SE specification. You should not deploy or write to this code, but instead use the tested and certified Java SE compatible version of the code that is available at [include a url and a link]."

- [ ] Add v1.0 link to the line "1) the notices set forth for Intermediate Builds in Attachment D version 1.0 [link to be added]"
- [x] Edit nightly build page (https://adoptium.net/temurin/nightly/?version=21) by changing the notice text as follows:

>  "This is an intermediate build made available for testing purposes only. The code is untested and presumed incompatible with the Java SE Specification. You should not deploy or write to this code, but instead use a tested and certified Java SE compatible version of the code. Redistribution of this build must retain this notice." 

- [ ] Please review, add to the list, and update all documentation this new wording affects.

**Comment by tellison** [comment]
Website is updated. Just waiting on Wayne to provide the extra governance tab on the project page before updating that too.

**Comment by waynebeaton** [comment]
The page is [here](https://projects.eclipse.org/projects/adoptium/governance/previous-versions).

Unfortunately, the permissions model isn't flexible enough to grant privileges to edit this page, so I'll have to do it.

Please provide me with the exact text and I'll update the page.

**Comment by tellison** [comment]
@waynebeaton the exact text is given above by Carmen. That's all we have.

**Comment by CarmenDelgadoEclipse** [comment]
> The page is [here](https://projects.eclipse.org/projects/adoptium/governance/previous-versions).
> 
> Unfortunately, the permissions model isn't flexible enough to grant privileges to edit this page, so I'll have to do it.
> 
> Please provide me with the exact text and I'll update the page.

Thank you @waynebeaton. We need to copy the text  quoted below  from the current governance page and change the title by adding v1.0

> Eclipse Adoptium Interim Build Labeling Requirements v 1.0:
> 
> The Eclipse Adoptium project may make available for testing, but not market or promote for extended or production use, binary builds created as a development step towards what is intended to be a Java SE implementation passing the Java SE TCK licensed to the Eclipse Adoptium project by Oracle that in each case (a) otherwise complies with the Eclipse Adoptium project charter, (b) excepting portions from OpenJDK, is developed primarily within the Eclipse Adoptium project, and (c) does not include any content from the OpenJ9 Project or Oracle’s GraalVM project(s) or any successors of either of the foregoing, except to the extent present in any future version of the Java SE reference implementation from Oracle (“Intermediate Builds”) subject to the following conditions:
> 
> i. such Intermediate Build is marked with the word "UNTESTED" or "INCOMPATIBLE" or "UNSTABLE" or "BETA"; 
> 
> ii. the Eclipse Adoptium project displays the following notice in such a manner that anyone downloading the Intermediate Build must see the notice before commencing the download (substituting in the relevant link where noted): 
> 
> "This is an intermediate build made available for testing purposes only. The code is untested and presumed incompatible with the Java SE specification. You should not deploy or write to this code, but instead use the tested and certified Java SE compatible version of the code that is available at [include a url and a link]. Redistribution of any Intermediate Build must retain this notice." 
> 
> The Eclipse Adoptium project must also include the same notice as a README.JAVASE file with any source code bundle (e.g. tarball) download that corresponds to the Intermediate Build; 
> 
> iii. the Eclipse Adoptium project shall not distribute (except as a passive download as provided above), market or promote Intermediate Builds, including without limitation in connection with providing any goods or services. 
> 
> iv. excepting mirror repositories of unmodified source code directly obtained from OpenJDK, the Eclipse Adoptium project must include the following README.JAVASE file in the root directory of any source code that is used in an Intermediate Build and that it may make available through access to a revision control system (e.g. git) (substituting in the relevant Project name and link where noted):
> 
> “This version of [Project name] source code is made available in support of the open source development process. Some numbered or tagged revisions of this source may have been tested and found to pass the Java SE TCK, and you can find information on which revisions or tags at [include URL and link]. Please note that since only binaries can be tested, source code cannot be described as a compatible implementation of the Java SE Specification. The different build environment on your machine and any changes you may make to this code could render your resulting build incompatible. Because of this, writing or deploying applications to builds based on this code can lead to lack of portability. You should instead consider deploying production applications on the pre-built binaries of [Project Name] that are available at [include a url and a link] that have been tested and certified to meet the Java SE compatibility requirements." 
> 
> v. any mirror repository of unmodified source code directly obtained from OpenJDK that is used in an Intermediate Build that is made available through access to a revision control system (e.g. git) must include the following in a public facing description of such source code: 
> 
> "This source code is an unmodified mirror of source code obtained from OpenJDK [include a url and a link]. It has been and may still be used to create builds that are untested and incompatible with the Java SE specification. You should not deploy or write to this code, but instead use the tested and certified Java SE compatible version of the code that is available at [include a url and a link].”

**Comment by waynebeaton** [comment]
Done. See [here](https://projects.eclipse.org/projects/adoptium/governance/previous-versions).

I added some preamble to attempt to make the intention of this page as understandable as possible to a user who stumbles up on it. Let me know if you want to add or change anything to the preamble.

Do we want to put any kind of framing around dates on the previous version?

**Comment by CarmenDelgadoEclipse** [comment]
> Done. See [here](https://projects.eclipse.org/projects/adoptium/governance/previous-versions).
> 
> I added some preamble to attempt to make the intention of this page as understandable as possible to a user who stumbles up on it. Let me know if you want to add or change anything to the preamble.
> 
> Do we want to put any kind of framing around dates on the previous version?

Thank @waynebeaton. I only have the effective date of the v2.0 "October 6, 2023 effective date of v2.0", @tellison, what do you think?

**Comment by CarmenDelgadoEclipse** [comment]
Hello, below you will find v2.0 text with the corresponding link updated, to be copied in the governance page:

>  **Eclipse Adoptium Interim Build Labeling Requirements v2.0:**

> The Eclipse Adoptium project may make available for testing, but not market or promote for extended or production use, binary builds created as a development step towards what is intended to be a Java SE implementation passing the Java SE TCK licensed to

> the Eclipse Adoptium project by Oracle that in each case (a) otherwise complies with the Eclipse Adoptium project charter, (b) excepting portions from OpenJDK, is developed primarily within the Eclipse Adoptium project, and (c) does not include any
> content from the OpenJ9 Project or Oracle’s GraalVM project(s) or any successors of either of the foregoing, except to the extent present in any future version of the Java SE reference implementation from Oracle (“Intermediate Builds”) subject to the following
> conditions:
> 
> i. such Intermediate Build is marked with the word "UNTESTED" or "INCOMPATIBLE" or "UNSTABLE" or "BETA";
> ii. the Eclipse Adoptium project displays the following notice in such a manner that anyone downloading the Intermediate Build must see the notice before commencing the download:
> 
> "This is an intermediate build made available for testing purposes only. The code is untested and presumed incompatible with the Java SE Specification. You should not deploy or write to this code, but instead use a tested and certified Java SE compatible version of the code. Redistribution of this build must retain this notice."
> 
> The Eclipse Adoptium project must also include the same notice as a README.JAVASE file with any source code bundle (e.g. tarball) download that corresponds to the Intermediate Build;
> 
> iii. the Eclipse Adoptium project shall not distribute (except as a passive download as provided above), market or promote intermediate Builds, including without limitation in connection with providing any goods or services.
> 
> iv. excepting mirror repositories of unmodified source code directly obtained from OpenJDK, the Eclipse Adoptium project must include the following README.JAVASE file in the root directory of any source code that is used in an Intermediate Build and that it may make available through access to a revision control system (e.g. git) (substituting in the relevant Project name and
> link where noted):
> 
> “This version of [Project name] source code is made available in support of the open source development process. Some numbered or tagged revisions of this source may have been tested and found to pass the Java SE TCK, and you can find information on which revisions or tags at [include URL and link]. Please note that since only binaries can be tested, source code cannot be described as a compatible implementation of the Java SE Specification. The different build environment on your machine and any changes you may make to this code could render your resulting build incompatible. Because of this, writing or deploying applications to builds based on this code can lead to lack of portability. You should instead consider deploying production applications on the pre-built binaries of [Project Name] that are available at [include a url and a link] that have been tested and certified to meet the Java SE compatibility requirements."
> 
> v. Notwithstanding the foregoing, for
> (i) Java SE 21 and later Intermediate Builds created prior to April 6, 2024 and (ii) Java SE 8-20 Intermediate Builds, the Eclipse Adoptium project must apply one of the following:
> (1) the notices set forth for Intermediate Builds in Attachment D version 1.0 [[link](https://projects.eclipse.org/projects/adoptium/governance/previous-versions)],
> (2) the notices set forth for Intermediate Builds in this Attachment D version 2.0.or
> (3) the notices set forth in the OpenJDK Community TCK and EA TCK License Agreement v 4.0[link].
> For Java SE 21 and later Intermediate Builds created after April 6, 2024, the notices set forth in the OpenJDK Community TCK and EA TCK License Agreement v 4.0[link] must be applied.
> 
> vi. any mirror repository of unmodified source code directly obtained from OpenJDK that is used in an Intermediate Build that is made available through access to a revision control system (e.g. git) must include the following in a public facing description of such source code:
> 
> "This source code is an unmodified mirror of source code obtained from OpenJDK [include a url and a link]. It has been and may still be used to create builds that are untested and incompatible with the Java SE specification. You should not deploy or write to this code, but instead use the tested and certified Java SE compatible version of the code that is available at [include a url and a link]."

Let me know if we need to decide and update something else. Thanks!

**Comment by CarmenDelgadoEclipse** [comment]
@waynebeaton, can you confirm if any committer can edit the governance page? @sxa  is trying to finish the final step of updating the current governance page with v2.0, and it looks like there are some restrictions for the governance page. Thank you!

**Comment by waynebeaton** [comment]
@CarmenDelgadoEclipse All committers should be able to update the scope field (which is the only thing that is displayed on that page at present).

@sxa: the handbook describes how to [edit](https://www.eclipse.org/projects/handbook/#pmi-editing) the project's "PMI" metadata. The _Scope_ field is what is displayed on the _Governance_ page; that field is in the section titled "The Basics".

If you're having trouble modifying this content, please open a Help Desk issue and the team will work with you to sort it out.

**Comment by sxa** [comment]
OK Not sure what's going on here, but just as I was raising the issue I went back and it's displaying the correct content. I wonder if the fact it re-authenticated me via 2FA to get into gitlab many some difference, but I can't see how it would have got some outdated text in that scenario ... That is one of the strangest cache-related issues I've seen ...

![image](https://github.com/adoptium/adoptium/assets/6487691/5cb229fb-f82f-4119-93e5-69a338fd4840)

**Comment by sxa** [comment]
@CarmenDelgadoEclipse ref;

> (3) the notices set forth in the OpenJDK Community TCK and EA TCK License Agreement v 4.0[link].
For Java SE 21 and later Intermediate Builds created after April 6, 2024, the notices set forth in the OpenJDK Community TCK and EA TCK License Agreement v 4.0[link](https://openjdk.org/legal/OCTLA-JDK21+.pdf) must be applied.

Can you clarify the correct link for this and the following line - do you want them both to point to the openjdk.org page at https://openjdk.org/legal/OCTLA-JDK21+.pdf ?

**Comment by CarmenDelgadoEclipse** [comment]
> @CarmenDelgadoEclipse ref;
> 
> > (3) the notices set forth in the OpenJDK Community TCK and EA TCK License Agreement v 4.0[link].
> > For Java SE 21 and later Intermediate Builds created after April 6, 2024, the notices set forth in the OpenJDK Community TCK and EA TCK License Agreement v 4.0[link](https://openjdk.org/legal/OCTLA-JDK21+.pdf) must be applied.
> 
> I've done the updates but can you clarify the correct link for this and the following line - do you want them both to point to the openjdk.org page at https://openjdk.org/legal/OCTLA-JDK21+.pdf ? I've included those for now but if that's incorrect please let me know so I can adjust them.

Yes, It is Thank you Stewart.

**Comment by CarmenDelgadoEclipse** [comment]
Thank you all for your help! :)
