### ISSUE TITLE
Define per-project security team defaults

### ISSUE THREAD

**Issue by tellison** [adoptium/adoptium#258]
The Eclipse Foundation [have announced](https://www.eclipse.org/lists/eclipse.org-committers/msg01448.html) that there are now individual project security teams for handling vulnerability reports. By default these teams will comprise all committers of the project.

Following a discussion in the Adoptium PMC, and a [discussion with the Eclipse security team](https://github.com/orgs/eclipse-csi/discussions/4#discussioncomment-10475939), Adoptium have chosen to implement a default that is restricted to only project leads, whilst recognising that additional committers and subject matter experts will be invited to consult and work on individual vulnerability reports as required.

This issue covers the task of updating the default security team membership in each project's [PMI](https://projects.eclipse.org/) page:

- [x] [Eclipse Adoptium](https://projects.eclipse.org/projects/adoptium) (top level project)
- [x] [Eclipse Temurin](https://projects.eclipse.org/projects/adoptium.temurin)
- [x] [Eclipse AQAvit](https://projects.eclipse.org/projects/adoptium.aqavit)
- [x] [Eclipse Temurin Compliance](https://projects.eclipse.org/projects/adoptium.temurin-compliance)
- [x] [Eclipse Mission Control](https://projects.eclipse.org/projects/adoptium.mc)
- [x] [Eclipse Migration Toolkit for Java](https://projects.eclipse.org/projects/adoptium.emt4j)
- [x] [Eclipse Adoptium Incubator](https://projects.eclipse.org/projects/adoptium.incubator)

**Comment by tellison** [comment]
I don't have rights to update the Security Team membership of all Adoptium's projects.
Please can the following people update their projects as follows:

1. Ensure you are logged into to your Eclipse account, and visit the project page (linked).
1. Go to the "Edit" tab, expand the "Security" twistie.
1. Change the "Roles where all members belong to the Security Team" to _uncheck_ **Committers** and _check_ **Project leads**. i.e. so it ends up with Project leads only.
1. Finally, mark the checkbox against the project in the [original post](https://github.com/adoptium/adoptium/issues/258#issue-2516849704) of this issue so we know it has been done. Thanks!

| Project | Lead |
|---|---|
| [Temurin Compliance](https://projects.eclipse.org/projects/adoptium.temurin-compliance) | @gdams / @sxa / @smlambert |
| [Mission Control](https://projects.eclipse.org/projects/adoptium.mc) | @thegreystone / @gdams / @reinhapa |
| [Migration Toolkit for Java](https://projects.eclipse.org/projects/adoptium.emt4j) | @D-D-H |

**Comment by D-D-H** [comment]
Done.

**Comment by reinhapa** [comment]
@tellison Done but unable to change the update the checkbox...

**Comment by tellison** [comment]
All completed - thanks everyone.
