### ISSUE TITLE
Bi-weekly Adoptium Community Call - July 7, 2021

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#27]
**Time**

Wednesday July 7, 2021 3pm-4pm GMT (10am-11am EST/Ontario)

**Location**

https://bluejeans.com/956754991/2833?src=calendarLink

Add this recurring bi-weekly Adoptium Community Call to your calendar, if you wish. Available via the [Adoptium community calendar.](https://calendar.google.com/calendar/u/1?cid=Y191YW5ub3VtczVobzBvbGhqazN1bGVjZGtiY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

**Overall Purpose**

Mainly to make announcements regarding planned actions that affect the Adopt community
(Emphasis on non-test efforts, as those are covered in AQAvit call on oppposite bi-weekly Wednesdays)

Secondary purposes include debate, discussion, and community socializing.

Call to be recorded for reference, and linked in this issue afterwards.

**Proposed Meeting Agenda** - TBD / topics to be confirmed

- [ ] 1st Temurin release / July release planning / Review related projects - all
- [x] Update on reproducible builds prototype - @andrew-m-leonard 
- [x] Future of Adoptium documentation - @hendrikebbers 
- [x] Marketing activities - @hendrikebbers

**Comment by hendrikebbers** [comment]
Draft document for future documentation on Adoptium.net: https://docs.google.com/document/d/1AHxz5hSr4MJApAuPOYzjY7CLRTOHJgh7gxgGFUV2WAk/edit#
Student project: https://github.com/AdoptOpenJDK/website-adoptium

**Comment by hendrikebbers** [comment]
Zenhub board: https://app.zenhub.com/workspaces/adoptium-60d93da7bf5a0e0019b82131

**Comment by smlambert** [comment]
Meeting [recording link](https://bluejeans.com/s/JKyBSrH2NHa)

Minutes:
- Quick note about "initial release" progress - finally at the last stages of this work, running TCKs, a few more items on the Eclipse infra teams list to complete in order for us to finish that work, hoping it can be completed by the end of this week
- @hendrikebbers talked about future documentation and marketing pieces (and added links in comments to this issue for more details on those topics)
  - Adoptium zenhub board currently contains 2 projects (Marketing_and_Community and DRASP), more updates to that board to be added during a Friday call on [Project Mgmt](https://github.com/AdoptOpenJDK/TSC/issues/220) (@smlambert & @karianna & any others who wish to join in)
- @andrew-m-leonard described some of the DRASP work he and others have been doing (DRASP stands for defined, reproducible/recreatable, auditable, secure, presentable).  We focus on the R, A, and S pieces for now.  He's updated the build_info artifact with additional info relating to dependencies.  @Haroon-Khel is looking from the playbook and infrastructure side (checksums/GPG verification of dependencies).  This work will get picked back up again after July release which will take all of our focus for now.
- July release project currently contains no issues, some issues to create (today & in Friday's project mgmt call) will be one to describe the priorities, how the team will split its time and attention (and the machine resources required).  
  - update to release checklist still needed
  - @karianna created the '[release plan' for the July release](https://projects.eclipse.org/projects/adoptium.temurin/releases/2021.07.20) (Eclipse foundation process) for July release
  - @adamfarley shared the issue for post July release retrospective in release channel

Link to next Adoptium community call: https://github.com/adoptium/adoptium/issues/47
