### ISSUE TITLE
Setup TCK infrastructure to begin TCK testing binaries

### ISSUE THREAD

**Issue by gdams** [adoptium/adoptium#3]
This is the high-level view of the activities under this Epic (based off of the action plan from the Eclipse transition document):

- [x] Setup eclipse Jenkins server with the plugins listed in the requirements doc - done https://ci.eclipse.org/temurin-compliance (EF infra)
- [x] Create empty repos for the test material (for each version JCK8-unzipped, JCK11-unzipped, and so forth) and for the Test results - to push the results artifacts from the release pipelines  (EF infra / PMC)
- [x] Coordinate with Wayne B. to transfer private JCK repo (which contains helpful FAQ and troubleshooting docs/wiki) to a private eclipse owned JCK repo (can be wiki off of the Test results repo (Shelley)
- [x] Generate test pipelines (including Grinders) (Shelley)
- [x] Create various triggers, both remotely triggered from open Temurin pipelines on the public server (for nightly/weekly runs), and top-level pipeline at the private Jenkins server that pull from the API and can trigger child pipelines by version/platform) (Shelley)
- [x] Attach Eclipse controlled machines (static and/or Eclipse controlled cloud instances to the private Jenkins server (and label appropriately), to cover all of the the different platforms we wish to distribute.   (Stewart/George/Mikael)
  - Initial eclipse-cbi/jiro PR: https://github.com/eclipse-cbi/jiro/pull/159
- [ ] Confirm machines for each platform have been added and configured properly (including at least 1 of each platform that can be used by committers to run manual TCK tests, see https://github.com/adoptium/adoptium/issues/3#issuecomment-857714700) (@sxa, @gdams, @mbarbero)
  - [x] x86-64_linux (jck-packet-ubuntu2004-x64-1 added via [cbi/jiro/159](https://github.com/eclipse-cbi/jiro/pull/159), config is 👍 for automated tests, will want other dynamic agents added for parallel runs of automated tests)
  - [x] x86-64_mac (request for machines: https://bugs.eclipse.org/bugs/show_bug.cgi?id=573538)
  - [x] x86-64_windows (request for machines: https://bugs.eclipse.org/bugs/show_bug.cgi?id=573539)
  - [x] aarch64_linux 
  - [x] s390x_linux (jck-marist-ubuntu2004-s390x-1,jck-marist-ubuntu2004-s390x-2 added via [cbi/jiro/159](https://github.com/eclipse-cbi/jiro/pull/159), config needs ansible-ization)
  - [x] ppc64le_linux
  - [x] ppc64_aix
  - [x] x86-32_windows
  - [x] solaris_sparcv9 (jck-siteox-solaris10u11-sparcv9-1 added via [cbi/jiro/165](https://github.com/eclipse-cbi/jiro/pull/165)
  - [x] solaris_x86-64 (added via [cbi/jiro/178](https://github.com/eclipse-cbi/jiro/pull/178), config needs testing)
  - [ ] arm_linux 
- [x] Set up necessary jck servers ([ubuntu-jckservices.yml](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Services_Playbooks/ubuntu-jckservices.yml) for reference) (EF infra/Stewart)
- [x] Trial runs of other types of tests (non-JCK) to ensure Jenkins and nodes are setup correctly (on each platform/version) (Shelley / Temurin-compliance committers)
- [x] Download TCK material from Oracle site to populate the JCKxx-unzipped repos (preferably using jckUpdater script supplied to Mikael directly).  (pending Oracle signature on 3way agreement, EDIT: 3way agreement signed June 1st, will proceed with this item now) (Mikael / Temurin-compliance committers)
- [x] Configure Jenkins server with credentials that allow test jobs access to clone private JCKxx-unzipped repos (@mbarbero)
- [x] Dry run automated TCK runs (nightly/weekly/full release), starting with 1 version and 1 platform and then expanding to the complete set (Shelley / Temurin-compliance committers)

**Comment by smlambert** [comment]
References:
- TCK infra requirements document (which includes detailed infra requirements)
- Eclipse transition document (which includes an action plan for lifting up Temurin-compliance)

**Comment by sxa** [comment]
My current plan (unless someone shouts otherwise) is to aim for:
- Ideally two systems on each platform where possible
- 1-2 CPU cores, 6-8Gb of RAM
- Ubuntu 20.04 (Latest LTS) as the OS for the Linux platforms (We will probably need Alpine too although if we run that in containers we can possibly share with the Ubuntu hosts)

**Comment by smlambert** [comment]
I've updated the description with the high-level tasks from the action plan, to give people a view of progress.

**Comment by sxa** [comment]
Requests for Eclipse-provided hardware:
- Mac: https://bugs.eclipse.org/bugs/show_bug.cgi?id=573538
- Windows: https://bugs.eclipse.org/bugs/show_bug.cgi?id=573539

**Comment by smlambert** [comment]
@sxa - Machine config request:
- https://ci.eclipse.org/temurin-compliance/job/Grinder/4/console - looks like AIX machines need git installed

**Comment by sxa** [comment]
Yeah not too much of a surprise - I haven't done any set up on them. We need to decide for the TCK machines if we want to run the full playbooks, a subset, or build a minimal set up from scratch. Let's discusss later today :-)

**Comment by smlambert** [comment]
My expectation would be that they are set up like other test machines so that they behave somewhat predictably.  If that playbook for test machines can be stripped down to a more minimal set, then great, we should apply that approach for all test machines (not just these attached to this server).

Adding another bullet item to this issue about setting up the services (ftp/kerberos) as well (either based on [ubuntu-jck.yml](https://github.com/adoptium/infrastructure/blob/master/ansible/playbooks/ubuntu-jck.yml)) or some static container based story).

**Comment by gdams** [comment]
One Solaris Sparc server has been ordered to host the Sparc TCK builds

**Comment by andrew-m-leonard** [comment]
Does this include running the TCK "manuals" ? Printers? GUI? VNC connection to run Manual TCK test tool?

**Comment by smlambert** [comment]
It needs to include configuration that supports running TCK interactive/manual testing also.  I have updated the checklist above to mention that.

**Comment by mbarbero** [comment]
> * [x]  Configure Jenkins server with credentials that allow test jobs access to clone private JCKxx-unzipped repos (@mbarbero)

Credentials' ID is `github-bot`

**Comment by sxa** [comment]
Two Linux/ppc64le machines from OSUOSL are now online in jenkins.
AIX is also set up although it's missing the `cups-devel` package due to RPM dependency issues in the AIX Toolbox. We will need to verify whether that causes a problem with any printer tests.

**Comment by mbarbero** [comment]
Two windows machines (windows server 2019) have been added to jenkins. Note that msvs 2013 and msvs 2019 setups failed and only 2017 is installed for now (see https://github.com/adoptium/infrastructure/issues/2231)

**Comment by smlambert** [comment]
This table added to make it easier to see progress.  TemurinVersion columns indicate that we've attempted and successfully run some automated tests on that platform for that version, which shows that the machines appear to be configured correctly and TCK material is accessible to the job.  This table is not to indicate that all tests were attempted, just that machines and test material are set up and ready to try the full set of automated runs. 

| Platforms | Num of Machines | Temurin8 | Temurin11 | Temurin16 | Temurin17 | Notes | 
| ----- | ----- | ----- | ----- | ----- | ----- | ----- | 
|   x64 Linux | 1 |  👍 |   | | | |
|   x64 Windows | 2 |  👍 |   | | | |
| x64 OSX | 2 | 👍 |   | | | |
| ppcle64 Linux | 2 |  |   | | | |
| s390x Linux | 2 |  |   | | | |
| ppc64 AIX | 2  |  |   | | | |
| aarch64 Linux | 2  |  |   | | | |
| sparcv9 Solaris | 1  |  |   | | | |

**Comment by smlambert** [comment]
Still 0 machines for aarch64 OSX and aarch64 Windows, but other platforms each have at least a single machine.  This means it is possible to release on all platforms where we have machines, noting that the table in https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922 contains estimates for how long it will take (best case scenario) to run TCKs, which is required before releasing binaries.  Time estimates do not include time it will take to also run compliance tests on JREs (double the estimates in that event).

Will mark this as closed and raise temurin-compliance issues for adding machines for aarch64 OSX and aarch64 Windows and for picking up the jdk17 TCK test material.

**Comment by smlambert** [comment]
Just for reference, July release interactive TCK tests, take 4-6hrs per platform/version/binaryType, so at 5hrs:

9 platforms x 3 versions x 2 binaryTypes x 5hrs = 270 hrs for interactives
2 platforms (solaris) x 1 version x 2 binaryTypes x 5hrs = 20 hrs for interactives

270+20 =
~290 hrs of people time (divided by the number of committers with 3-way agreement, which is 6, though 2 on vacation atm...) = 48 to 72 hrs per eligible person each to complete running these interactive tests for the July release.  

Noting this must be scheduled in and around the automated runs which take ~50 hrs per platform/version/binaryType (so ~100hrs per platform/version if JREs included, this can then be divided by the number of machines per platform to give a rough estimate on execution time to complete).

Adding people and machines will be important.
