### ISSUE TITLE
Provide ZenHub board for marketing related issues

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/adoptium#31]
Based on a discussion with @smlambert and @gdams we want to try to use ZenHub for all issues that are related to marketing and community work.

**Comment by smlambert** [comment]
Believe we are set.

I've created an [Adoptium Zenhub board](https://app.zenhub.com/workspaces/adoptium-60d93da7bf5a0e0019b82131/board) 
- connected to adoptium, adoptium.net, blog.adoptium.net repos (can add more as needed)
- added a project called Marketing_and_Community (with 3 Epics - Adoptium Marketplace, Transition to Website-Adoptium, Marketing Activities and added the issues tagged with "marketing" label to the appropriate Epic) - you can see them in the Roadmap view

Suggest that people pick up the [Zenhub browser extension](https://www.zenhub.com/extension) for best experience viewing the board and linking to it from repos.
