### ISSUE TITLE
Provide initial style and content for Adoptium.net

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/adoptium#36]
We need to define the initial content and style. The basic version will be based on a migration of the AdoptOpenJDK page (see https://github.com/adoptium/adoptium.net) in combination with the blog (https://github.com/adoptium/blog.adoptium.net) and later we can add more complex functionalities that are developed in a separate repository (https://github.com/AdoptOpenJDK/website-adoptium).

**Related issues / PRs**

-  https://github.com/adoptium/adoptium.net/pull/49

**Comment by tellison** [comment]
Obsolete
