### ISSUE TITLE
Provide Logos for basic projects / products

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/adoptium#37]
We need Logos for Temurin & Aqa

**Comment by hendrikebbers** [comment]
@smlambert this one is still in review. I assume we can close it?

**Comment by smlambert** [comment]
Yes, this can be closed (thanks for adding the wikis for usage and logos: https://github.com/adoptium/adoptium/wiki/Adoptium-Project-Logos and for Color Schemes and Fonts: https://github.com/adoptium/adoptium/wiki/Adoptium-Color-Schema-and-Fonts)
