### ISSUE TITLE
Tag core build/test repos to preserve pre EF history

### ISSUE THREAD

**Issue by gdams** [adoptium/adoptium#4]
- https://github.com/adoptium/installer/releases/tag/april-psu
- https://github.com/adoptium/ci-jenkins-pipelines/releases/tag/april-psu
- https://github.com/adoptium/github-release-scripts/releases/tag/april-psu
- https://github.com/adoptium/temurin-build/releases/tag/april-psu
- https://github.com/adoptium/mirror-scripts/releases/tag/april-psu

**Comment by smlambert** [comment]
Would we want to have thought about naming convention for tags to include year for example, in the event we want to tag at each quarterly going forward?  I feel like I should now copy the other examples (april-psu), but think the tag name will look pretty vague and out of place in a year if we continue to tag releases.

**Comment by sxa** [comment]
Is the intention of this to tag every release in this way or just as a one-off "pre-EF" thing which the title seems to suggest (although those tag names don't nevessarily make that obvious)

**Comment by smlambert** [comment]
I will call the test repo tags the same so we are consistent (though would have preferred a better/different tag name).  I will add a description: 
April 2021 snapshot prior to lifting up the Temurin builds in the transition to Eclipse Foundation
