### ISSUE TITLE
Get Quarkus based website content up and running

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/adoptium#42]
Based on a student project we created the following repo: https://github.com/AdoptOpenJDK/website-adoptium

Thais contains features like documentation, etc.
We want to integrate this in our Adoptium webpage.

**Comment by hendrikebbers** [comment]
issue regarding documentation: https://github.com/adoptium/adoptium/issues/50

**Comment by tellison** [comment]
New website technology stack is in place.
