### ISSUE TITLE
Provide Adoptium and project logos to the open

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/adoptium#44]
Maybe https://www.eclipse.org/org/artwork/ is the best place?

**Comment by smlambert** [comment]
Sharon mentioned that there is a review process underway (expected to be complete by end of June) to put the logos up to https://www.eclipse.org/org/artwork/.  We can follow up with her to find out if that has completed.

**Comment by smlambert** [comment]
Closing as the logos are available at both:
https://www.eclipse.org/org/artwork/ and https://github.com/adoptium/adoptium/wiki/Adoptium-Project-Logos
