### ISSUE TITLE
Provide style guideline for the Adoptium logos

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/adoptium#46]
Provide style guideline for the Adoptium logos

**Comment by smlambert** [comment]
Closing as complete as @hendrikebbers has put the [logos](https://github.com/adoptium/adoptium/wiki/Adoptium-Project-Logos) and [font/colour](https://github.com/adoptium/adoptium/wiki/Adoptium-Color-Schema-and-Fonts) guidelines as wikis to this repository:
