### ISSUE TITLE
Retrospective for July 2021 Releases

### ISSUE THREAD

**Issue by adamfarley** [adoptium/adoptium#48]
Using Community call timeslot and link for the retrospective 
**Time**

Wednesday Sept 1, 2021 4pm-5pm GMT (11am-noon EST/Ontario)

**Location**

https://bluejeans.com/956754991/2833?src=calendarLink

A bulleted list of all proposed agenda items in this issue (whether at the top or in a comment) will be created on the day of the call, with a list of actions added at the end.

Invited @adoptium/adoptium-committers @adoptium/adoptium-temurin-committers @adoptium/adoptium-aqavit-committers and anyone else interested in improving our release process

Retrospective Owner Tasks (in order):
- [x] Post this issue's URL on the \#Release Slack channel around the start of the new release.
- [x] Copy actions from the previous retrospective into this issue, while ignoring actions that have an issue link (i.e. clearly-completed actions).
- [x] Wait until all builds have been released, with no clear signs of additional respins.
- [x] Announce the retrospective Slack call's date + time on \#Release at least one full week in advance, and send out meeting invites.
- [x] On the day of the call, compile all of the agenda items into a tick-box list inside a single comment.
- [x] Host the slack call for the retrospective, including:
  - [x] Iterating over the actions from the previous retrospective issue, annotating *both* issues with any issues that have been raised for them.
  - [x] Iterate over the agenda tick-list, ensuring everything gets debated.
  - [x] Create a clear list of actions at the end of the retrospective, including volunteer names.
- [ ] Close the issue for the previous retrospective, ensuring that every action is annotated with its conclusion (issue link, ignored, etc).
- [x] Create a new retrospective issue for the next release.
- [x] Set yourself a calendar reminder so that you remember to commence step 1 (in the new issue) just before the next release.

Add proposed agenda items as comments below.

**Comment by mkurz** [comment]
> Date: TBD, likely around the start of August.

For Java 17, it would be nice to wait until August 5th, because that's when the Initial Release Candidate gets released, see https://openjdk.java.net/projects/jdk/17/

**Comment by adamfarley** [comment]
@mkurz - I'm not sure I understand why a retrospective for the July release (JDK 8, 11, and 16) is affected by the Java 17 candidate.

Could you explain your reasoning, please?

**Comment by mkurz** [comment]
Sorry, my bad, of course that makes no sense. Seems like I misread this issue.
Anyway, when do you plan to publish a new Java 17 binary (https://github.com/AdoptOpenJDK/openjdk17-binaries/releases)?

**Comment by adamfarley** [comment]
For any given release, we usually try to get it out within 48 hours of the upstream release, or as close as we can.

So for Java 17, that'll be within 48 hours of September 14th. Unless there's an upstream delay, or a key test failure, etc etc.

**Comment by adamfarley** [comment]
Please take further questions to Slack. :)

**Comment by mkurz** [comment]
Alright, but what about nightly builds, which seems stopped working as of May 7th? https://github.com/AdoptOpenJDK/openjdk17-binaries/releases

**Comment by mkurz** [comment]
@adamfarley Seems like I can't join the slack channel, because I don't have a `@eclipse-foundation.org` email address...

**Comment by adamfarley** [comment]
Odd. Leave it with me. I'll ask in Slack, see if we can get an admin's attention.

**Comment by mkurz** [comment]
Thanks @adamfarley. Maybe the nightly build pipeline is broken?

**Comment by karianna** [comment]
> @adamfarley Seems like I can't join the slack channel, because I don't have a `@eclipse-foundation.org` email address...

Hi @mkurz - Which link did you follow to join Slack?

**Comment by mkurz** [comment]
https://adoptium.slack.com/signup found via https://blog.adoptium.net/2021/03/eclipse-adoptium-announcement/

**Comment by adamfarley** [comment]
@mkurz - Try going via https://adoptium.net/slack

**Comment by mkurz** [comment]
Thanks, I did just now.

**Comment by sxa** [comment]
Clarify process for kicking the API when new artifacts are added to the release (given that we are likely drip feeding releases out in the future)

**Comment by sxa** [comment]
Who should have access to build jobs during the lockdown period? We need to consider the impact on being able to debug problems during the lockdown period (particulary problematic for this release!) e.g. our AIX support were unable to look at the output from jobs and run test jobs during this period.

**Comment by adamfarley** [comment]
**Retrospective Agenda**
- [ ] Clarify process for kicking the API when new artifacts are added to the release (given that we are likely drip feeding releases out in the future)
- [ ] Who should have access to build jobs during the lockdown period? We need to consider the impact on being able to debug problems during the lockdown period (particulary problematic for this release!) e.g. our AIX support were unable to look at the output from jobs and run test jobs during this period.
- [ ] Clarity on who will be available during the release cycles and ensure any appopriate handover is done if someone is going to be away (particuarly important if the TCK is resulting in longer release cycles)

**Retrospective Actions**
-

**Comment by smlambert** [comment]
Would be preferred to do AQA triage all at once rather than in bits and pieces (primaries and secondaries), or at very least communicate and co-ordinate what platforms are up next.

**Comment by smlambert** [comment]
Review the release checklist template to make sure its correct to the new Adoptium process.

**Comment by smlambert** [comment]
Is the table in https://github.com/adoptium/adoptium/issues/68 helpful for future releases

**Comment by smlambert** [comment]
Rethink project mgmt & use of Zenhub as it relates to a release.

**Comment by adamfarley** [comment]
Closing. [Next retrospective](https://github.com/adoptium/adoptium/issues/48).
