### ISSUE TITLE
Bi-weekly Adoptium Community Call - August 4, 2021

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#61]
**Time**

Wednesday August 4, 2021 3pm-4pm GMT (10am-11am EST/Ontario)

**Location**

https://bluejeans.com/956754991/2833?src=calendarLink

Add this recurring bi-weekly Adoptium Community Call to your calendar, if you wish. Available via the [Adoptium community calendar.](https://calendar.google.com/calendar/u/1?cid=Y191YW5ub3VtczVobzBvbGhqazN1bGVjZGtiY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

**Overall Purpose**

Mainly to make announcements regarding planned actions that affect the Adopt community
(Emphasis on non-test efforts, as those are covered in AQAvit call on opposite bi-weekly Wednesdays)

Secondary purposes include debate, discussion, and community socializing.

Call to be recorded for reference, and linked in this issue afterwards.

**Proposed Meeting Agenda** - TBD / topics to be confirmed

- [ ] TBD

**Comment by adamfarley** [comment]
Next meeting: https://github.com/adoptium/adoptium/issues/69

**Comment by smlambert** [comment]
Meeting [recording link](https://bluejeans.com/s/4eUQMfq39Vw)
