### ISSUE TITLE
July 2021 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#68]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922.  Primary platforms (x64 Linux/Windows/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).

👍 results in this Table means both AQA tests for quality and TCK tests for compliance have been run and pass.
:hourglass_flowing_sand: results means that we are actively working on closing off the runs needed for this version, platform, binaryType.
:no_entry_sign: means there is no build planned for that version/platform combination 
:open_file_folder: means compliance testing not yet started

| Platforms | Link to Build | jdk8  | jdk11 | jdk16 |  jre8 | jre11 | jre16 |Notes | 
| ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | 
| **x64 Linux** | [8](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1715/artifact/target/linux/x64/hotspot/OpenJDK8U-jdk_x64_linux_hotspot_8u302b08.tar.gz) [11](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1597/artifact/target/linux/x64/hotspot/OpenJDK11U-jdk_x64_linux_hotspot_11.0.12_7.tar.gz) [16](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk16-pipeline/432/artifact/target/linux/x64/hotspot/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz) | 👍  | 👍 | 👍 | 👍 |  👍  |  :no_entry_sign: |  JDK Complete, JRE in progress ||
| **x64 Windows** | [8](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1715/artifact/target/windows/x64/hotspot/OpenJDK8U-jdk_x64_windows_hotspot_8u302b08.zip) [11](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1597/artifact/target/windows/x64/hotspot/OpenJDK11U-jdk_x64_windows_hotspot_11.0.12_7.zip) [16](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk16-pipeline/432/artifact/target/windows/x64/hotspot/OpenJDK16U-jdk_x64_windows_hotspot_16.0.2_7.zip)  | 👍   | 👍 | 👍 | 👍 | 👍  | :no_entry_sign:  |  JDK & JRE8 Complete | 
| **x64 OSX** |  [8](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1716/artifact/target/mac/x64/hotspot/OpenJDK8U-jdk_x64_mac_hotspot_8u302b08.tar.gz) [11](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1597/artifact/target/mac/x64/hotspot/OpenJDK11U-jdk_x64_mac_hotspot_11.0.12_7.tar.gz) [16](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk16-pipeline/432/artifact/target/mac/x64/hotspot/OpenJDK16U-jdk_x64_mac_hotspot_16.0.2_7.tar.gz) | 👍    | 👍    | 👍    | 👍 | 👍   |  :no_entry_sign: |  JDK Complete, JRE in progress |
| aarch64 Linux |  [8](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1715/artifact/target/linux/aarch64/hotspot/OpenJDK8U-jdk_aarch64_linux_hotspot_8u302b08.tar.gz)  [11](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1597/artifact/target/linux/aarch64/hotspot/OpenJDK11U-jdk_aarch64_linux_hotspot_11.0.12_7.tar.gz) [16](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk16-pipeline/432/artifact/target/linux/aarch64/hotspot/OpenJDK16U-jdk_aarch64_linux_hotspot_16.0.2_7.tar.gz) | 👍   | 👍   | 👍   | 👍  | 👍  | :no_entry_sign:  |  JDK Complete, JRE in progress |
| ppcle64 Linux |  [8](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1715/artifact/target/linux/ppc64le/hotspot/OpenJDK8U-jdk_ppc64le_linux_hotspot_8u302b08.tar.gz) [11](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1597/artifact/target/linux/ppc64le/hotspot/OpenJDK11U-jdk_ppc64le_linux_hotspot_11.0.12_7.tar.gz) [16](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk16-pipeline/432/artifact/target/linux/ppc64le/hotspot/OpenJDK16U-jdk_ppc64le_linux_hotspot_16.0.2_7.tar.gz) | 👍   | 👍    | 👍   | 👍 | 👍  | :no_entry_sign: |  JDK Complete, JRE in progress |
| s390x Linux |  [8](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1715/artifact/target/linux/s390x/hotspot/OpenJDK8U-jdk_s390x_linux_hotspot_8u302b08.tar.gz)  [11](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1597/artifact/target/linux/s390x/hotspot/OpenJDK11U-jdk_s390x_linux_hotspot_11.0.12_7.tar.gz) [16](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk16-pipeline/432/artifact/target/linux/s390x/hotspot/OpenJDK16U-jdk_s390x_linux_hotspot_16.0.2_7.tar.gz) | :no_entry_sign:  | 👍    | 👍  | :no_entry_sign: | 👍  | :no_entry_sign: | JDK11 complete, JDK8/16 in progress  |  
| ppc64 AIX | [8](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1715/artifact/target/aix/ppc64/hotspot/OpenJDK8U-jdk_ppc64_aix_hotspot_8u302b08.tar.gz) [11](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1597/artifact/target/aix/ppc64/hotspot/OpenJDK11U-jdk_ppc64_aix_hotspot_11.0.12_7.tar.gz) [16](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk16-pipeline/432/artifact/target/aix/ppc64/hotspot/OpenJDK16U-jdk_ppc64_aix_hotspot_16.0.2_7.tar.gz) | 👍    |  👍   | :hourglass_flowing_sand:   | 👍 | 👍  | :no_entry_sign: | JDK8/11 complete, JDK16 in progress   |
| sparcv9 Solaris |  [8](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1715/artifact/target/solaris/sparcv9/hotspot/OpenJDK8U-jdk_sparcv9_solaris_hotspot_8u302b08.tar.gz)  |  👍   | :no_entry_sign:  | :no_entry_sign: |  :open_file_folder:  |  :no_entry_sign:  | :no_entry_sign: |  JDK in progress  |
| x64 Solaris | [8](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1715/artifact/target/solaris/x64/hotspot/OpenJDK8U-jdk_x64_solaris_hotspot_8u302b08.tar.gz) | 👍  | :no_entry_sign: | :no_entry_sign: | :open_file_folder:  | :no_entry_sign:   | :no_entry_sign: |  JDK in progress  |
| x32 Windows |  [8](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1715/artifact/target/windows/x86-32/hotspot/OpenJDK8U-jdk_x86-32_windows_hotspot_8u302b08.zip) [11](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1597/artifact/target/windows/x86-32/hotspot/OpenJDK11U-jdk_x86-32_windows_hotspot_11.0.12_7.zip) [16](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk16-pipeline/432/artifact/target/windows/x86-32/hotspot/OpenJDK16U-jdk_x86-32_windows_hotspot_16.0.2_7.zip) | 👍  | 👍 |  👍  | 👍   |  👍 | :no_entry_sign: | JDK in progress  |
| arm32 Linux |  8 [11](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1597/artifact/target/linux/arm/hotspot/OpenJDK11U-jdk_arm_linux_hotspot_11.0.12_7.tar.gz) [16](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk16-pipeline/432/artifact/target/linux/arm/hotspot/OpenJDK16U-jdk_arm_linux_hotspot_16.0.2_7.tar.gz) | 👍    | 👍   | 👍 |  :hourglass_flowing_sand:   |  👍   |  :no_entry_sign: | JDK in progress |
| ~~aarch64 Windows~~ | - | :no_entry_sign: | -  |  - | :no_entry_sign:   |  - | - | Nightly beta builds available, but no July release, since no TCK machines |

**Docker Images**

Docker Images have been released for the binaries above at [Docker Hub](https://hub.docker.com/_/eclipse-temurin).

As more JDKs/JREs roll off the production line, the Docker images (for the supported platforms) will follow suit ~24 hours later

There is a [discussion on Alpine Images](https://www.github.com/adoptium/containers/issues/1) - covering both glibc and musl.

**Linux Installers**

Linux Installers are still being worked on, you can track the [New Linux Installer Issue](https://www.github.com/adoptium/installer/issues/330)

**Comment by tellison** [comment]
Maybe clarify that "means there is no build for that version/platform combination" means there is no build planned.
Consider adding an explanation for blank cells in the table (or inventing an icon for planned but not started etc).

**Comment by Shoggi1105** [comment]
Can we have an update on the x32? The problem is that for cyber essentials we have to patch our servers 14 days after security bulletin out. This was on 21st July. This is 4 weeks since knowing on public. We end up to move to Oracle and paying money to keep our security standards if hte 32 builds will take such long every time a new version comes out.

**Comment by gdams** [comment]
@Shoggi1105 Windows x32 JDK8 has been released, JDK11 Win x32 will be released shortly

**Comment by Shoggi1105** [comment]
@gdams , thank you. We neeed the JDK16 :-) before the 17 LTS comes out in September

**Comment by koldat** [comment]
Is Alpine Linux Java 16 build missed intentionally? AdoptJDK had it: https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16.0.1%2B9/OpenJDK16U-jdk_x64_alpine-linux_hotspot_16.0.1_9.tar.gz

**Comment by karianna** [comment]
https://github.com/docker-library/official-images/pull/10779 has just gone in

**Comment by koldat** [comment]
@karianna - (I written similar comment in Slack) this is Alpine image with glibc and not with muslc (native C library for Alpine). This build (muslc) was introduced for AdoptOpenJDK Java 16. Adoptium builds are having that only in "nightly" builds. Image in your link does not use "Alpine" build, but "Linux x64" build.

We am not need Docker image, but just JDK binary tar.gz using muslc build. We are building our own image in our pipeline using Adoptium binaries.

**Comment by karianna** [comment]
Ah, I see - I'll ask the PMC what we're going to do here.

**Comment by Shoggi1105** [comment]
@gdams , thanks for your help so far. Do we have any high level estimate when x32 Windows JDK in progress 16.x moves to ready? Is this this week, next week or what is "planned" without comitting to a date please?

**Comment by smlambert** [comment]
This one is as done as its going to get...
