### ISSUE TITLE
Sept 2021 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#74]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922.  Primary platforms (x64 Linux/Windows/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).

👍 results in this Table means the activity has successfully completed.
⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.
⛔ means there is no build planned for that version/platform combination. 
📂 means activity not yet started.

| Platforms | Link to Build | jdk17 AQA  | jdk17 TCK | jdk17 installers | jdk17 containers | Notes | 
| ----- | ----- | ----- | ----- | ----- | ----- | ----- | 
| **x64 Linux** | [build 187](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/187/) | 👍     | 👍   | 📂  | 👍 |   | 
| **x64 Windows** | [build 187](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/187/) |   👍   | 👍   | 👍 |👍  |   | 
| **x64 Mac** | [build 187](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/187/) |   👍   | 👍   | 👍 | ⛔ | Homebrew completed  | 
|  aarch64 Linux | [build 188](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/188/) |  👍    | 👍  | 📂 |👍  |   | 
| ppcle64 Linux  | [build 188](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/188/) |  👍    | 👍   | 📂 | 👍 |   | 
|  s390x Linux | [build 188](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/188/) |   👍   | 👍   | 📂 | 👍 |   | 
| ppc64 AIX | [build 191](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/191/) |   👍   | ⏳  | ⛔ |⛔  |   | 
| x32 Windows | [build 188](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/188/) | 👍     | 👍  |👍  | ⛔ |   | 
| arm32 Linux | [build 188](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/188/) |   👍   | 👍  | 📂 | 👍 |   | 
| x64 alpine-Linux | [build 192](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/192/) | 👍     |  👍  | 📂 | 👍 |  This will be a headless build | 
|  aarch64 Mac | [build 188](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/188/) |  👍   | 👍  | 👍 | ⛔ |   |

**Comment by CyberFlameGO** [comment]
Sweet!

**Comment by System0x40** [comment]
Thanks for all the efforts

**Comment by roflsunriz** [comment]
I have upgraded JDK11(LTS) to JDK17(LTS), but with my java app, it makes turns out japanese font into chinese japanese font.
Is this issue (to make in this repository)?
Anyway thank you for your effort too.

**Comment by Saljack** [comment]
Do you plan to provide JRE versions?

**Comment by vkoshkin** [comment]
> Do you plan to provide JRE versions?

Since Java 9, there is no JRE. You can build your own JRE with needed jmods with `jlink` tool. You can check needed jmods by `jdeps`.

**Comment by slandelle** [comment]
@vkoshkin It really feels like a way to force users to go this way. Azul Zulu keeps on providing lightweight JRE builds alongside the fat JDK ones.

**Comment by tellison** [comment]
> > Do you plan to provide JRE versions?
> 
> Since Java 9, there is no JRE. You can build your own JRE with needed jmods with `jlink` tool. You can check needed jmods by `jdeps`.

and there are some detailed instructions for doing this in a Docker container in [the blog](https://blog.adoptium.net/2021/08/using-jlink-in-dockerfiles/).

**Comment by tellison** [comment]
@rolfsunriz wrote:
> I have upgraded JDK11(LTS) to JDK17(LTS), but with my java app, it makes turns out japanese font into chinese japanese font.
> Is this issue (to make in this repository)?

I have opened this as https://github.com/adoptium/adoptium-support/issues/367

**Comment by ST-DDT** [comment]
(When) Will you add it to winget as done with https://github.com/microsoft/winget-pkgs/pull/25455 (Java 16)?

**Comment by roflsunriz** [comment]
JDK includes JRE. JRE is only runtime so it will allow users to run Java application while not allow to compile them.

**Comment by slandelle** [comment]
> Is there a big difference between 45MB JRE and 200MB JDK? 

AWS AMI, Docker images, etc... When you have lots of those, yes, weight makes a difference.

> If one cares about space he/she will either way go the jlink way.

Well, sure, if something doesn't exist out of the box, you can build it yourself.
But if enough people have the same need, why not build it once and provide it out of the box?

**Comment by krzyk** [comment]
@slandelle Because not everyone has the same need. Each app is different, uses different parts of java, that's why there is jlink (and jdeps) to allow building customized runtime environment where you can have minimal image possible.

**Comment by bilak** [comment]
@krzyk maybe not everybody would like to take care of jlink and their own image. You know some people are using [jib](https://github.com/GoogleContainerTools/jib) for exapmle. And unless you'd like to prepare your own image it would be so complicated to do this with jib. 

So from my site :+1: for having jre (full jre) image. I believe others are also saying they only care about having some public available JRE and they don't want to care about providing their own images.

**Comment by Saljack** [comment]
Here is the discussion regarding JRE in Temurin adoptium/temurin-build#2683

**Comment by slandelle** [comment]
> If you care for each MB, you can probably get down to ~20MB for jlinked runtime.

Sure, some users will definitely want that.

But for my use case, I can't anticipate which Java features the end user will need. I just know for sure they won't need the compiler, javadoc and most other tools.

Then, for some users, being able to download a ready-to-go 42MB package would be a big win over trimming down a JDK themselves.

Anyway, that's my feedback that I provide because I care and I've been using AdoptOpenJDK for a long time.

**Comment by kanwei** [comment]
Is there a debian repository for this? I know https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ was the old adoptopenjdk one but what is it for Adoptium?

**Comment by larsgrefer** [comment]
@kanwei Have a look here https://github.com/adoptium/installer/issues/330

**Comment by Shoggi1105** [comment]
The x32 version seems ready based on the table. I still don't see the installers here: https://adoptium.net/releases.html?variant=openjdk17&jvmVariant=hotspot. Can you confirm I miss something only?

**Comment by tellison** [comment]
> The x32 version seems ready based on the table. I still don't see the installers here: https://adoptium.net/releases.html?variant=openjdk17&jvmVariant=hotspot. Can you confirm I miss something only?

You were just a bit quick - they have been published now.

**Comment by drej1** [comment]
Hi, when can we expect aarch64 Mac support via homebrew? Thanks

**Comment by cadenkriese** [comment]
> Hi, when can we expect aarch64 Mac support via homebrew? Thanks

It should be working now; at least it does for me.
https://github.com/Homebrew/homebrew-cask/pull/111654

**Comment by drej1** [comment]
@cadenkriese thanks!

**Comment by charpov** [comment]
Not sure if this is the right place to ask (as opposed to Homebrew), but I like to keep several versions of Java at the same time, e.g., temurin16 and temurin17.  I believe I could do that with AdoptOpenJDK, but not with temurin, and I miss the feature.

**Comment by EugenMayer** [comment]
@charpov IMHO this is the reason to not use homebrew for that. I used `sdkman` under macos and also use `sdkman` under Linux.

You will need to install one java using homebrew (the one hb roles with), same goes for me under arch. But for development I only use the ones I selected and maintain with `sdkman`.

While I use `sdkman` I combine it with `jenv` which is a bit more advanced topic (maintaining a 11 / 17 symlink on the latest release, so I can use that symlink for my IDE and also use `.java-version` in my projects for the cli)

**Comment by timja** [comment]
`asdf` is also another good tool similar to sdkman which you can use for a large selection of developer tools.

**Comment by charpov** [comment]
I still like the fact that Homebrew can update each version within it's own major number.  I use my own script to set `JAVA_HOME` using `java_home`, and have multiple JDKs setup in IntelliJ.  I had a look an `sdkman` once and didn't like it, but I can give it another try.  Hadn't heard of `asdf` before.  Thanks for the pointers.

**Comment by karianna** [comment]
> (When) Will you add it to winget as done with [microsoft/winget-pkgs#25455](https://github.com/microsoft/winget-pkgs/pull/25455) (Java 16)?

This has been done.

**Comment by Okeanos** [comment]
> @charpov IMHO this is the reason to not use homebrew for that. I used https://sdkman.io/ under macos and also use `sdkman` under Linux.

Personally, I used to use the [AdoptOpenJDK-tap](https://github.com/AdoptOpenJDK/homebrew-openjdk) to install multiple JDKs in parallel. With the Adoptium/Temurin release it's slightly different but I have yet to find a reason to use `asdf` or `sdkman` to handle multiple JDKs in parallel when building projects. A minimal [brew bundle](https://github.com/Homebrew/homebrew-bundle) below that installs all available temurin releases:

```Brewfile
tap "homebrew/cask"
tap "homebrew/cask-versions"

cask "temurin"
cask "temurin8"
cask "temurin11"
```

This will install JDK latest, JDK 8, and JDK 11 to `/Library/Java/JavaVirtualMachines/temurin-*.jdk`. Using a particular JDK in a project is achieved with [Maven Toolchains](http://maven.apache.org/plugins/maven-toolchains-plugin/) or [Gradle Toolchains](https://docs.gradle.org/current/userguide/toolchains.html). If you need non-LTS JDK the installation is probably a little more involved but overall the usage should stay the same. For recent version, the [cask discussion](https://github.com/Homebrew/homebrew-cask/pull/109359) reads like all LTS + most recent will be supported as cask-versions.
This is of course only sets up build infrastructure, not runtime infrastructure for Java apps that want a `JAVA_HOME` (something both `sdkman` and `asdf` take care of I think).

**Comment by sfcoy** [comment]
Hi there,

The x64 Mac jdk17 installers have been marked with a ⛔? 
Is that a mistake? A jdk17 installer for Mac is available on the adoptium site.

**Comment by smlambert** [comment]
re: https://github.com/adoptium/adoptium/issues/74#issuecomment-929786768 - Yes I am not sure why the use of ⛔ as installers column was intended to be a general category of activity, including the homebrew activities.

**Comment by karianna** [comment]
Fixed, I swapped the icons around by accident earlier.

**Comment by smlambert** [comment]
Closing as complete.
