### ISSUE TITLE
Bi-weekly Adoptium Community Call - September 15, 2021

### ISSUE THREAD

**Issue by adamfarley** [adoptium/adoptium#76]
**Time**

Wednesday September 15, 2021 3pm-4pm GMT (10am-11am EST/Ontario)

**Location**

https://bluejeans.com/956754991/2833?src=calendarLink

Add this recurring bi-weekly Adoptium Community Call to your calendar, if you wish. Available via the [Adoptium community calendar](https://calendar.google.com/calendar/u/1?cid=Y191YW5ub3VtczVobzBvbGhqazN1bGVjZGtiY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t).

**Overall Purpose**

Mainly to make announcements regarding planned actions that affect the Adopt community
(Emphasis on non-test efforts, as those are covered in AQAvit call on opposite bi-weekly Wednesdays)

Secondary purposes include debate, discussion, and community socializing.

Call to be recorded for reference, and linked in this issue afterwards.

**Proposed Meeting Agenda** 

- September Release discussion
- [Retrospective](https://github.com/adoptium/adoptium/issues/77) date?
- AOB

**Comment by smlambert** [comment]
Meeting [recording link](https://bluejeans.com/s/W1I7zFJalrL)

Minutes:
- A look at some of the project management updates PMC has been doing, noting its still a WIP and will be documented and more properly shared post-release
  - [Sept 2021 Release report](https://app.zenhub.com/workspaces/adoptium-60d93da7bf5a0e0019b82131/board) in Zenhub - get the [zenhub extension](https://www.zenhub.com/extension) for browser for viewing
  - Release checklist (https://github.com/adoptium/adoptium/issues/73) broken out into categories, with owners in each area of focus 
  - A single issue table view of the state of the release for easier communication on status to the community in https://github.com/adoptium/adoptium/issues/74
- No TCK material yet, once it arrives, activities in Temurin-compliance project will kick-off, meantime focus on AQA triage and other areas of focus (installers, containers, etc)
- How to tell what people are taking as AQA triage?  for now, let's add a comment to the AQA triage issues, and Shelley will add names to the release checklist as she sees the comments... (also look at release channel as people will be putting in notes about failures on certain platforms, its a clue to others that they are looking at that platform)
- Ensure you are looking at trss.adoptium.net, and not some cached older trss.adoptopenjdk.net instance for generating the most current release reports for AQA triage
- Short meeting, let's get back to release activities!  Targeted to complete Sept release by Sept 30th.

Link to next community call: https://github.com/adoptium/adoptium/issues/78
