### ISSUE TITLE
Retrospective for September 2021 Releases

### ISSUE THREAD

**Issue by adamfarley** [adoptium/adoptium#77]
This will be a Slack call after the release, with at least a week of notice in the #Release Slack channel.

A bulleted list of all proposed agenda items in this issue (whether at the top or in a comment) will be created on the day of the call, with a list of actions added at the end.

Invited: Everyone.

Time: 3:00pm BST (10am Ontario)
Date: Wednesday, 29th of September
Note: Will be 30 minutes long tops.

URL: https://bluejeans.com/956754991/2833?src=calendarLink

Retrospective Owner Tasks (in order):

- [x] Post this issue's URL on the \#Release Slack channel around the start of the new release.
- [x] Copy actions from the previous retrospective into this issue, while ignoring actions that have an issue link (i.e. clearly-completed actions).
- [x] Wait until all builds have been released, with no clear signs of additional respins.
- [x] Announce the retrospective Slack call's date + time on \#Release at least one full week in advance, and send out meeting invites.
- [x] On the day of the call, compile all of the agenda items into a tick-box list inside a single comment.
- [x] Host the slack call for the retrospective, including:
  - [x] Iterating over the actions from the previous retrospective issue, annotating *both* issues with any issues that have been raised for them.
  - [x] Iterate over the agenda tick-list, ensuring everything gets debated.
  - [x] Create a clear list of actions at the end of the retrospective, including volunteer names.
- [x] Close the issue for the previous retrospective, ensuring that every action is annotated with its conclusion (issue link, ignored, etc).
- [x] Create a new retrospective issue for the next release.
- [x] Set yourself a calendar reminder so that you remember to commence step 1 (in the new issue) just before the next release.

Add proposed agenda items as comments below.

**Comment by adamfarley** [comment]
Meeting Agenda:
(tickbox list, to be populated as people add comments)

Actions:
(tickbox list, to be populated during the meeting)

Actions from previous retrospectives:
(Still being populated. 1 minute pls.)

**Comment by smlambert** [comment]
I will suggest we reschedule this, as I did not give a good heads up to folks who were involved in the release to join.  We held a community call today, but discussed other topics, not a release retrospective.

**Comment by sxa** [comment]
See if we can simplify the `openjdk_release_tool` job in terms of releasing individual platform artefacts and jdk/jre split more simply

**Comment by sxa** [comment]
Look into lockdown process in terms of:
- Lockdown of changes into the build repository - do we need to be this strict? Does it cause any problems holding up changes into the main nightly builds? (Maybe let's see how long it takes us to do the full set of releases on October)
- What should the criteria be for unlocking?
- At what point should we re-enable nightly tests? Perhaps once we've done all the main test runs and are only awaiting TCK competion. Could we do it for one night? What would now be the impact of not doing it even for one night given that we have the TCK executions as the likely limiting factor now?

**Comment by sxa** [comment]
Simplification of installer production process to redude likelihood of errors. Perhaps include more "smoke test" testing of some of our deliverables.

**Comment by sxa** [comment]
Look at access control on the bulid jobs - why are top level `openjdkXX-pipelines` locked down from public access but not the individual platform build pipelines underneath?

**Comment by smlambert** [comment]
What went well?
- Different people focused on various areas of concern (AQA, Temurin-compliance, installers, containers), and having a single view of 'where we are at' via #74)

What could be improved?
- Breakdown the Zenhub workspaces so the performance of the release report is not laggy
- Finishing all the tasks in the release checklist (seems some linger on far past the big ticket items are done)
- Consider branching strategy rather than freeze, for both build and test, for both stability and to enable development to continue, especially if we linger in code freeze for a long time

**Comment by adamfarley** [comment]
Closing. [Next retrospective](https://github.com/adoptium/adoptium/issues/99).
