### ISSUE TITLE
Change java -version/vendor output to be Temurin

### ISSUE THREAD

**Issue by gdams** [adoptium/adoptium#8]
Here is what I've got so far:

## java -version
```bash
./bin/java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+19-202104272346 (build 17+19-202104272346)
OpenJDK 64-Bit Server VM Temurin-17+19-202104272346 (build 17+19-202104272346, mixed mode, sharing)
```

## java -XshowSettings:properties -version
```bash
./bin/java -XshowSettings:properties -version
Property settings:
    file.encoding = ANSI_X3.4-1968
    file.separator = /
    java.class.path = 
    java.class.version = 61.0
    java.home = /java/jdk-linux-hotspot/jdk-17+19
    java.io.tmpdir = /tmp
    java.library.path = /usr/java/packages/lib
        /usr/lib64
        /lib64
        /lib
        /usr/lib
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 17+19-202104272346
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 17
    java.vendor = Eclipse Foundation
    java.vendor.url = https://adoptium.net/
    java.vendor.url.bug = https://github.com/adoptium/adoptium-support/issues
    java.vendor.version = Temurin-17+19-202104272346
    java.version = 17
    java.version.date = 2021-09-14
    java.vm.compressedOopsMode = 32-bit
    java.vm.info = mixed mode, sharing
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 17
    java.vm.vendor = Eclipse Foundation
    java.vm.version = 17+19-202104272346
    jdk.debug = release
    line.separator = \n 
    os.arch = amd64
    os.name = Linux
    os.version = 4.19.121-linuxkit
    path.separator = :
    sun.arch.data.model = 64
    sun.boot.library.path = /java/jdk-linux-hotspot/jdk-17+19/lib
    sun.cpu.endian = little
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.launcher = SUN_STANDARD
    sun.jnu.encoding = ANSI_X3.4-1968
    sun.management.compiler = HotSpot 64-Bit Tiered Compilers
    sun.stderr.encoding = ANSI_X3.4-1968
    sun.stdout.encoding = ANSI_X3.4-1968
    user.country = US
    user.dir = /java/jdk-linux-hotspot/jdk-17+19
    user.home = /root
    user.language = en
    user.name = root
```

**Comment by mmilinkov** [comment]
To comply with the Eclipse Foundation project trademark guidelines, please s/Temurin/Eclipse Temurin/
Thanks.

**Comment by tellison** [comment]
@mmilinkov I'm not sure that having a whitespace in there will be possible, as it will cause version vendor string parsers to fail.
Best effort will be, for example, `Eclipse-Temurin-17+19-202104272346`

**Comment by tellison** [comment]
Just to be 100% clear: there is no debate that the binaries will be referred to as "Eclipse Temurin", this `java.vendor.version` property is a **build identifier**.

Making the identifier longer with a prefix is tiresome, but not the end of the world.  Adding a whitespace to the identifier likely would break users who have chosen to parse the identifier (even though the format is not dictated). Indeed, we may find that we have to use `EclipseTemurin-` to avoid adding another hyphen which users may be interpreting as a field separator.

**Comment by mmilinkov** [comment]
Okay, so no whitespace then. 

But now I am struggling a bit with what the right answer is here. My feeling is (and please correct me if I'm wrong) is that the string that appears when you type in 'java -version' is going to be widely thought of by developers as the true name for the distribution. It's going to be what people call it. Do we want that to be Adoptium or Temurin? And if the answer is Temurin, I really do think that the Eclipse project branding guidelines need to be followed for such a ubiquitous usage. Your camel case suggestion could end up being the best option available.

**Comment by tellison** [comment]
> My feeling is (and please correct me if I'm wrong) is that the string that appears when you type in 'java -version' is going to be widely thought of by developers as the true name for the distribution.

The build identifier will indeed appear in the `java -version`, and of course we need that identifier to be able to track the individual binary provenance.

As to whether it is going to be "widely thought of by developers" by that identifier prefix - well, I think that name more probably depends on how we depict the name on the website, documentation, marketing, etc. and that will indeed always be "Eclipse Temurin".  Either way, as a lazy developer myself, I cannot promise it won't get abbreviated to just "Temurin".

FWIW
Azul Zulu prints the following:
```
$ ./bin/java -version
openjdk version "11.0.11" 2021-04-20 LTS
OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.48+21-CA (build 11.0.11+9-LTS, mixed mode)
```

and Amazon Corretto prints
```
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.7.10.1 (build 11.0.7+10-LTS, mixed mode)
```
as things stand, Eclipse Temurin would be
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+19-202104272346 (build 17+19-202104272346)
OpenJDK 64-Bit Server VM Temurin-17+19-202104272346 (build 17+19-202104272346, mixed mode, sharing)
```

/cc:  @giltene who expressed an interest in this topic

**Comment by mmilinkov** [comment]
Perhaps @waynebeaton can comment. 

I hate it when I come across as being pedantic, but it feels to me like using 'Temurin' alone would not comply with our project trademark guidelines.

**Comment by waynebeaton** [comment]
This walks a bit of line. We have some flexibility in technical namespaces; a hypothetical command-line tool could, for example, use the short name alone, but a hypothetical "about" dialog, `man` page, or help would use the formal name starting with the brand ("Eclipse"). 

The general rule is that you use the formal name (e.g., "Eclipse Temurin") in "end user" content (e.g., websites, documentation, about dialogs, `man` pages, ...), and the brand and short name are used in technical namespaces where possible (e.g., Java packages, OSGi bundles, etc. named "org.eclipse.temurin.*"), unless doing so is unnatural, unnecessarily burdensome, or technically impossible.

My strong preference is to include "Eclipse" in the name, but I'm inclined to lean towards "EclipseTemurin" being unnatural in this context, and recommend that we run with "Temurin".

**Comment by waynebeaton** [comment]
> but a hypothetical "about" dialog, `man` page, or _help_ would use the formal name starting with the brand ("Eclipse").

`$ java --help` doesn't list a project/product name at all; I'm **not** suggesting that Eclipse Temurin should.

**Comment by gdams** [comment]
Closing for now, we've made the changes and can review before we push out our first release
