### ISSUE TITLE
October 2021 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#81]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922.  Primary platforms (x64 Linux/Windows/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).

👍 results in these Tables means the activity has successfully completed.
⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.
⛔ means there is no build planned for that version/platform combination. 
📂 means activity not yet started.

### JDK8
| Platforms | Link to Build | jdk8 AQA  | jdk8/jre8 TCK | jdk8 installers | jdk8 containers | Notes | 
| ----- | ----- | ----- | ----- | ----- | ----- | ----- | 
| **x64 Linux** | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1827/artifact/target/linux/x64/hotspot) | 👍  |  👍    | 📂  | 👍  |   | 
| **x64 Windows** | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1827/artifact/target/windows/x64/hotspot) |   👍      |  👍    | 👍  | 👍  |   | 
| **x64 Mac** | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1827/artifact/target/mac/x64/hotspot) |   👍   | 👍    | 📂  | ⛔ |   | 
| aarch64 Linux | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1827/artifact/target/linux/aarch64/hotspot) | 👍     |  👍    | 📂  | 👍  |   | 
| ppcle64 Linux  | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1827/artifact/target/linux/ppc64le/hotspot) |  👍      |  👍    | 📂  | 👍  |   | 
| ppc64 AIX | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1827/artifact/target/aix/ppc64/hotspot) |  👍   | 👍   | ⛔ | ⛔ |   | 
| x32 Windows | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1827/artifact/target/windows/x86-32/hotspot) | 👍     | 👍   | 👍  | ⛔ |   | 
| arm32 Linux | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1844/artifact/target/linux/arm/hotspot) |   👍      |  👍    | 📂  | 👍  |   | 
| sparcv9 solaris | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1827/artifact/target/solaris/sparcv9/hotspot) |  👍    | ⏳   | ⛔  | ⛔ | Most failures due to underpowered machine (RAM)  | 
| x86 solaris | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1827/artifact/target/solaris/x64/hotspot) |  👍   | ⏳   | ⛔  | ⛔ | Recommend fixing - [Setting nativepath](https://github.com/adoptium/aqa-tests/issues/1964) and [Revert/Fix stf naming?](https://github.com/adoptium/aqa-tests/issues/2949) - then a post release rerun of AQA |
| x64 alpine-Linux | build xxxx | 📂  |  📂    | 📂  | 📂  |  This will be a headless build | 

### JDK11
| Platforms | Link to Build | jdk11 AQA  | jdk11/jre11 TCK | jdk11 installers | jdk11 containers | Notes | 
| ----- | ----- | ----- | ----- | ----- | ----- | ----- | 
| **x64 Linux** | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/artifact/target/linux/x64/hotspot/) | 👍      |  👍    | 📂  | 👍  |   | 
| **x64 Windows** | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/artifact/target/windows/x64/hotspot/) |   👍      |  👍    | 👍  | 👍  |   | 
| **x64 Mac** | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/artifact/target/mac/x64/hotspot/) |   👍    | 👍    | 📂  | ⛔ |   | 
| aarch64 Linux | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/artifact/target/linux/aarch64/hotspot/) | 👍      |  👍    | 📂  | 👍  |   | 
| ppcle64 Linux  | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/artifact/target/linux/ppc64le/hotspot/) |  👍      |  👍   | 📂  | 👍  |   | 
| s390x Linux | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/artifact/target/linux/s390x/hotspot/) |   👍      |  👍   | 📂  | 👍  |   | 
| ppc64 AIX | [1022](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot/1022/) |   👍    | 👍  | ⛔ |⛔  |  First build failed 1022 is a respin | 
| x32 Windows | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/artifact/target/windows/x86-32/hotspot/) | 👍      | 👍   | 👍  | ⛔ |   | 
| arm32 Linux | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/artifact/target/linux/arm/hotspot/) |   👍      |  👍    | 📂  | 👍  |   | 
| x64 alpine-Linux | [Builds](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/artifact/target/alpine-linux/x64/hotspot/) | 👍      |  👍    | 📂  | 👍  |  This will be a headless build | 

### JDK17
| Platforms | Link to Build | jdk17 AQA  | jdk17 TCK | jdk17 installers | jdk17 containers | Notes | 
| ----- | ----- | ----- | ----- | ----- | ----- | ----- | 
| **x64 Linux** | [218](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/218/)| 👍      |  👍    | 📂  | 👍  |   | 
| **x64 Windows** | [218](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/218/) |   👍      |  👍    | 👍  | 👍  |   | 
| **x64 Mac** | [218](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/218/) |   👍    | 👍    | 📂  | ⛔ |   | 
| aarch64 Linux | [218](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/218/) | 👍      |  👍    | 📂  | 👍  |   | 
| ppcle64 Linux  | [218](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/218/) |  👍      |  👍    | 📂  | 👍  |   | 
| s390x Linux | [218](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/218/) |   👍     |  👍    | 📂  | 👍  |   | 
| ppc64 AIX | [218](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/218/)|   👍    | 📂   | ⛔ |⛔  |   | 
| x32 Windows | [218](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/218/) | 👍      | 👍   | 👍   | ⛔ |   | 
| arm32 Linux | [218](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/218/) |   👍      |  👍    | 📂  | 👍  |   | 
| x64 alpine-Linux | [218](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/218/) | 👍      |  👍    | 📂  | 👍  | This will be a headless build | 
| aarch64 Mac | [218](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/218/) |  👍    | 👍   | 📂  | ⛔ |   |

**Comment by Merlijnv** [comment]
when do u expect to release the linux image for 8u312?

**Comment by jgkirschbaum** [comment]
> when do u expect to release the linux image for 8u312?

They are already there: https://adoptium.net/releases.html?variant=openjdk8&jvmVariant=hotspot

**Comment by Merlijnv** [comment]
> 
> 
> > when do u expect to release the linux image for 8u312?
> 
> They are already there: https://adoptium.net/releases.html?variant=openjdk8&jvmVariant=hotspot

I mean the linux (docker) image so on https://hub.docker.com/_/eclipse-temurin

**Comment by d-schmidt** [comment]
Are there no JRE images anymore? 11 did have them. What about 17?

**Comment by Arktikus-git** [comment]
When do you expect to release the 17.0.1+12 for x64 alpine-Linux?

**Comment by alexbde** [comment]
> Are there no JRE images anymore? 11 did have them. What about 17?

See https://github.com/docker-library/docs/blob/master/eclipse-temurin/README.md#creating-a-jre-using-jlink

**Comment by flyingcircle** [comment]
> > when do u expect to release the linux image for 8u312?
> 
> They are already there: https://adoptium.net/releases.html?variant=openjdk8&jvmVariant=hotspot

No, the links to the JRE still point to 8u302. Only some of the links point to the new version.

**Comment by minduch** [comment]
When would be an estimated date for the availability of the JRE versions of 1.8u812, 11.0.13, 17.0.1 for the supported platforms (Linux, Windows x64, Windows x86, ...)?

**Comment by sxa** [comment]
I'm hoping to get the JREs for 8u312 and 11.0.13 out tomorrow. Linux/x64 ones are already there.

**Comment by rubenporras** [comment]
Is there an estimated date for availability of the JDK17 for ppc64 AIX?

**Comment by mirkowein** [comment]
+1 for JRE11 for ppc64 AIX?

Thanks !

**Comment by minduch** [comment]
When would be an estimated date for the availability of the JRE version of 17.0.1 for Windows x64?

**Comment by karianna** [comment]
> @sxa: When would be an estimated date for the availability of the JRE version of 17.0.1 for Windows x64?

We're not producing JREs for 17 (at this stage although we're reviewing this decision).  See https://blog.adoptium.net/2021/08/using-jlink-in-dockerfiles/ in the mean time

**Comment by sxa** [comment]
> Is there an estimated date for availability of the JDK17 for ppc64 AIX?

There is a specific problem with it that we are awaiting a resolution on, and the resolution is outside Adoptium's control so I cannot give an ETA unfortunately.

**Comment by sxa** [comment]
> > @sxa: When would be an estimated date for the availability of the JRE version of 17.0.1 for Windows x64?
> 
> We're not producing JREs for 17 (at this stage although we're reviewing this decision). See https://blog.adoptium.net/2021/08/using-jlink-in-dockerfiles/ in the mean time

Also https://blog.adoptium.net/2021/10/jlink-to-produce-own-runtime goes into a bit more detail on the process and options for producing a cut down runtime (and is independent of docker)

**Comment by sxa** [comment]
> +1 for JRE11 for ppc64 AIX?

Did you really mean 11? it's already [on the web site](https://adoptium.net/releases.html?variant=openjdk11&jvmVariant=hotspot)

**Comment by mirkowein** [comment]
> > +1 for JRE11 for ppc64 AIX?
> 
> Did you really mean 11? it's already [on the web site](https://adoptium.net/releases.html?variant=openjdk11&jvmVariant=hotspot) [EDIT: Hmmm ok only 11.0.12 is there, not 11.0.13. I'll get that fixed now!]

Now it's there! Thanks, that helps me a lot.

**Comment by sxa** [comment]
> Now it's there! Thanks, that helps me a lot.

And thanks to you for telling us about it :-)

**Comment by smlambert** [comment]
Closing as complete.
