### ISSUE TITLE
Provide ECA info in issues for newcomer

### ISSUE THREAD

**Issue by hendrikebbers** [adoptium/adoptium#86]
Since this is a general issues over all repos I created it directly in the Adoptium repo. We have a template for 'good first issue' issues that can be found for example [here](https://github.com/adoptium/documentation-services/issues/10). The template has been created at AdoptOpenJDK and was migrated to Adoptium. Therefore information regarding the ECA is missing. I already created https://github.com/AdoptOpenJDK/website-adoptium-documentation/issues/34 to have a step by step tutorial for newcomers in future. This tutorial should be referenced in the template and the ECA check should be added to the checklist of the issue.

**Comment by hendrikebbers** [comment]
First draft: https://github.com/adoptium/documentation-services/issues/10

**Comment by smlambert** [comment]
Documentation to help with signing ECA is now available via https://github.com/adoptium/documentation/blob/main/documentation-documentation/eca-sign-off.adoc 

Just need to explicitly link to it from the new contributor template now...

**Comment by tellison** [comment]
See also https://github.com/adoptium/.github/pull/6

Repos have contributing guides now
