### ISSUE TITLE
Temurin Release 11.0.13+8 Triage

### ISSUE THREAD

**Issue by karianna** [adoptium/adoptium#87]
#### Release Summary Report for openjdk11-pipeline 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=616f3519c6182d021788d2c3&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=616f3519c6182d021788d2c3) 
Jenkins Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/ 
Started by user Stewart X Addison at 19/10/2021, 22:02:18 

 --- 

[**create_installer_linux**](undefined) ❌ undefined ❌ -  **OK to Release** - This shouldn't be part of a TRSS report?
[**create_installer_mac**](undefined) ❌ undefined ❌  - **OK to Release** - This shouldn't be part of a TRSS report?
[**create_installer_windows**](undefined) ❌ undefined ❌ -  **OK to Release** - This shouldn't be part of a TRSS report?
[**jdk11u-aix-ppc64-hotspot**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot/1021/) ❌ FAILURE ❌ - Respin [1022](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot/1022/)
[**sign_build**](undefined) ❌ undefined ❌ -  **OK to Release** - This shouldn't be part of a TRSS report?
[**sign_installer**](undefined) ❌ undefined ❌ -  **OK to Release** - This shouldn't be part of a TRSS report?

 --- 

[**Test_openjdk11_hs_extended.openjdk_aarch64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_aarch64_linux/45/) ⚠️ UNSTABLE ⚠️ - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947948315)
jdk_management_0 => [deep history 1/6 passed](https://trss.adoptium.net/deepHistory?testId=616f82acc6182d02178a18e8) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8179c6182d02178a1107&buildName=Test_openjdk11_hs_extended.openjdk_aarch64_linux&testId=616f82acc6182d02178a18e8&testName=jdk_management_0) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947948315)
jdk_tools_1 => [deep history 4/6 passed](https://trss.adoptium.net/deepHistory?testId=616f82acc6182d02178a18fb) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8179c6182d02178a1107&buildName=Test_openjdk11_hs_extended.openjdk_aarch64_linux&testId=616f82acc6182d02178a18fb&testName=jdk_tools_1) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947948315)
jdk_management_1 => [deep history 1/6 passed](https://trss.adoptium.net/deepHistory?testId=616f82acc6182d02178a18f2) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8179c6182d02178a1107&buildName=Test_openjdk11_hs_extended.openjdk_aarch64_linux&testId=616f82acc6182d02178a18f2&testName=jdk_management_1) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947948315)
jdk_tools_0 => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=616f82acc6182d02178a18f1) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8179c6182d02178a1107&buildName=Test_openjdk11_hs_extended.openjdk_aarch64_linux&testId=616f82acc6182d02178a18f1&testName=jdk_tools_0) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947948315)

[**Test_openjdk11_hs_extended.openjdk_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_arm_linux/17/) ⚠️ UNSTABLE ⚠️ - **OK to Release** - Wrapper Target

[**Test_openjdk11_hs_extended.openjdk_arm_linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_arm_linux_testList_0/11/) ⚠️ UNSTABLE ⚠️ - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947957122)
jvm_compiler_2 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=616f5173c6182d021789478b) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f504fc6182d021789425c&buildName=Test_openjdk11_hs_extended.openjdk_arm_linux_testList_0&testId=616f5173c6182d021789478b&testName=jvm_compiler_2) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947957122)
jdk_management_2 => [deep history 2/3 passed](https://trss.adoptium.net/deepHistory?testId=616f5173c6182d0217894797) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f504fc6182d021789425c&buildName=Test_openjdk11_hs_extended.openjdk_arm_linux_testList_0&testId=616f5173c6182d0217894797&testName=jdk_management_2) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947957122)

[**Test_openjdk11_hs_extended.openjdk_arm_linux_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_arm_linux_testList_1/11/) ⚠️ UNSTABLE ⚠️ - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947957122)
jdk_jfr_2 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=616f516cc6182d021789473c) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f504fc6182d021789425b&buildName=Test_openjdk11_hs_extended.openjdk_arm_linux_testList_1&testId=616f516cc6182d021789473c&testName=jdk_jfr_2) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947957122)

[**Test_openjdk11_hs_extended.openjdk_arm_linux_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_arm_linux_testList_2/11/) ⚠️ UNSTABLE ⚠️ - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947957122)
jdk_nio_2 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=616f517bc6182d02178947bc) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f504fc6182d021789425d&buildName=Test_openjdk11_hs_extended.openjdk_arm_linux_testList_2&testId=616f517bc6182d02178947bc&testName=jdk_nio_2) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947957122)
jdk_beans_2 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=616f517bc6182d02178947bd) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f504fc6182d021789425d&buildName=Test_openjdk11_hs_extended.openjdk_arm_linux_testList_2&testId=616f517bc6182d02178947bd&testName=jdk_beans_2) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947957122) 
jdk_imageio_2 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=616f517bc6182d02178947c1) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f504fc6182d021789425d&buildName=Test_openjdk11_hs_extended.openjdk_arm_linux_testList_2&testId=616f517bc6182d02178947c1&testName=jdk_imageio_2) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947957122) 

[**Test_openjdk11_hs_extended.openjdk_s390x_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_s390x_linux/42/) ⚠️ UNSTABLE ⚠️ - **OK to Release** - Wrapper Target

[**Test_openjdk11_hs_extended.openjdk_s390x_linux_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_s390x_linux_testList_1/16/) ⚠️ UNSTABLE ⚠️
jdk_net_1 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=616ffc55c6182d02178e3be1) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616ffb9bc6182d02178e2b0a&buildName=Test_openjdk11_hs_extended.openjdk_s390x_linux_testList_1&testId=616ffc55c6182d02178e3be1&testName=jdk_net_1) - **OK to release** [1596](https://github.com/adoptium/aqa-tests/issues/1596)

[**Test_openjdk11_hs_extended.openjdk_x86-32_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-32_windows/42/) ⚠️ UNSTABLE ⚠️ - **OK to Release** - Wrapper Target

[**Test_openjdk11_hs_extended.openjdk_x86-32_windows_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-32_windows_testList_1/17/) ⚠️ UNSTABLE ⚠️
jdk_jfr_2 => [deep history 3/4 passed](https://trss.adoptium.net/deepHistory?testId=616fa10cc6182d02178ac78c) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616fa019c6182d02178abd26&buildName=Test_openjdk11_hs_extended.openjdk_x86-32_windows_testList_1&testId=616fa10cc6182d02178ac78c&testName=jdk_jfr_2) - **OK to release** - Not a blocker [3053](https://github.com/adoptium/aqa-tests/issues/3053)

[**Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux/3/) ⚠️ UNSTABLE ⚠️ - **OK to Release** - Wrapper Target

[**Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_0/2/) ⚠️ UNSTABLE ⚠️
jdk_net_0 => [deep history 0/2 passed](https://trss.adoptium.net/deepHistory?testId=616f8f2ec6182d02178a5cd3) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8d9ac6182d02178a4cce&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_0&testId=616f8f2ec6182d02178a5cd3&testName=jdk_net_0) - **Likely OK to Release** - [3055](https://github.com/adoptium/aqa-tests/issues/3055)
jdk_security4_0 => [deep history 0/2 passed](https://trss.adoptium.net/deepHistory?testId=616f8f2ec6182d02178a5ce0) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8d9ac6182d02178a4cce&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_0&testId=616f8f2ec6182d02178a5ce0&testName=jdk_security4_0) - **Likely OK to Release** - [3056](https://github.com/adoptium/aqa-tests/issues/3056)

[**Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_1/2/) ⚠️ UNSTABLE ⚠️
jdk_net_1 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=616f8f3fc6182d02178a5d67) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8d9ac6182d02178a4cd1&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_1&testId=616f8f3fc6182d02178a5d67&testName=jdk_net_1) - **Likely OK to Release** - [3055](https://github.com/adoptium/aqa-tests/issues/3055)
jdk_management_1 => [deep history 0/2 passed](https://trss.adoptium.net/deepHistory?testId=616f8f3fc6182d02178a5d68) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8d9ac6182d02178a4cd1&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_1&testId=616f8f3fc6182d02178a5d68&testName=jdk_management_1) - **OK To release** - [Upstream issue](https://bugs.openjdk.java.net/browse/JDK-8271466)

[**Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_2/2/) ⚠️ UNSTABLE ⚠️
jdk_security_infra_0 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=616f8f37c6182d02178a5d1b) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8d9ac6182d02178a4cd0&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_2&testId=616f8f37c6182d02178a5d1b&testName=jdk_security_infra_0) - **Likely due to cert update** - similar issue last release [2074](https://github.com/adoptium/aqa-tests/issues/2074)
jdk_tools_1 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=616f8f37c6182d02178a5d16) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8d9ac6182d02178a4cd0&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_2&testId=616f8f37c6182d02178a5d16&testName=jdk_tools_1) **OK to release** - [upstream issue](https://bugs.openjdk.java.net/browse/JDK-8081569)
jdk_management_0 => [deep history 0/2 passed](https://trss.adoptium.net/deepHistory?testId=616f8f37c6182d02178a5d13) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8d9ac6182d02178a4cd0&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_2&testId=616f8f37c6182d02178a5d13&testName=jdk_management_0) - **OK To release** - [Upstream issue](https://bugs.openjdk.java.net/browse/JDK-8271466)
jdk_security4_1 => [deep history 0/2 passed](https://trss.adoptium.net/deepHistory?testId=616f8f37c6182d02178a5d12) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8d9ac6182d02178a4cd0&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_alpine-linux_testList_2&testId=616f8f37c6182d02178a5d12&testName=jdk_security4_1) - **Likely OK to Release** - [3056](https://github.com/adoptium/aqa-tests/issues/3056) 

[**Test_openjdk11_hs_extended.openjdk_x86-64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_linux/42/) ⚠️ UNSTABLE ⚠️ - **OK to Release** - Wrapper Target

[**Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/16/) ⚠️ UNSTABLE ⚠️ - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947907511)
jdk_security4_0 => [deep history 2/4 passed](https://trss.adoptium.net/deepHistory?testId=616f853dc6182d02178a2b1d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f83f3c6182d02178a1e62&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0&testId=616f853dc6182d02178a2b1d&testName=jdk_security4_0) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947907511)
jdk_build_1 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=616f853dc6182d02178a2b23) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f83f3c6182d02178a1e62&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0&testId=616f853dc6182d02178a2b23&testName=jdk_build_1) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947907511)
jdk_tools_0 => [deep history 1/4 passed](https://trss.adoptium.net/deepHistory?testId=616f853dc6182d02178a2b1f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f83f3c6182d02178a1e62&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0&testId=616f853dc6182d02178a2b1f&testName=jdk_tools_0) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947907511)
jdk_security_infra_1 => [deep history 2/4 passed](https://trss.adoptium.net/deepHistory?testId=616f853dc6182d02178a2b27) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f83f3c6182d02178a1e62&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0&testId=616f853dc6182d02178a2b27&testName=jdk_security_infra_1) - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947907511)

[**Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_2/16/) ⚠️ UNSTABLE ⚠️
jdk_build_0 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=616f854cc6182d02178a2bad) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f83f3c6182d02178a1e65&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_2&testId=616f854cc6182d02178a2bad&testName=jdk_build_0) 

[**Test_openjdk11_hs_extended.openjdk_x86-64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_mac/44/) ⚠️ UNSTABLE ⚠️ - **OK to Release** - Wrapper Target

[**Test_openjdk11_hs_extended.openjdk_x86-64_mac_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_mac_testList_1/16/) ⚠️ UNSTABLE ⚠️
jdk_time_0 => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6170339bc6182d02178fc4bd) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=617032bbc6182d02178fbd3c&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_mac_testList_1&testId=6170339bc6182d02178fc4bd&testName=jdk_time_0) - **More investigation needed** [3051](https://github.com/adoptium/aqa-tests/issues/3051)
jdk_time_1 => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6170339bc6182d02178fc4be) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=617032bbc6182d02178fbd3c&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_mac_testList_1&testId=6170339bc6182d02178fc4be&testName=jdk_time_1) - **More investigation needed** [3051](https://github.com/adoptium/aqa-tests/issues/3051)

[**Test_openjdk11_hs_extended.perf_x86-32_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.perf_x86-32_windows/37/) ⚠️ UNSTABLE ⚠️
renaissance-chi-square_0 => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=616f9fd7c6182d02178abaf4) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f9eb7c6182d02178ab5b3&buildName=Test_openjdk11_hs_extended.perf_x86-32_windows&testId=616f9fd7c6182d02178abaf4&testName=renaissance-chi-square_0) - **OK to Release** - [2155](https://github.com/adoptium/aqa-tests/issues/2155)
renaissance-movie-lens_0 => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=616f9fd7c6182d02178abafd) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f9eb7c6182d02178ab5b3&buildName=Test_openjdk11_hs_extended.perf_x86-32_windows&testId=616f9fd7c6182d02178abafd&testName=renaissance-movie-lens_0) - **OK to Release** - [2155](https://github.com/adoptium/aqa-tests/issues/2155) 
renaissance-als_0 => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=616f9fd7c6182d02178abafc) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f9eb7c6182d02178ab5b3&buildName=Test_openjdk11_hs_extended.perf_x86-32_windows&testId=616f9fd7c6182d02178abafc&testName=renaissance-als_0) - **OK to Release** - [2155](https://github.com/adoptium/aqa-tests/issues/2155)
renaissance-log-regression_0 => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=616f9fd7c6182d02178abafa) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f9eb7c6182d02178ab5b3&buildName=Test_openjdk11_hs_extended.perf_x86-32_windows&testId=616f9fd7c6182d02178abafa&testName=renaissance-log-regression_0) - **OK to Release** - [2155](https://github.com/adoptium/aqa-tests/issues/2155)
renaissance-gauss-mix_0 => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=616f9fd7c6182d02178abaf9) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f9eb7c6182d02178ab5b3&buildName=Test_openjdk11_hs_extended.perf_x86-32_windows&testId=616f9fd7c6182d02178abaf9&testName=renaissance-gauss-mix_0) - **OK to Release** - [2155](https://github.com/adoptium/aqa-tests/issues/2155)
renaissance-dec-tree_0 => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=616f9fd7c6182d02178abaf6) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f9eb7c6182d02178ab5b3&buildName=Test_openjdk11_hs_extended.perf_x86-32_windows&testId=616f9fd7c6182d02178abaf6&testName=renaissance-dec-tree_0) - **OK to Release** - [2155](https://github.com/adoptium/aqa-tests/issues/2155)

[**Test_openjdk11_hs_extended.system_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.system_arm_linux/120/) ❌ FAILURE ❌ - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947906352)

[**Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux/6/) ⚠️ UNSTABLE ⚠️
cmdLineTester_libpathTestRtfChild_0 => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=616f8d8bc6182d02178a4cb4) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8bf4c6182d02178a4818&buildName=Test_openjdk11_hs_sanity.functional_x86-64_alpine-linux&testId=616f8d8bc6182d02178a4cb4&testName=cmdLineTester_libpathTestRtfChild_0) - **OK to release as we are headless** - [3057](https://github.com/adoptium/aqa-tests/issues/3057)

[**Test_openjdk11_hs_sanity.openjdk_x86-32_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-32_windows/578/) ⚠️ UNSTABLE ⚠️
jdk_lang_2 => [deep history 0/12 passed](https://trss.adoptium.net/deepHistory?testId=616f9ff0c6182d02178abb79) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f9eb7c6182d02178ab5b7&buildName=Test_openjdk11_hs_sanity.openjdk_x86-32_windows&testId=616f9ff0c6182d02178abb79&testName=jdk_lang_2) - Java 17 exclude probably needs to come to 11 as well - [3002](https://github.com/adoptium/aqa-tests/issues/3002)

[**Test_openjdk11_hs_sanity.openjdk_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-64_alpine-linux/8/) ⚠️ UNSTABLE ⚠️
jdk_lang_0 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=616f8db7c6182d02178a4e73) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8bf4c6182d02178a481e&buildName=Test_openjdk11_hs_sanity.openjdk_x86-64_alpine-linux&testId=616f8db7c6182d02178a4e73&testName=jdk_lang_0) - **Likely OK to release** - [3058](https://github.com/adoptium/aqa-tests/issues/3058)
jdk_lang_1 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=616f8db7c6182d02178a4e77) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=616f8bf4c6182d02178a481e&buildName=Test_openjdk11_hs_sanity.openjdk_x86-64_alpine-linux&testId=616f8db7c6182d02178a4e77&testName=jdk_lang_1) - **Likely OK to release** - [3058](https://github.com/adoptium/aqa-tests/issues/3058)

[**Test_openjdk11_hs_sanity.system_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.system_arm_linux/120/) ❌ FAILURE ❌ - **OK To Release** - [Detailed Triage](https://github.com/adoptium/adoptium/issues/87#issuecomment-947906352)

**Comment by smlambert** [comment]
Closing as complete
