### ISSUE TITLE
Temurin Release jdk-17.0.1+12 Triage

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/adoptium#89]
#### Release Summary Report for openjdk17-pipeline 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=61700b73c6182d02178ec9ed&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=61700b73c6182d02178ec9ed) 
Jenkins Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/218/ 
Started by user George Adams at 20/10/2021, 13:28:31 

 --- 

[**create_installer_linux**](undefined) ❌ undefined ❌

[**create_installer_mac**](undefined) ❌ undefined ❌

[**create_installer_windows**](undefined) ❌ undefined ❌

[**jdk17u-windows-x64-hotspot_SmokeTests**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-windows-x64-hotspot_SmokeTests/10/) ⚠️ UNSTABLE ⚠️

[**sign_build**](undefined) ❌ undefined ❌

[**sign_installer**](undefined) ❌ undefined ❌

 --- 

[**Test_openjdk17_hs_extended.openjdk_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux/20/) ⚠️ UNSTABLE ⚠️ **Ok to release**

[**Test_openjdk17_hs_extended.openjdk_arm_linux_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_1/16/) ⚠️ UNSTABLE ⚠️ **Ok to release**
jdk_vector_2 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=61702c3fc6182d02178f9af4) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61702b73c6182d02178f9170&buildName=Test_openjdk17_hs_extended.openjdk_arm_linux_testList_1&testId=61702c3fc6182d02178f9af4&testName=jdk_vector_2) 

`jdk/incubator/vector/Byte128VectorLoadStoreTests.java.Byte128VectorLoadStoreTests`
Known issue https://github.com/adoptium/aqa-tests/issues/2874

[**Test_openjdk17_hs_extended.openjdk_arm_linux_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_2/16/) ⚠️ UNSTABLE ⚠️ **Ok to release**
jdk_beans_2 => [deep history 1/3 passed](https://trss.adoptium.net/deepHistory?testId=61702c4fc6182d02178f9b4d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61702b73c6182d02178f9173&buildName=Test_openjdk17_hs_extended.openjdk_arm_linux_testList_2&testId=61702c4fc6182d02178f9b4d&testName=jdk_beans_2) 

```
java/beans/PropertyChangeSupport/Test4682386.java.Test4682386
java/beans/XMLEncoder/Test4631471.java.Test4631471
java/beans/XMLEncoder/Test4903007.java.Test4903007
java/beans/XMLEncoder/javax_swing_DefaultCellEditor.java.javax_swing_DefaultCellEditor
java/beans/XMLEncoder/javax_swing_JTree.java.javax_swing_JTree
```

jdk_imageio_2 => [deep history 2/4 passed](https://trss.adoptium.net/deepHistory?testId=61702c4fc6182d02178f9b68) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61702b73c6182d02178f9173&buildName=Test_openjdk17_hs_extended.openjdk_arm_linux_testList_2&testId=61702c4fc6182d02178f9b68&testName=jdk_imageio_2) 

`javax/imageio/plugins/shared/ImageWriterCompressionTest.java.ImageWriterCompressionTest`

jdk_beans_2 and jdk_imageio_2 both failed on test-docker-ubuntu2004-armv7l-1 but have been shown to pass previously on build-equinix-ubuntu1604-armv7l-1. Rerunning on build-equinix-ubuntu1604-armv7l-1 at https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1921/console Test passed 

[**Test_openjdk17_hs_extended.openjdk_ppc64_aix**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix/21/) ⚠️ UNSTABLE ⚠️ **Ok to release**

[**Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0/10/) ⚠️ UNSTABLE ⚠️ **Ok to release**
jdk_net_0 => [deep history 0/2 passed](https://trss.adoptium.net/deepHistory?testId=6170bee8c6182d0217927541) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170bdc3c6182d02179267b0&buildName=Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0&testId=6170bee8c6182d0217927541&testName=jdk_net_0) 
Known issue https://github.com/adoptium/aqa-tests/issues/2246

[**Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_1/10/) ⚠️ UNSTABLE ⚠️ **Ok to release**
jdk_beans_1 => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6170bee0c6182d02179274e8) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170bdc3c6182d02179267af&buildName=Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_1&testId=6170bee0c6182d02179274e8&testName=jdk_beans_1) 
Raised issue https://github.com/adoptium/aqa-tests/issues/3073

jdk_net_1 => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6170bee0c6182d02179274e1) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170bdc3c6182d02179267af&buildName=Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_1&testId=6170bee0c6182d02179274e1&testName=jdk_net_1) 
jdk_nio_1 => [deep history 0/2 passed](https://trss.adoptium.net/deepHistory?testId=6170bee0c6182d02179274e2) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170bdc3c6182d02179267af&buildName=Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_1&testId=6170bee0c6182d02179274e2&testName=jdk_nio_1) 
Known issue https://github.com/adoptium/aqa-tests/issues/2246

[**Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_2/10/) ⚠️ UNSTABLE ⚠️ **Ok to release**
jdk_nio_0 => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6170bed8c6182d02179274a5) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170bdc3c6182d02179267ae&buildName=Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_2&testId=6170bed8c6182d02179274a5&testName=jdk_nio_0) 
Known issue https://github.com/adoptium/aqa-tests/issues/2535

[**Test_openjdk17_hs_extended.openjdk_ppc64le_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64le_linux/30/) ⚠️ UNSTABLE ⚠️ **Ok to release**

[**Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_0/17/) ⚠️ UNSTABLE ⚠️ **Ok to release**
jdk_jfr_1 => [deep history 2/3 passed](https://trss.adoptium.net/deepHistory?testId=61705325c6182d0217905507) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61705226c6182d021790491c&buildName=Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_0&testId=61705325c6182d0217905507&testName=jdk_jfr_1) 
Rerunning on test-osuosl-ubuntu2004-ppc64le-1 https://ci.adoptopenjdk.net/job/Grinder/1928/console
Test passed 👍🏻 

[**Test_openjdk17_hs_extended.openjdk_x86-32_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows/32/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0/12/) ⚠️ UNSTABLE ⚠️
jvm_compiler_2 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=61704a7bc6182d0217902d9f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=617049bac6182d0217902732&buildName=Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0&testId=61704a7bc6182d0217902d9f&testName=jvm_compiler_2) 

[**Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2/12/) ⚠️ UNSTABLE ⚠️
jdk_nio_2 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=61704a83c6182d0217902de3) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=617049bac6182d0217902733&buildName=Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2&testId=61704a83c6182d0217902de3&testName=jdk_nio_2) 
jdk_tools_2 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=61704a83c6182d0217902df1) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=617049bac6182d0217902733&buildName=Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2&testId=61704a83c6182d0217902df1&testName=jdk_tools_2) 

[**Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux/27/) ❌ FAILURE ❌ **Ok to release**

Rerunning in grinder https://ci.adoptopenjdk.net/job/Grinder/1935/console

```
jdk_tools_0
jdk_tools_1
```

tools/jpackage/share/AddLauncherTest.java#id1.AddLauncherTest_id1
tools/jpackage/share/ArgumentsTest.java.ArgumentsTest
tools/jpackage/share/EmptyFolderTest.java.EmptyFolderTest
tools/jpackage/share/jdk/jpackage/tests/AppVersionTest.java.AppVersionTest
tools/jpackage/share/jdk/jpackage/tests/BasicTest.java.BasicTest
tools/jpackage/share/jdk/jpackage/tests/CookedRuntimeTest.java.CookedRuntimeTest
tools/jpackage/share/jdk/jpackage/tests/DotInNameTest.java.DotInNameTest
tools/jpackage/share/jdk/jpackage/tests/JLinkOptionsTest.java.JLinkOptionsTest
tools/jpackage/share/jdk/jpackage/tests/JavaOptionsEqualsTest.java#id0.JavaOptionsEqualsTest_id0
tools/jpackage/share/jdk/jpackage/tests/JavaOptionsEqualsTest.java#id1.JavaOptionsEqualsTest_id1
tools/jpackage/share/jdk/jpackage/tests/JavaOptionsTest.java.JavaOptionsTest
tools/jpackage/share/jdk/jpackage/tests/MainClassTest.java.MainClassTest
tools/jpackage/share/jdk/jpackage/tests/ModulePathTest.java.ModulePathTest
tools/jpackage/share/jdk/jpackage/tests/ModulePathTest2.java.ModulePathTest2
tools/jpackage/share/jdk/jpackage/tests/ModulePathTest3.java.ModulePathTest3
tools/jpackage/share/jdk/jpackage/tests/MultipleJarAppTest.java.MultipleJarAppTest
tools/jpackage/share/jdk/jpackage/tests/NoMPathRuntimeTest.java.NoMPathRuntimeTest

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /home/jenkins/workspace/Grinder_testList_0/aqa-tests/TKG/output_16348411798784/jdk_tools_0/work/scratch/2/testJavaOptions.1b2f3350/output/JavaOptionsAddLauncherTest/lib/runtime/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
```

Known test issue https://github.com/adoptium/aqa-tests/issues/2877

```
jdk_security_infra_0
jdk_security_infra_1
```

security/infra/java/security/cert/CertPathValidator/certification/DTrustCA.java.DTrustCA
security/infra/java/security/cert/CertPathValidator/certification/GlobalSignR6CA.java.GlobalSignR6CA
security/infra/java/security/cert/CertPathValidator/certification/HaricaCA.java.HaricaCA
security/infra/java/security/cert/CertPathValidator/certification/SSLCA.java.SSLCA

```
Execution failed: main' threw exception: java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status
```

Known infra issue https://github.com/adoptium/infrastructure/issues/2363

[**Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_0/14/) ❌ FAILURE ❌ **Ok to release (reran in grinder above)**
Post Test => [deep history 0/2 passed](https://trss.adoptium.net/deepHistory?testId=6170a219c6182d021791d0a4) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170a124c6182d021791cc19&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_0&testId=6170a219c6182d021791d0a4&testName=Post%20Test) 
jdk_tools_0 => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6170a219c6182d021791d0a6) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170a124c6182d021791cc19&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_0&testId=6170a219c6182d021791d0a6&testName=jdk_tools_0) 

[**Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_2/2/) ❌ FAILURE ❌ **Ok to release (reran in grinder above)**
Post Test => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6170a20ec6182d021791d07b) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170a124c6182d021791cc18&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_2&testId=6170a20ec6182d021791d07b&testName=Post%20Test) 
jdk_tools_1 => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6170a20ec6182d021791d075) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170a124c6182d021791cc18&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_2&testId=6170a20ec6182d021791d075&testName=jdk_tools_1) 

[**Test_openjdk17_hs_extended.openjdk_x86-64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux/29/) ⚠️ UNSTABLE ⚠️ **Ok to release**

[**Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0/15/) ⚠️ UNSTABLE ⚠️ **Ok to release**
jdk_security_infra_1 => [deep history 1/3 passed](https://trss.adoptium.net/deepHistory?testId=61705569c6182d0217906290) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170548fc6182d02179059a3&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0&testId=61705569c6182d0217906290&testName=jdk_security_infra_1) 

issue raised https://github.com/adoptium/infrastructure/issues/2363

[**Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_1/15/) ⚠️ UNSTABLE ⚠️ **Ok to release**
jdk_jfr_0 => [deep history 0/2 passed](https://trss.adoptium.net/deepHistory?testId=61705571c6182d02179062b6) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170548fc6182d02179059a4&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_1&testId=61705571c6182d02179062b6&testName=jdk_jfr_0) 
jdk_jmx_1 => [deep history 1/3 passed](https://trss.adoptium.net/deepHistory?testId=61705571c6182d02179062b5) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170548fc6182d02179059a4&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_1&testId=61705571c6182d02179062b5&testName=jdk_jmx_1) 

Rerunning on test-docker-fedora33-x64-1 https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1923/console
Test passed 

[**Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2/15/) ⚠️ UNSTABLE ⚠️ **Ok to release**
jdk_security_infra_0 => [deep history 2/3 passed](https://trss.adoptium.net/deepHistory?testId=61705561c6182d021790625a) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170548fc6182d02179059a2&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2&testId=61705561c6182d021790625a&testName=jdk_security_infra_0) 

issue raised https://github.com/adoptium/infrastructure/issues/2363

[**Test_openjdk17_hs_extended.openjdk_x86-64_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows/30/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0/17/) ⚠️ UNSTABLE ⚠️
jdk_tools_0 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=6170698dc6182d021790b959) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61706877c6182d021790b3bb&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0&testId=6170698dc6182d021790b959&testName=jdk_tools_0) 

[**Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_2/17/) ⚠️ UNSTABLE ⚠️
jdk_tools_1 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=61706995c6182d021790b9db) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61706877c6182d021790b3bc&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_2&testId=61706995c6182d021790b9db&testName=jdk_tools_1) 

[**Test_openjdk17_hs_extended.system_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.system_arm_linux/58/) ❌ FAILURE ❌ **Ok to release**
Rerunning on https://ci.adoptopenjdk.net/job/Grinder/1927/console with https://github.com/adoptium/aqa-tests/pull/3038 and https://github.com/adoptium/aqa-systemtest/pull/469
Test passed 👍🏻 

[**Test_openjdk17_hs_extended.system_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.system_x86-64_alpine-linux/74/) ❌ FAILURE ❌ **Ok to release**
Rerunning https://ci.adoptopenjdk.net/job/Grinder/1926/console with https://github.com/adoptium/aqa-tests/pull/3038 and https://github.com/adoptium/aqa-systemtest/pull/469
Test passed 👍🏻 

[**Test_openjdk17_hs_sanity.functional_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.functional_x86-64_alpine-linux/74/) ⚠️ UNSTABLE ⚠️ **Ok to release** 
cmdLineTester_libpathTestRtfChild_0 => [deep history 1/6 passed](https://trss.adoptium.net/deepHistory?testId=6170a10ec6182d021791cbf4) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61709fefc6182d021791c26c&buildName=Test_openjdk17_hs_sanity.functional_x86-64_alpine-linux&testId=6170a10ec6182d021791cbf4&testName=cmdLineTester_libpathTestRtfChild_0) 

`[ERR] Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /home/jenkins/workspace/Test_openjdk17_hs_sanity.functional_x86-64_alpine-linux/openjdkbinary/j2sdk-image/lib/libawt_xawt.so`
Similar to https://github.com/adoptium/aqa-tests/issues/2854#issuecomment-921784552. tests should be excluded for headless alpine linux https://github.com/adoptium/aqa-tests/issues/2877

[**Test_openjdk17_hs_sanity.openjdk_ppc64_aix**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.openjdk_ppc64_aix/71/) ⚠️ UNSTABLE ⚠️ **Ok to release** 
jdk_lang_1 => [deep history 3/6 passed](https://trss.adoptium.net/deepHistory?testId=6170bdbcc6182d021792679d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6170bce5c6182d0217926751&buildName=Test_openjdk17_hs_sanity.openjdk_ppc64_aix&testId=6170bdbcc6182d021792679d&testName=jdk_lang_1) 
Test raised https://github.com/adoptium/aqa-tests/issues/3075

[**Test_openjdk17_hs_sanity.openjdk_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.openjdk_x86-64_alpine-linux/74/) ⚠️ UNSTABLE ⚠️ **Ok to release**
jdk_lang_1 => [deep history 0/8 passed](https://trss.adoptium.net/deepHistory?testId=6170a12cc6182d021791cc46) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61709fefc6182d021791c270&buildName=Test_openjdk17_hs_sanity.openjdk_x86-64_alpine-linux&testId=6170a12cc6182d021791cc46&testName=jdk_lang_1) 
jdk_lang_0 => [deep history 0/8 passed](https://trss.adoptium.net/deepHistory?testId=6170a12cc6182d021791cc44) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61709fefc6182d021791c270&buildName=Test_openjdk17_hs_sanity.openjdk_x86-64_alpine-linux&testId=6170a12cc6182d021791cc44&testName=jdk_lang_0) 
Known issue https://github.com/adoptium/aqa-tests/issues/2385

[**Test_openjdk17_hs_sanity.system_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.system_arm_linux/58/) ❌ FAILURE ❌ **Ok to release**
Rerunning https://ci.adoptopenjdk.net/job/Grinder/1928/console with https://github.com/adoptium/aqa-tests/pull/3038 and https://github.com/adoptium/aqa-systemtest/pull/469
Test passed 👍🏻 

[**Test_openjdk17_hs_sanity.system_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.system_x86-64_alpine-linux/75/) ❌ FAILURE ❌ **Ok to release**
Rerunning in grinder https://ci.adoptopenjdk.net/job/Grinder/1925/console with https://github.com/adoptium/aqa-tests/pull/3038 and https://github.com/adoptium/aqa-systemtest/pull/469
Test passed 👍🏻

**Comment by smlambert** [comment]
Closing as complete.
