### ISSUE TITLE
Temurin Release JDK-18

### ISSUE THREAD

**Issue by Jotschi** [adoptium/adoptium#95]
Early development experiments with JDK 18 (Project Loom) are starting. It would be great if those could use the setup-java Github action. Unfortunately it seems there are no EA / nightly builds accessible to be used for the actions:

https://adoptium.net/releases.html?variant=openjdk18&jvmVariant=hotspot

Open JDK builds can currently be downloaded via https://jdk.java.net/18/

Are there any plans to provide those with adoptium as well?

**Comment by smlambert** [comment]
JDK18 EA builds have been available for some time via the API, so closing this issue as resolved.
