### ISSUE TITLE
Provide JDK/JRE 8 and 11 builds for Apple Silicon (M1/ARM/aarch64)

### ISSUE THREAD

**Issue by yogurtearl** [adoptium/adoptium#96]
Currently only JDK 17 has builds for Apple Silicon (M1/ARM/aarch64)

This request is to provide JDK/JRE **8** and **11** builds for Apple Silicon (M1/ARM/aarch64)

References: 
[Azul OpenJDK JRE and JDK 8 macOS ARM builds
](https://www.azul.com/downloads/?version=java-8-lts&os=macos&architecture=arm-64-bit)
[Azul OpenJDK JRE and JDK 11 macOS ARM builds
](https://www.azul.com/downloads/?version=java-11-lts&os=macos&architecture=arm-64-bit)

Previous related issue: 
https://github.com/adoptium/temurin-build/issues/1922

**Comment by karianna** [comment]
For Java 11 - Microsoft is back porting windows Arm (Jan PSU) and Azul are going to following up with the M1 back port on top of that (timeframe TBD).

Fro Java 8 - not sure yet.  Microsoft is going to look at the feasibility of the Windows ARM back port) and presumedly M1 could follow.  TBD though

**Comment by marcphilipp** [comment]
Any updates? I'm specifically interested in Java 11.

**Comment by karianna** [comment]
They were worked on at the end of last year.  We'll likely release them as part of this January's PSU release cycle (Jan 20th+).  Will depend on our success of passing the TCK with them.

**Comment by sclassen** [comment]
On https://github.com/adoptium/adoptium/issues/109 I only see MacOS x64 for Java 8 & 11
Can you give an update on the M1/ARM/aarch64 for Java 8 & 11

**Comment by mseele** [comment]
I guess they are waiting for https://github.com/openjdk/jdk11u-dev/pull/715 to get merged for Java 11.

**Comment by diogormendes** [comment]
Any news on these ??

**Comment by karianna** [comment]
Likely April PSU for Java 11 Mac Aarch, not 100% sure on 8 yet

**Comment by minhtran83** [comment]
Is there any update for this ticket?

**Comment by karianna** [comment]
April PSU is likely to have the 11 Port, the 8 port is still TBD

**Comment by sxa** [comment]
Nightly (early access) builds are now available with the usual "Not for production use, may have bugs, it's untested" at https://api.adoptium.net/v3/binary/latest/11/ea/mac/aarch64/jdk/hotspot/normal/adoptium

**Comment by mseele** [comment]
Will there be a aarch64 version of the april build?

```
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
```

```
❯ file /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java
/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java: Mach-O 64-bit executable x86_64
```

brew still installs the x86_64 variant...

**Comment by sxa** [comment]
It will be dependent on it pasing our quality assurance test suites.

**Comment by thelaurg** [comment]
Any update on this? Any timeline? When can I upgrade my macbook? :D

**Comment by IanE-Official** [comment]
Any update for this ticket?

**Comment by filipesilva** [comment]
Oct 2022 https://github.com/adoptium/adoptium/issues/180 seems to not have included the `aarch64 Mac` images.

Jan 2023 https://github.com/adoptium/adoptium/issues/202 also shows no `aarch64 Mac` images, but has some comments about it.

**Comment by frsnjung** [comment]
> 
> I presume this is because you wish to run older applications that still cannot run on Java 11+?

Yes, for example Databricks-connect requires specifically jdk8

**Comment by sdavids** [comment]
Why is this closed?

https://adoptium.net/temurin/archive/?version=8

Does not offer macOS aarch64.

**Comment by karianna** [comment]
> Why is this closed?
> 
> https://adoptium.net/temurin/archive/?version=8
> 
> Does not offer macOS aarch64.

OpenJDK 8u stream does not have Mac OS X Aarch support.

**Comment by sdavids** [comment]
This issue asks for 8 and 11 builds.

11 is available, 8 is not.

8 is not available due to upstream not being available.

So this issue should be closed when:

1. both 8 and 11 are available 
2. upstream decides not to backport — I am unsure if that announcement has been made

**Comment by theofficialgman** [comment]
> Fro Java 8 - not sure yet. Microsoft is going to look at the feasibility of the Windows ARM back port) and presumedly M1 could follow. TBD though

Any update on this part? There is still interest for both Windows and MacOS JDK 8 aarch64 backports

**Comment by karianna** [comment]
> > Fro Java 8 - not sure yet. Microsoft is going to look at the feasibility of the Windows ARM back port) and presumedly M1 could follow. TBD though
> 
> Any update on this part? There is still interest for both Windows and MacOS JDK 8 aarch64 backports

Unfortunately given the large engineering investment required for the backport and then it's maintenance, we (Microsoft) are not proceeding with this.

**Comment by theofficialgman** [comment]
> > Why is this closed?
> > https://adoptium.net/temurin/archive/?version=8
> > Does not offer macOS aarch64.
> 
> OpenJDK 8u stream does not have Mac OS X Aarch support.

@karianna something seems wrong with this statement. MacOS aarch64 is listed as back ported to jdk8u in 2022 https://bugs.openjdk.org/browse/JDK-8294161 in 8u361

**Comment by karianna** [comment]
Added to PMC agenda

**Comment by jerboaa** [comment]
> > > Why is this closed?
> > > https://adoptium.net/temurin/archive/?version=8
> > > Does not offer macOS aarch64.
> > 
> > 
> > OpenJDK 8u stream does not have Mac OS X Aarch support.
> 
> @karianna something seems wrong with this statement. MacOS aarch64 is listed as back ported to jdk8u in 2022 https://bugs.openjdk.org/browse/JDK-8294161 in 8u361

There is nothing wrong with this statement. What you see there is that Oracle included MacOS aarch64 patches to their private fork (i.e. pertains to Oracle JDK 8). OpenJDK 8u still doesn't have support for it and somebody would have to invest the time to backport it.

> Additionally, it seems that many other builders of openjdk 8 have macos-arm64 releases https://javaalmanac.io/jdk/8/

Sure, it comes up every once in a while (to bring to upstream 8u). Apparently it's not something those downstream builders have brought to upstream OpenJDK 8u yet. With my OpenJDK 8u maintainer hat on, it's something not immediately pressing as the current x64 port for Mac works with Rosetta. Besides, 8u is a done release and the bar is extremely high for patches to go in.

There is also the option to move away from the old legacy release and have the native port.

Overall, I don't think there is anything for the PMC to discuss.

**Comment by theofficialgman** [comment]
> What you see there is that Oracle included MacOS aarch64 patches to their private fork (i.e. pertains to Oracle JDK 8). OpenJDK 8u still doesn't have support for it and somebody would have to invest the time to backport it.
> 
> > Additionally, it seems that many other builders of openjdk 8 have macos-arm64 releases https://javaalmanac.io/jdk/8/
> 
> Sure, it comes up every once in a while (to bring to upstream 8u). Apparently it's not something those downstream builders have brought to upstream OpenJDK 8u yet. With my OpenJDK 8u maintainer hat on, it's something not immediately pressing as the current x64 port for Mac works with Rosetta. Besides, 8u is a done release and the bar is extremely high for patches to go in.

Maybe this aarch64 MacOS Openjdk 8 PR was from one of those maintainers https://github.com/openjdk/jdk8u/pull/38 ?
To me it seems likely not but instead an independent backport of the jdk11 code that lacks proper authorship. If someone wants to take a closer look I think it would be worth it.

**Comment by theofficialgman** [comment]
> > > OpenJDK 8u stream does not have Mac OS X Aarch support.
> > 
> > 
> > @karianna something seems wrong with this statement. MacOS aarch64 is listed as back ported to jdk8u in 2022 https://bugs.openjdk.org/browse/JDK-8294161 in 8u361
> 
> There is nothing wrong with this statement. What you see there is that Oracle included MacOS aarch64 patches to their private fork (i.e. pertains to Oracle JDK 8). OpenJDK 8u still doesn't have support for it and somebody would have to invest the time to backport it.

@fmatte1 as the assignee for https://bugs.openjdk.org/browse/JDK-8294161 , could you provide more insight on this? Same goes for @AntonKozlov as the reporter and assignee of the original report https://bugs.openjdk.org/browse/JDK-8253795

**Comment by AntonKozlov** [comment]
The change is pretty large, for jdk8u we were discussing a refactoring to reduce the size and possible negative impact. However, the refactoring stuck in the upstream. @snazarkin can provide more context.
